### ISSUE TITLE
Error in split view for a particular html file

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1511] opened 2012-01-09 20:59 UTC
I have an HTML file that throws an error in the Design pane when I try to switch to a split view. The source is shown in the bottom pane, but the design pane just gets a red background and the error below. NOTE: It's possible to use split pane in my env with other HTML files (like Sample1.html), but not this particular one.

Uh oh! An error has occurred:
Tried to register widget with id==span_6 but that id is already registered
Error: Tried to register widget with id==span_6 but that id is already registered at Object.add (dijit/dijit:15:27356) at [object Object].create (dijit/dijit:15:69748) at [object Object].postscript (dijit/dijit:15:69379) at new (http://localhost:50000/maqetta/user/maqettaUser/ws/workspace/project1/lib/dojo/dojo/dojo.js:15:57008) at [object Object]. (dojo/parser:180:30) at Object._3de [as forEach](http://localhost:50000/maqetta/user/maqettaUser/ws/workspace/project1/lib/dojo/dojo/dojo.js:15:105594) at [object Object].instantiate (dojo/parser:56:4) at [object Object].parse (dojo/parser:292:13) at [object Object]. (davinci/davinci:46643:44) at http://localhost:50000/maqetta/user/maqettaUser/ws/workspace/project1/lib/dojo/dojo/dojo.js:15:112007

---

Environment: Chrome, local install
Version: Preview 4
Date: Jan 9, 2012 2:12:26 PM
Build: e57f533dce68662...

**Comment by waynevicknair** [comment] 2012-01-09 21:33
this is probably a duplicate of issue #1509

**Comment by aerwin** [comment] 2012-01-09 21:40
As for relation to 1509, I never edited the source (since I couldn't use the split pane) so Maqetta itself must have corrupted the file in this case.

**Comment by JonFerraiolo** [comment] 2012-01-09 22:14
Could you please copy/paste the source code for the file that causes the design view to turn red?

**Comment by aerwin** [comment] 2012-01-09 22:20
Yes...

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<style>@import "themes/claro/claro.css";@import "lib/dojo/dojo/resources/dojo.css";@import "lib/jquery-ui/css/smoothness/jquery-ui-1.8.11.custom.css";@import "lib/yui/calendar/assets/skins/sam/calendar.css";@import "app.css";
</style>
<script type="text/javascript" src="maqetta/maqetta.js"></script>
<script type="text/javascript" data-dojo-config="'async':true,'parseOnLoad':true,'packages':[{'name':'clipart','location':'../../clipart'},{'name':'shapes','location':'../../shapes'},{'name':'jquery-ui','location':'../../jquery-ui'},{'name':'yui','location':'../../yui'}]" src="lib/dojo/dojo/dojo.js"></script>
<script type="text/javascript" src="lib/jquery-ui/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="lib/jquery-ui/jquery-ui-1.8.11.custom.min.js"></script>
<script type="text/javascript" src="lib/yui/yahoo-dom-event/yahoo-dom-event.js"></script>
<script type="text/javascript" src="lib/yui/calendar/calendar-min.js"></script>
<script type="text/javascript" src="maqetta/States.js"></script>
<script type="text/javascript">
require(["dijit/dijit"]);
require(["dojo/parser"]);
require(["dijit/form/Button"]);
require(["dijit/Calendar"]);
require(["dijit/form/TextBox"]);
require(["dijit/form/MultiSelect"]);
require(["dijit/layout/ContentPane"]);
require(["dijit/layout/AccordionContainer"]);
require(["dijit/layout/TabContainer"]);
require(["dijit/form/CheckBox"]);
require(["dijit/form/ComboBox"]);
require(["dijit/form/DropDownButton"]);
require(["dijit/Menu"]);
require(["dijit/MenuItem"]);
require(["dijit/form/ComboButton"]);</script>
</head>
<body class="claro" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp">
 <input type="button" dojoType="dijit.form.Button" intermediateChanges="false" label="Button" iconClass="dijitNoIcon"></input>
 <input dojoType="dijit.Calendar"></input>
 <span dojoType="dijit.layout.TabContainer" tabStrip="false" persist="false" controllerWidget="dijit.layout.TabController" style="width: 300px; height: 300px; min-width: 1em; min-height: 1em;"><div dojoType="dijit.layout.ContentPane" title="Tab 1" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" closable="false" style="width: 300px; height: 260px;">
   <input type="button" dojoType="dijit.form.Button" intermediateChanges="false" label="Button" iconClass="dijitNoIcon"></input>
   <select dojoType="dijit.form.ComboBox" value="Item 1" intermediateChanges="false" trim="false" uppercase="false" lowercase="false" propercase="false" required="false">
     <option dvwidget="html.option" value="Item 1">
       Item 1</option>
     <option dvwidget="html.option" value="Item 2">
       Item 2</option>
     <option dvwidget="html.option" value="Item 3">
       Item 3</option>
   </select>
 </div>
 <div dojoType="dijit.layout.ContentPane" title="Tab 2" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" style="width: 282px; height: 253px;"></div>
 </span><input type="text" dojoType="dijit.form.TextBox"></input>
 <input type="button" dojoType="dijit.form.Button" intermediateChanges="false" label="Button" iconClass="dijitNoIcon"></input>
 <img src="SampleBanner.jpg"></img>
 <div></div>
<span></span>
<label>
 my label</label>
<div dvwidget="YAHOO.widget.Calendar">
 <div id="widget_1934cal1Container" class="yui-skin-sam"></div>
 <script>(new YAHOO.widget.Calendar('widget_1934cal1Container')).render();</script>
</div>
<div dojoType="dijit.layout.ContentPane" title="Pane" doLayout="false" style="width: 645px; height: 465px;">
 <input type="checkbox" dojoType="dijit.form.CheckBox"></input>
 </div>
<select multiple="multiple" dojoType="dijit.form.MultiSelect" intermediateChanges="false" style="width: 200px;">
  <option dvwidget="html.option" value="Item 1">

     Item 1</option>
  <option dvwidget="html.option" value="Item 2">

     Item 2</option>
  <option dvwidget="html.option" value="Item 3">

     Item 3</option>
</select>
<span dojoType="dijit.form.ComboButton" intermediateChanges="false" label="Combo Button" iconClass="dijitNoIcon" dropDownPosition="below"><span dojoType="dijit.Menu" contextMenuForWindow="false" leftClickToOpen="false" tabIndex="0"><span dojoType="dijit.MenuItem" label="Option 1" iconClass="dijitNoIcon"></span><span dojoType="dijit.MenuItem" label="Option 2" iconClass="dijitNoIcon"></span>
</span><span dojoType="dijit.Menu"><span dojoType="dijit.MenuItem" label="Option 1"></span><span dojoType="dijit.MenuItem" label="Option 2"></span>
</span>
</span><span dojoType="dijit.layout.AccordionContainer" style="width: 300px; height: 300px; min-width: 1em; min-height: 1em;">
<div dojoType="dijit.layout.ContentPane" title="Pane 1" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" style="width: 274px; height: 224px;" doLayout="false">
 <input type="button" dojoType="dijit.form.Button" intermediateChanges="false" label="Button" iconClass="dijitNoIcon"></input>
<span dojoType="dijit.form.DropDownButton" intermediateChanges="false" label="Drop Down" iconClass="dijitNoIcon"><span dojoType="dijit.Menu" contextMenuForWindow="false" leftClickToOpen="false" tabIndex="0"><span dojoType="dijit.MenuItem" label="Option 1" iconClass="dijitNoIcon"></span><span dojoType="dijit.MenuItem" label="Option 2" iconClass="dijitNoIcon"></span>
 </span>
 </span></div>
<div dojoType="dijit.layout.ContentPane" title="Pane 2" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" style="width: 274px; height: 224px;" doLayout="false"></div>
</span>
<div><span dojoType="dijit.form.ComboButton" intermediateChanges="false" label="Combo Button" iconClass="dijitNoIcon" dropDownPosition="below"><span dojoType="dijit.Menu" contextMenuForWindow="false" leftClickToOpen="false" tabIndex="0"><span dojoType="dijit.MenuItem" label="Option 1" iconClass="dijitNoIcon"></span><span dojoType="dijit.MenuItem" label="Option 2" iconClass="dijitNoIcon"></span>
 </span>
 </span>
<input type="button" dojoType="dijit.form.Button" intermediateChanges="false" label="Button" iconClass="dijitNoIcon"></input>
</div>
</body>
</html>
```

**Comment by aerwin** [comment] 2012-01-09 22:22
Well, doesn't look like pasting was so successful... I can send the file separately...

**Comment by JonFerraiolo** [comment] 2012-01-10 00:16
Ah, in GitHub, surround code with triple backquotes (before and after). What's weird is that I'm not seeing the red error message. This is what I did:
- New HTML File
- Split view
- Copy above source code to clipboard, then in source view, select all of the initial source code for the new file, and the issue a Ctrl-V to paste/replace with the clipboard contents

After doing the above, I see the HTML file contents successfully. I am running this morning's build from macwayne2 using Mac/Chrome.

**Comment by aerwin** [comment] 2012-01-10 00:40
I just tried what you did on my local server (e.g., pasting source into code pane of new HTML file) and that does indeed appear to work.

BUT, I notice if I save that HTML file, close it, and re-open it that I see the originally reported behavior. Very weird.

**Comment by aerwin** [comment] 2012-01-10 00:44
Turns out I don't even have to save and close it... e.g., paste into source pane and see it get rendered (which works like you noted), then click Design icon, then click back on horizontal split pane again.

**Comment by JonFerraiolo** [comment] 2012-01-10 01:09
I'm trying to get to the bottom of this. Raising this to Priority-High/M4 until we figure out what's going wrong here. Note that there are jQuery and YUI elements in the original source code. I tried hand-editing the above file to remove all pieces of jQuery and YUI, but it is still failing.

**Comment by JonFerraiolo** [comment] 2012-01-10 01:09
@peller, @waynevicknair, @childsb, @billreed63, @jhpedemonte

**Comment by peller** [comment] 2012-01-10 04:21
The TabContainer is trying to claim id=span_6 where it's still taken by the previous parse of the document.  Are we supposed to be destroying the old elements?  Not sure that would even matter in this case?

At first, I was worried that we were creating the id off the wrong document (workplace vs. user space, need to wrap in something like dojo.withDoc or this.getGlobal()) as I've seen that bug in the past.  But that doesn't seem to be the case.  My best guess is that we're asking dijit.getUniqueId() and context.getUniqueId() for the same widgetType ("span")  The context code checks the DOM before incrementing the counter, where dijit keeps its own hash within a closure.  States.js seems to run over the document and call dijit.getUniqueId.

**Comment by peller** [comment] 2012-01-10 07:13
So States and dijit.getUniqueId() did not seem to be involved here.  It was just Context.getUniqueId() handing out the same id twice.  In the previous parse, span_6 went to a Menu inside a ComboButton.  On this parse, Context.getUniqueId() looked for span_6 in the DOM and when it wasn't there tried to use it again.  The Menu still exists in the registry, however.  Apparently it was never added to the DOM, since it was a popup.

Inserting the following code at Context.js:1074 to completely destroy all widgets in the dijit.registry, after the recursive destroy of "getTopWidgets", seems to fix the problem:

``` javascript
        // remove all registered widgets
        this.getDijit().registry.forEach(function(w){
              w.destroy();           
        });
```

**Comment by jhpedemonte** [comment] 2012-01-10 14:37
Well, I think this is a bigger issue than just the registry.  Basically, we're still keeping around the whole JS context -- this could lead to other issues in the future.  Is it too much to regenerate the iframe, in order to kill the JS context and start anew?

**Comment by peller** [comment] 2012-01-10 15:02
I agree.  It's worrisome.  "Destroying" all the widgets works, in theory, for Dijit if there are no global leaks or leaks of any other sort.  That's hard to guarantee, especially when we start introducing other libraries.  Performance may not be too great if we recreate the whole iframe.  Worth trying.  I'd suggest considering the above patch for M4, though.

**Comment by JonFerraiolo** [comment] 2012-01-10 15:15
yep, I like the patch, too

**Comment by JonFerraiolo** [comment] 2012-01-10 15:15
Reassigning to @peller

**Comment by waynevicknair** [comment] 2012-01-10 15:26
what if we strengthen Context.getUniqeId() by having it check the dijit.registry? the registry is a WidgetSet that has a byId() method and a remove() method if we want to be less kind and gentle.

**Comment by JonFerraiolo** [comment] 2012-01-10 15:41
I agree with @waynevicknair that improving Context.getUniqueId() to also check the dijit registry would be a good thing to do from the point of view of doing responsible, paranoid programming, but it sounds like Adam has a fix for M4. Maybe this suggestion could go into M5. If we did check the Dijit registry, we probably should have a "library helper" so that we aren't just hardcoding things for Dijit.

**Comment by peller** [comment] 2012-01-10 15:43
Either way, I'm sure @jhpedemonte would point out, it's an awkward dependency on Dijit.  Between the two, I like the nuclear option better.

**Comment by waynevicknair** [comment] 2012-01-10 15:47
sounds good. i'll open an M5 issue to track getUniqueId() change. i also agree that @peller 's fix is the proven change to go with for M4.

**Comment by peller** [comment] 2012-01-10 15:53
proven only by a night's sleep.

**Closed as completed** 2012-01-10 15:56 UTC
Labels: Visual Editor
