### ISSUE TITLE
Exception if putting a class on a Menu within MenuBar

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1636] opened 2012-01-25 21:10 UTC
@peller 
- New HTML File
- Add a MenuBar, enter these values:

```
aa
bb
cc
```
- Click to select the "cc" entry in the MenuBar (this is a PopupMenuBarItem widget)
- In properties palette, enter "zzz" for class attribute

Result=> Exception at PopupMenuItem.js:18 within the guts of Dojo because this.popup.domNode is null.

I can imagine that fixing this might be complex. The user who ran into this bug had the ultimate objective of assigning a 'float:right' property to the 3rd menu so that it would be right-justified. The user's goal was to have the 3rd menu item be right-justified, but every more to the point, he wants to put the 'float:right' property in a CSS style rule within app.css using the cascade UI in the Properties palette.

**Comment by billreed63** [comment] 2012-02-02 20:09
It looks like the root cause of this is that PopupMenuBarItemHelper does not have a getData() method.

dijit.PopupMenuBarItem is expecting a popup Menu (dijit.Menu), dijit.PopupMenuBarItem.pop. When we change the class on the PopupMenuBarItem we create a ModifyCommand and execute. ModifyCommand. execute does a widget.getData becouse the helper has no getData() the default is used which returns a data.properties.pop instead of converting the pop to children. We then destroy the original  PopupMenuBarItem which destroys the pop.domNode, and because we did not convert the pop to children they do not get created when we create the new PopupMenuBarItem, instead the pop is added as a property and it has no domNode leading to the exception.

So the fix is to create a getData method in PopupMenuBarItemHelper that will convert the pop submenu to children and add them to the data that is returned. This code is currently in the MenuBarHelper, which seems like the wrong place. I think when we add the getData to the PopupMenuBarItemHelper we will need to remove it from MenuHelper...

**Comment by billreed63** [comment] 2012-02-02 22:44
fixed by 6c3adc3257f367a6d2811b50377527e0b35ebb29

**Closed as completed by billreed63** 2012-02-02 22:44 UTC
Labels: Widget Libraries, Priority High
