### ISSUE TITLE
Unable to delete file from file exploer

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#649] opened 2011-07-05 16:16 UTC
Add a new HTML file, such as mmm.html (see above for instructions). Close the page editor tab that appears. Then, in the Files palette, click on mmm.html and then click the right mouse button (or Ctrl-click on Mac) to bring up context menu and choose "Delete resource". Click OK on "are you sure" warning dialog. The Files palette should no longer show the file.

**Comment by billreed63** [comment] 2011-07-05 16:17
delete files
Steps

```
You'll want to set up a virgin user environment by creating a whole new user login or resetting the existing user login (ask engineers about how to do that). Clear the browser cache. Launch the Maqetta server. Login if necessary.
Add a new HTML file, such as mmm.html (see above for instructions). Close the page editor tab that appears. Then, in the Files palette, click on mmm.html and then click the right mouse button (or Ctrl-click on Mac) to bring up context menu and choose "Delete resource". Click OK on "are you sure" warning dialog. The Files palette should no longer show the file.
Create a new folder (see instructions above), perhaps named "nnn". Add a new file (e.g., ooo.html) into that folder (see instructions above). Close the page editor tab that appears. Then, in the Files palette, click on ooo.html and then click the right mouse button (or Ctrl-click on Mac) to bring up context menu and choose "Delete resource". Click OK on "are you sure" warning dialog. The Files palette should no longer show the file.
Create a new folder (e.g., www) and add a file into that folder (e.g., via New operations - see instructions above for how to do this.) In the Files palette, click on www and then click the right mouse button (or Ctrl-click on Mac) to bring up context menu and choose "Delete resource". Click OK on "are you sure" warning dialog. The Files palette should no longer show the folder (or any of the files that were in the folder).
```

All test cases fail, I get a message no resources selected

**Comment by jhpedemonte** [comment] 2011-07-05 16:18
Dupe of #628.

**Closed as completed by jhpedemonte** 2011-07-05 16:18 UTC
Labels: Files View, Bug

**Comment by billreed63** [comment] 2011-07-05 16:19
download is disabled, maybe related to not detecting the selected resourse
