### ISSUE TITLE
Upload file dialog won't upload

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1689] opened 2012-02-03 20:35 UTC
Using Chrome with local install on Windows, I can add a file to the File Upload dialog. But, clicking "Upload" button on dialog has no impact. Dialog stays up, and no errors in JavaScript console or server console.

**Comment by JonFerraiolo** [comment] 2012-02-03 21:07
Dupe of #1668

**Closed as completed by JonFerraiolo** 2012-02-03 21:07 UTC
Labels: Bug
