### ISSUE TITLE
Source editor does moves cursor to position 1,1 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#866] opened 2011-08-26 18:07 UTC
If I am typing in the middle of the page and pause for a second the source editor does a setSource which causes the cursor to move to the first line and first position (1,1). The effect is that if I am deleting or add content in unintended places making the source editor unusable

**Comment by peller** [comment] 2011-08-26 18:10
@WayneVicknair, is this what you're seeing?

**Comment by waynevicknair** [comment] 2011-08-26 18:14
duplicate of #865

**Closed as completed by waynevicknair** 2011-08-26 18:14 UTC
Labels: Bug, Priority High

**Comment by billreed63** [comment] 2011-08-26 18:23
fixed by #865
