### ISSUE TITLE
Workspace has become unusable (can't open or create HTML files)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2263] opened 2012-05-14 19:48 UTC
I was doing testing on our server hosting our "external" GitHub-sources-only build. I left for lunch and came back. I had been logged out (which is fine), but now when I log back in I can't view any of my existing HTML files or create a new one. I see the following when trying to create a new one:

```
Error opening editor for filename: ./project1/file8.html 
TypeError
_3bb.openEditordavinci.js:4789
_172dojo.js:1711
dojo.Deferred._16f.then.thendojo.js:1771
_3bb.openEditordavinci.js:4781
_99b.openResourcedavinci.js:11339
_99b.newHTML._9a2davinci.js:11040
(anonymous function)davinci.js:4419
_383dojo.js:4555
_492.(anonymous function)dojo.js:6092
_181c._okButtondavinci.js:31592
_383dojo.js:4551
_492.(anonymous function)dojo.js:6092
_17cf._onClickdavinci.js:31011
_25edojo.js:2636
_25db._onClickdavinci.js:53787
_383dojo.js:4551
_1e3dijit.js:193
```

**Comment by aerwin** [comment] 2012-05-14 19:50
The last thing I was doing before lunch was states testing. I was at about Step 5 of "Changing properties in different states" in the StatesPalette/basic.html test cases.

**Comment by JonFerraiolo** [comment] 2012-05-14 21:22
-> me - I'll try to figure out what's wrong. I'm actually having a similar problem with my own account on Maqetta.org

**Comment by JonFerraiolo** [comment] 2012-05-15 20:08
With only the stack trace to go with, I tried to look through the source code for Workbench.openEditor and Workbench._createEditor to see how it might be possible to have a TypeError, and nothing leaped out at me. I'll keep looking.

(updated) I tried to corrupt my workspace in various ways and put a bad HTML file in my workspace so that a broken file would load, and I couldn't reproduce the same problems.

Unless some more information appears, we'll probably have to push or close this one.

**Closed as completed** 2012-05-18 22:46 UTC
Labels: Bug, Priority High
