### ISSUE TITLE
Toolbar icons "jiggle" as hover over them

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2655] opened 2012-07-02 02:23 UTC
Open an HTML file and move your mouse over the toolbar icons.  Notice that they jiggle.

Regression from Dojo 1.8 beta?  Assigning to @peller for now, to investigate.  Send it back to me if this isn't the case.

I'm guessing that there's some discrepancy in the CSS for the icons, where margins/padding are incorrect.

@JonFerraiolo @doronrosenberg

**Comment by JonFerraiolo** [comment] 2012-07-02 18:21
I'm seeing the same jiggling with Preview6 when using Chrome. No jiggling icons with Firefox.

**Comment by peller** [comment] 2012-07-02 18:37
and only horizontal jiggling this time.  It looks like the button content box (not padding or margin) changes its size during mouseover, but none of the child elements change size.  Does that make any sense?  I don't see any style rules appear in the Chrome debugger, but there must be some taking effect.

**Comment by JonFerraiolo** [comment] 2012-07-19 18:30
I'm seeing the same jiggling in Dojo's own test files (i.e., Maqetta not involved). Go to http://dojotoolkit.org/reference-guide/1.7/dijit/Toolbar.html and try running the "Declarative example". I'm also seeing the same thing when running Dojo 1.8 toolbar tests from localhost (http://localhost/.../dojo18beta/dijit/tests/test_Toolbar.html). So, something changed in Chrome that makes Dojo toolbars jiggle for everyone, not just Maqetta.

My first guess as to what might be the problem is CSS3 animations or transitions because of the likelihood of obscure bugs creeping in.

**Comment by JonFerraiolo** [comment] 2012-07-19 18:37
Yep, that's it. In debugger, I changed the value of `-webkit-transition-duration` on `.claro .dijitToolbar .dijitButton .dijitButtonNode` and the jiggling went away.

**Comment by peller** [comment] 2012-07-19 19:15
created a [Dojo ticket](http://bugs.dojotoolkit.org/ticket/15723)

**Comment by jhpedemonte** [comment] 2012-07-19 22:08
So if I'm reading the Dojo ticket correctly, then the fix should be in for Dojo 1.8.  Can we remove these commits when we move up to 1.8 final?

**Comment by JonFerraiolo** [comment] 2012-07-20 00:39
por supuesto

**Comment by peller** [comment] 2012-07-20 02:49
@jhpedemonte yes, that patch should actually be in 1.8.0rc1, which I just added to the build.

With that _and_ Jon's fix, I'm still seeing the jiggle.  Is it just me?

**Comment by JonFerraiolo** [comment] 2012-07-20 14:29
I just did a "git pull" and I don't see any jiggling on Mac/Chrome.

**Comment by JonFerraiolo** [comment] 2012-08-03 15:04
Closing. No jiggling on Chrome now with latest Dojo and UI makeover.

**Closed as completed by JonFerraiolo** 2012-08-03 15:04 UTC
Labels: Priority High, UI, Regression, Severity 2
