### ISSUE TITLE
Reviewer comment emails should include link to review session

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1108] opened 2011-10-28 14:33 UTC
@EldonReturn, @jmockler

With Preview 3, when a reviewer adds a comment, the author gets an email, but there is no hyperlink to the review session. The author has to dig through old emails to find the original invitation to find the link to the review session. This is highly inconvenient.

Given the consolidation of R&C code with core, I'm not sure how this one will shake out, but logging the issue nonetheless. I'm assigning to @waynevicknair instead of @EldonReturn because we have to let the dust settle on the consolidation effort before seeing how to address this issue.

**Comment by waynevicknair** [comment] 2011-11-17 15:59
this issue is a duplicate of issue #1026

**Closed as completed by waynevicknair** 2011-11-17 15:59 UTC
Labels: Review and Commenting, Priority Med, UI
