### ISSUE TITLE
DataGrid and Tree problems

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1774] opened 2012-02-17 23:34 UTC
I pulled latest code and tried out DataGrid and Tree.
- DataGrid brings up SmartInput, but upon clicking OK, nothing appears on canvas
- Tree works OK, but if I copy the Tree and then paste, a second Tree does not appear on the canvas

**Comment by peller** [comment] 2012-02-18 00:26
Tree copy/paste problem is duplicate of #1768

**Comment by JonFerraiolo** [comment] 2012-02-18 00:43
@peller might be related to #1771

**Comment by peller** [comment] 2012-02-19 23:10
There's an exception deep in the construction of the DataGrid, as triggered by the ModifyCommand in DataGridInput.  Apparently this.store is a string, not an object (e.g. "ItemFileReadStore_1")

Uncaught TypeError: Object ItemFileReadStore_1 has no method 'getFeatures'

@billreed63, at which point should the string in the markup (store=) get converted to a data store object?

**Closed as completed** 2012-02-20 16:33 UTC
Labels: Widget Libraries, Priority High, Regression
