### ISSUE TITLE
Server exception when opening sample1.html in page editor

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2878] opened 2012-08-07 18:04 UTC
org.eclipse.core.runtime.CoreException: Could not write file: C:\maqetta-workspace\a\samples\Sample1.html.workingcopy.
    at org.eclipse.core.internal.filesystem.Policy.error(Policy.java:55)
    at org.eclipse.core.internal.filesystem.local.LocalFile.openOutputStream(LocalFile.java:391)
    at maqetta.server.orion.VOrionStorage.createNewFile(VOrionStorage.java:155)
    at org.maqetta.server.VFile.createNewInstance(VFile.java:126)
    at maqetta.core.server.DavinciPageServlet.doPut(DavinciPageServlet.java:83)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:758)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrapper.service(ServletManager.java:180)
    at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service(ServletRegistration.java:61)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:38)
    at org.eclipse.orion.internal.server.hosting.HostedSiteRequestFilter.doFilter(HostedSiteRequestFilter.java:50)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)
    at org.eclipse.equinox.http.servlet.internal.FilterRegistration.doFilter(FilterRegistration.java:81)
    at org.eclipse.equinox.http.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:35)
    at org.eclipse.orion.server.configurator.servlet.WelcomeFileFilter.doFilter(WelcomeFileFilter.java:92)
    at org.eclipse.equinox.http.registry.internal.FilterManager$FilterWrapper.doFilter(FilterManager.java:173)

**Comment by childsb** [comment] 2012-08-21 16:50
dupe of #2971

**Closed as completed by childsb** 2012-08-21 16:50 UTC
Labels: Bug, Priority High, Severity 2
