### ISSUE TITLE
Second View has display:none, can't drop widgets into it

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#686] opened 2011-07-09 17:52 UTC
@peller

(Working on tutorials and ran into this)

dojox.mobile has logic that tries to manage View visibility (via display property) and enforce the constraint that only one View is visible at once. This logic conflicts with Maqetta authoring. (More about that later)

But first, the technical details. Turns out that the startup() method in dojox/mobile/View.js gets called indirectly from the Maqetta creation logic. I'm not sure of exact mechanism because the Chrome debugger was somewhat confused when I tried to trace through the code (probably some issues with deobfuscation), but I'm 99% sure that AddCommand.js:48 calls widget.startup(), which goes to widget.js:1575 (davinci.ve.DijitWidget class), which then calls this.dijitWidget.startup();). This takes us into dojox/mobile/View.js:62, which has the following logic:

```
        startup: function(){
...
            // if no visible view exists, make the first view visible
            if(siblings.length === 1 || (!visible && siblings[0] === this.domNode)){
                _visible = true;
            }
            var _this = this;
            setTimeout(function(){ // necessary to render the view correctly
                if(!_visible){
                    _this.domNode.style.display = "none";
                }else{
                    dojox.mobile.currentView = _this;
                    _this.onStartView();
                    dojo.publish("/dojox/mobile/startView", [_this]);
                }
...
            }, dojo.isIE?100:0); // give IE a little time to complete drawing
            this.inherited(arguments);
        },
```

The authoring issue is that if an author wants to create an application with 2 Views (or 2 ScrollableViews or 2 SwapViews), the above logic will set display:none for every subsequent View (i.e., all but the first one). Because of the setTimeout, there is a brief moment when the new View is visible, and (I'm pretty sure) it just so happens that this is when we compute the bounding box for the View in order to draw the selection chrome. But once the timeout logic executes, the new View becomes invisible (display:none), but it looks to the user like the View is there because we show selection chrome around it. So, now the user tries to drag a widget (e.g., a Heading) onto his new View, and up comes the alert that says "No valid target...", even if the user attempts to drop the Heading inside of the selection chrome for the (now invisible) View. The "No valid target..." message comes up because the browser event mechanism will not set the View as the event.target because it has display:none. Another problem is that the Outline palette is wrong - it shows an open eye instead of a closed eye. (When display:none, the Outline should show a closed eye.)

The user workaround with the current code is to go to the Outline palette and click on the eyeball for the new View twice - the first click to get the Outline palette back in sync with reality (i.e., display:none), and the second click to make the View visible. This is a very ugly workaround.

I'm pretty sure that we want new Views to be visible (i.e., display:block) at creation time and thereby bypass the attempted display property management by dojox.mobile, and instead the page editor should manage widget visibility. Within the page editor, (overly simplified claim) we disable all of the other runtime processing in widget libraries by masking out and/or intercepting all runtime events, such as mouse clicks, so allowing dojo.mobile to manage the 'display' property at creation time makes no sense since we disable all other subsequent processing.

My suggestion is to force display:block on View elements at widget creation time. But how to implement this is likely to be a bit tricky since we are having to patch around some asynchronous logic (i.e., the timeout). Probably easy to do a horrible timeout hack that hard-codes a check for particular widgets, but harder to achieve this will a clean and robust manner.

**Comment by jhpedemonte** [comment] 2011-07-11 04:33
This is something we've discussed before, but I haven't been paying attention to lately, concentrating on other bugs.

If you recall (do we already have an issue on this?), I had wondered about integrating View visibility with the States view, such that the user could work with a given View by clicking on the eyeball, to make it visible.  The trick would be to then make sure that any visible View is hidden before showing the newly selected View.

Same thing for dropping a View on the page: existing View is hidden, new View is made visible.

I don't think this is a good, intuitive UI, but it'll do for now, given what we have with Maqetta.  The question is how easy will it be to do this integration with the States view.  Adam, care to weigh in?

**Comment by jhpedemonte** [comment] 2011-07-14 17:06
This is what I just did and seems to work well:

Dropped first View and added Heading and ListView.  Then hid that View in Outline and dropped a 2nd View.  Added Heading.  Hid this one through Outline and dropped a 3rd View.  Added Heading.  Made appropriate changes to ListView items went to _view2_ and _view3_, and Headings in those views went back to _view1_.

That worked well for me and didn't require doing any CreateTool methods for View (still confused about the whole **display:block** scenario in the summary).

One issue I found is that before doing Preview, the user would have to make sure that the **selected** (or **first**, if _selected_ isn't set on any view) View would have to be made visible in Outline.  Otherwise, Preview comes up blank, since the starting View has `display: none` set.

So maybe this is something we handle through tutorials for now, until we have a better solution?

**Comment by jhpedemonte** [comment] 2011-07-15 02:48
Checkin fixes this for the most part.  I had to resort to using a `setInterval()` since there wasn't any event I could latch on to.  But I made sure to add enough checks so it doesn't cause issues.

One scenario that still isn't fixed:
- Drop a View.
- Drop a View inside of that View.
- In Outline, drag inner View to be sibling of outer View.

The result is that there are 2 Views now visible in the VE, each taking "100%", meaning that page is double the height of the viewable area.

I thought I could fix this by adding a check before setting `"display: block"` -- the idea being to not make a View visible if there is already a sibling View that is visible.  But the issue is that the inner View already has `"display: block"` set, so moving it up a level results in 2 Views with `"display: block"`;  `View.startup()` isn't called again when moving the View, so the 2nd one doesn't get set as `"display: none"`.

But this issue can probably wait until after M2?  What do you think, Jon?

**Comment by JonFerraiolo** [comment] 2011-07-15 13:53
I played with it some this morning and so far looks good enough for M2. Maybe close this bug and create other bugs for things we need to do in M3?

**Closed as completed** 2011-07-15 14:58 UTC
Labels: Widget Libraries, Priority High, Mobile
