### ISSUE TITLE
Dojo control not responding to state

### ISSUE THREAD

**Issue by JohnHart** [maqetta/maqetta#7] opened 2011-04-20 19:29 UTC
The following steps describe the process I am taking in Maqetta: 
1.  Create new HTML file 
2.  Drop a DIV on the workspace (for this process I will call this DIV 
   1) 
3.  Drop a Dojo Edge-to-Edge list in the DIV 
4.  Drop a new DIV on the workspace (for this process I will call this 
   DIV 2) 
5.  Drop a Dojo button in the DIV 
6.  Create a new state called "Off" 
7.  For the Off state, click to close the eyes on DIV 1 and the Edge- 
   to-Edge control, and the list items. 
8.  Create a click event for the button - select the Off state 

View in the browser.  Everything looks good, but when I click on the 
button, nothing occurs. 

I appreciate whatever help you can provide. 

Thank you, 
John

**Comment by JonFerraiolo** [comment] 2011-04-22 19:19
One quick note. The Edge-to-Edge-List widget is in the dojox.mobile group. In the Preview 1 release, those widgets are not fully implemented, and in fact were added to the code in the 2 weeks before the Preview 1 release was posted. In fact, widgets themselves aren't yet ready for production use and aren't scheduled for completion until Dojo 1.7 (June?). We will be completing the implementation of the dojox.mobile group in the next couple of months, perhaps shipping an update to Maqetta soon on the heels of Dojo 1.7 with more complete support for mobile widgets.

**Comment by JonFerraiolo** [comment] 2012-04-15 22:37
@JohnHart  I couldn't reproduce this bug with our latest release (Preview5), so I'm closing this. Maybe we fixed bugs in the meantime. If you have the inclination, could you please try to reproduce with the latest release running on Maqetta.org? If you can reproduce, could you please copy/paste the source code for the file that doesn't work into this bug report? To get the source code, click on the "View Source" icon on the toolbar, and then use browser copy/paste to grab the text. Thanks.

**Closed as completed by JonFerraiolo** 2012-04-15 22:37 UTC
Labels: Visual Editor, Widget Libraries, Bug, Priority High
