### ISSUE TITLE
Save-as-widget fails with shapes

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3729] opened 2013-02-04 14:07 UTC
Create a Rounded Rectangle.  Put a Dijit Button inside.  Select the Rounded Rectangle and choose "Save As Widget".

Find the new widget in the palette and drag it to the canvas.  The compound widget will appear in the design view, but in source, only the rectangle tag will be added to the document.  Close and re-open the document and you will only see a rectangle where your new compound widget was added, and nothing inside.

**Comment by jhpedemonte** [comment] 2013-02-04 14:25
I could be wrong, but I think Brad only really got this working with Dijit widgets in the first pass.

**Comment by JonFerraiolo** [comment] 2013-02-04 16:54
Also fails if you have a ContentPane with a Button inside and go through same steps.

The workaround is to select the RoundedRect (or ContentPane), issue a "surround with DIV" command (which will select the DIV), and then do a Save As Widget on the DIV (and its descendants).

**Comment by JonFerraiolo** [comment] 2013-04-12 23:01
Save-as-widget sort of works with shapes. When I tried adding one of each shape on canvas, then surround with DIV, then Save-as-Widget, I got an undefined exception on first try, but it worked on second try. Note that exception causes widget palette to disappear because the custom widget is incompletely formulated.

-> Prio-High to investigate the exception.

**Comment by JonFerraiolo** [comment] 2013-04-12 23:29
Closing. There is some intermittent flakiness, at least one time when I tried it, but now I can't reproduce, and shapes are indeed working inside of custom widgets these days.

**Closed as completed by JonFerraiolo** 2013-04-12 23:29 UTC
Labels: Bug, Priority Med, Severity 2, SaveAsWidget
