### ISSUE TITLE
Same file name in different folders causes problems if both are open

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#671] opened 2011-07-07 14:32 UTC
I can't imagine this happening often for any user, but it's something to look into eventually...
- new HTML file -- go with the default name of "file1.html"
- add a button to the canvas
- save and close it
- new folder -- go with the default name of "folder1"
- highlight the new folder name in the Files palette
- select new HTML file so that the new file will be in the folder you created -- go with the default name of "file1.html"
- add a button to the canvas
- save it but do not close the file
- open the other file1.html so that they're both open
- double-click the button in folder1/file1.html to edit it
  This is where it breaks and won't let me edit the button. It gives me the console errors:

Uncaught TypeError: Cannot read property '0' of undefined
TypeError: Cannot set property 'checked' of null

Testing in Windows/Chrome

**Comment by JonFerraiolo** [comment] 2011-07-07 14:35
Assigned to Brad. Maybe our unique naming algorithms don't take into account the scenario where file1.html might be in two separate folders at same time???

**Comment by childsb** [comment] 2011-09-07 22:24
Can't reproduce-- probably fixed along side another issue/bug.

**Closed as completed by childsb** 2011-09-07 22:24 UTC
Labels: Files View, Priority Med
