### ISSUE TITLE
Login screen exception doing document.getElementById('googleLoginLink')

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3131] opened 2012-08-27 23:30 UTC
@jhpedemonte 

With Win/Firefox, running maqetta-test, I'm getting an exceptoin at LoginWindow.js:460:

```
document.getElementById("googleLoginLink").href = createOpenIdLink("https://www.google.com/accounts/o8/id");
```

Could it be that we are missing a few DIVs? We really shouldn't be shipping with these exceptions.

I might be able to look into this, too.

**Comment by jhpedemonte** [comment] 2012-08-27 23:54
Dupe of #3102.

**Closed as completed by jhpedemonte** 2012-08-27 23:54 UTC
Labels: Other, Priority Med, Severity 3
