### ISSUE TITLE
YUI Calendar widget does not work

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1229] opened 2011-11-14 22:56 UTC
Create new file drag and drop YUI calendar widget

**Comment by peller** [comment] 2011-11-14 23:03
dup of #918?

**Comment by jhpedemonte** [comment] 2011-11-15 02:23
From Jon in #918:

> Reopening. (@childsb)
> 
> Running from both daily builds and launching from Eclipse, jQuery and YUI widgets aren't working. HTTP requests for jQuery libraries is failing with 404:
> 
> ```
> Problem accessing /maqetta/user/maqettaUser/ws/workspace/project1/lib/jquery-ui/jquery-1.4.4.min.js. Reason:
> NOT_FOUND
> ```
> 
> One hint: I don't see jQuery and YUI folders in my workspace within ./lib

**Comment by jhpedemonte** [comment] 2011-12-16 14:54
Dupe of #1328.

**Closed as completed by jhpedemonte** 2011-12-16 14:54 UTC
Labels: Bug, Priority Med
