### ISSUE TITLE
[AMD Regression] Error in console after opening app.css

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1688] opened 2012-02-03 20:21 UTC
On built maqetta-

1) Open sample1.html
2) open app.css

notice error in console (or if you have break on error the debugger will stop):
s is null
http://lab9.austin.ibm.com:50010/maqetta/app/dojo/dojo.js?6228de405d8e0b1581446c0428ea2818a31b22cc
Line 3880

**Comment by JonFerraiolo** [comment] 2012-02-03 20:52
Assigned to @peller just so it doesn't fall through cracks.

I just tried using local install version of built (http://localhost:50000/maqetta) on Mac/Chrome and couldn't reproduce.

**Comment by peller** [comment] 2012-02-04 03:36
works for me on lab9.  @childsb, if you still see this, please paste in the stack

**Closed as completed by peller** 2012-02-04 03:36 UTC
Labels: Build, Bug, Priority High
