### ISSUE TITLE
Characters dropped when typing in source view

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1554] opened 2012-01-12 01:15 UTC
1. New HTML Page, iPhone.
2. Drop a dojox.mobile.View into silhouette, then a Heading into the view and a ToolBarButton onto the Heading.
3. Split view to show source.
4. Try typing in ToolBarButton's **label**.

I found that some characters don't register.  When this happens, I see the page content flicker as it's being recreated.

I'm assuming that because of everything involved in recreating the page, this is blocking some keystroke events.

@waynevicknair @JonFerraiolo @peller

**Comment by JonFerraiolo** [comment] 2012-01-12 02:52
<soapbox>This is one of the reasons why we don't want to always regenerate the entire visual document with each and every keystroke in the source editor. If we knew that the keystrokes were within the bounds of the ToolBarButton, then we might be able to regenerate just the ToolBarButton.</soapbox>

But probably more pertinent to this problem is that we have too much source-begets-design-begets-source-begets-design-and-luckily-we-manage-to-get-out-of-an-infinite-loop.

**Comment by peller** [comment] 2012-01-12 03:39
Maybe.  Or we might just be losing focus for a time, or have some other coding practices that are throwing the browser for a 'loop' worth fixing.

Yes, we could arguably optimize some simple changes as deltas (at the expense of adding complexity to the code) but if indeed the page refresh is causing a loss of keystrokes, wouldn't we need to devise a system to handle **all** changes incrementally?

**Comment by jhpedemonte** [comment] 2012-01-12 03:44
Also consider that we've mostly been testing fairly simple pages.  Users may start constructing pages with many more widgets, at which point performance deficiencies will be very evident.

> wouldn't we need to devise a system to handle all changes incrementally?

Yes.  Sure, it'll add complexity, but it'll improve performance.

**Comment by peller** [comment] 2012-01-12 04:39
premature optimization is the root of all evil

**Comment by peller** [comment] 2012-01-12 04:41
Keep in mind we're only talking about typing in split view, right?  Perhaps we just need to be more clever about when and how often we refresh the visual display.  We shouldn't be doing it that often.

**Comment by jhpedemonte** [comment] 2012-03-15 05:07
-> M6

**Comment by JonFerraiolo** [comment] 2012-05-12 22:34
-> @peller M6 Prio-Med - maybe this is fixed now?

**Comment by peller** [comment] 2012-05-14 04:17
Last I checked, we were doing better, though FF was still very slow.  It's impossible to test now, given regressions in selection which throw off the cursor as you type.

**Comment by peller** [comment] 2012-05-16 20:13
@JonFerraiolo: Moving to M7 Prio-Med to reassess after selection regressions are fixed

**Comment by peller** [comment] 2012-08-01 17:32
now that the selection issues are fixed, I feel I can type freely.  The behavior is to defer changes until the user stops typing.  If the user stops then starts typing while those changes are getting propagated, there will be a delay, and the key strokes do seem to be getting buffered.

**Closed as completed by peller** 2012-08-01 17:32 UTC
Labels: Source Editors, Priority Med, Severity 2
