### ISSUE TITLE
Browser refresh: iPhone CSS files not active in current editor window

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#999] opened 2011-09-12 22:52 UTC
@peller, @billreed63, @jhpedemonte

With latest checkins:
- New HTML File
- Switch to iPhone silhouette
- Add a View and a RoundRectList
- Browser refresh

Result => iPhone CSS rules aren't showing in document. Just see plain HTML list elements. If you save, close, reopen, the iPhone look&feel now shows. No problem if you choose an Android silhouette instead of the iPhone silhouette.

**Comment by JonFerraiolo** [comment] 2011-09-12 23:07
The iphone css file is there, just not "taking". Javier did some magic about a week ago to address this problem. Anyone remember what he did?

**Comment by peller** [comment] 2011-09-13 02:56
I'm still unable to reproduce this in a local copy, but I've got a theory that the regression is due to moving the call to setMobileTheme in 6672eb0b2596ec8b80beeedc92b498fb49e15af4 to after the parse, after dojox.mobile has had a chance to initialize its deviceTheme and insert the iphone.css stylesheet, thus putting us back in the condition where we remove and replace the stylesheet while it's being processed (the problem from #899)

**Comment by peller** [comment] 2011-09-13 02:58
@billreed63 we talked about this, and you confirmed that changing to dj.addOnLoad wasn't enough, that it had to come after the dojo.parse, and that putting it immediately before failed on chrome, right?

**Comment by peller** [comment] 2011-09-13 03:04
@billreed63 other question to revisit is, whether the 'force=true' is necessary when first calling setMobileTheme.  This is where oldDevice = device = "iphone"

**Comment by jhpedemonte** [comment] 2011-09-13 12:56
I mentioned this in #980: the `device === oldDevice` check in `setMobileTheme` can get us in trouble.  That's why I removed it in the pull request attached to that issue.  See my last comment there.

If you need to set `force = true`, then you might as well remove the check, since the only other call to `setMobileTheme` already has `force` set as well.

**Comment by jhpedemonte** [comment] 2011-09-13 12:56
I'm pretty sure I'd also fixed this issue with my pull request, but not 100% sure.

**Comment by billreed63** [comment] 2011-09-13 13:20
We already have the force on the load at start up, it is a timing issue. The setDeviceAndTheme is being called to soon. If I add a setTimeout , 200 the issue is resolved. not the best approach but one that will get us past m3.

**Comment by JonFerraiolo** [comment] 2011-09-13 13:57
So far so good with my testing. Before the above fix, on my system with Mac/Chrome, the stylesheet loading didn't work about 75% of the time with a browser refresh when I had an editing tab open with a silhouette. With the above fix, I haven't seen a problem yet.

**Comment by JonFerraiolo** [comment] 2011-09-13 14:22
I did see one problem running the latest build on the staging server. I had two HTML editing tabs open, the first with iPhone silhouette, the second with Android silhouette, with second tab active, and I hit browser refresh. After refresh, Android page was fine, but when I click on tab for iPhone page, the CSS styling wasn't there. But it has only happened that one time. No problems with subsequent attempts.

**Comment by jhpedemonte** [comment] 2011-09-13 14:59
I haven't updated since Sunday evening, so I don't have any of Adam's or Bill's changes.  I pulled in my patch from https://github.com/maqetta/maqetta/pull/990 and tested this issue.  Works just fine.

I don't like using `setTimeout` -- it's arbitrary and fragile.

The only thing that may not be covered by my patch is the FF issue, for which Bill made the change from `unload` to `dj.addOnLoad`.  But that doesn't seem to have worked well, since now we're adding in a `setTimeout`.

**Comment by JonFerraiolo** [comment] 2011-09-13 16:17
So far, I'm seeing things working either completely or mostly on Mac/Chrome launched from Eclipse, Mac/Chrome on staging server, Win/Chrome on staging server, and Win/Chrome using a downloadable build ZIP.

**Comment by JonFerraiolo** [comment] 2011-09-13 17:12
Moving to M4 where we hope to address this by fundamental cleanups

**Comment by peller** [comment] 2011-09-27 04:32
addressed by cleanup in #1011

**Closed as completed by peller** 2011-09-27 04:32 UTC
Labels: Priority Med, Mobile
