### ISSUE TITLE
M1->M2 migration issues with DataGrid and Tree widgets 

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#781] opened 2011-07-25 16:51 UTC
As part of my migration testing for M1=>M2, I created files with DataGrid and Tree widgets in M1 and tried to load in M2. On both Mac/Safari and Win/FF, I'm getting this error when trying to open the M1-created HTML file in M2:

```
dojo.js:15[ Exception: TypeError: Result of expression 'Object' [undefined] is not an object. ]
Error parsing in _ContentSetter#Setter_div_8_8 [ Exception: TypeError: Result of expression 'Object' [undefined] is not an object. 
```

We should at least understand what's going wrong here before shipping M2.

**Comment by jhpedemonte** [comment] 2011-07-25 16:54
Adding @waynevicknair, so he can keep track of any migration issues.

Can you compare the **M1** file against one you created with **M2** and see if there are any differences?

**Comment by JonFerraiolo** [comment] 2011-07-25 17:47
Comparing the two files isn't as easy as it sounds. I'm working on it.

**Comment by JonFerraiolo** [comment] 2011-07-25 17:56
Here is the source file I created using Preview 1.0.1:

```
<!DOCTYPE html>
<html>
<head>
<title>Untitled</title>
<style type="text/css">
@import "themes/claro/claro.css";
@import "app.css";
@import "./lib/dojo/dojo/resources/dojo.css";
@import "./lib/dojo/dojox/grid/resources/Grid.css";
@import "./lib/dojo/dojox/grid/resources/claroGrid.css";
</style>
<script type="text/javascript" src="./lib/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
<script type="text/javascript">
dojo.require('dojo.data.ItemFileReadStore');
dojo.require('dojox.grid.DataGrid');
dojo.require('dijit.Tree');
dojo.require('dijit.Calendar');</script>
<script src="maqetta/States.js"></script>
<script src="maqetta/maqetta.js"></script>
</head>
<body class="claro lotusui" data-davinci-ws="collapse" id="myapp" dvFlowLayout="true">
 <iframe style="width: 300px; height: 300px;" src="Sample1.html"></iframe>
 <img src="SampleBanner.jpg"></img>
<span dojoType="dojo.data.ItemFileReadStore" id="ItemFileReadStore_1" jsId="ItemFileReadStore_1" data="{&quot;identifier&quot;:&quot;uniqe_id&quot;,&quot;items&quot;:[{&quot;uniqe_id&quot;:1,&quot;id&quot;:&quot;1&quot;,&quot;_label&quot;:&quot; Label 1&quot;},{&quot;uniqe_id&quot;:2,&quot;id&quot;:&quot;2&quot;,&quot;_label&quot;:&quot; Label 2&quot;}]}"></span><span dojoType="dojox.grid.DataGrid" structure="[{&quot;cellType&quot;:&quot;dojox.grid.cells.Cell&quot;,&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot;ID&quot;,&quot;field&quot;:&quot;id&quot;},{&quot;cellType&quot;:&quot;dojox.grid.cells.Cell&quot;,&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot; Label&quot;,&quot;field&quot;:&quot;_label&quot;}]" autoWidth="false" autoHeight="false" singleClickEdit="false" columnReordering="false" selectable="false" delayScroll="false" style="width: 294px; height: 66px;" store="ItemFileReadStore_1"></span><span dojoType="dojo.data.ItemFileReadStore" id="ItemFileReadStore_2" jsId="ItemFileReadStore_2" data="{&quot;identifier&quot;:&quot;id&quot;,&quot;label&quot;:&quot;label&quot;,&quot;items&quot;:[{&quot;label&quot;:[&quot;1&quot;],&quot;id&quot;:[110732931644],&quot;children&quot;:[{&quot;label&quot;:[&quot;1.1&quot;],&quot;id&quot;:[457104792818]},{&quot;label&quot;:[&quot;1.2&quot;],&quot;id&quot;:[307154759765]}]},{&quot;label&quot;:[&quot;2&quot;],&quot;id&quot;:[70492998231],&quot;children&quot;:[{&quot;label&quot;:[&quot;2.1&quot;],&quot;id&quot;:[761214051628]},{&quot;label&quot;:[&quot;2.2&quot;],&quot;id&quot;:[840745277470]},{&quot;label&quot;:[&quot;2.3&quot;],&quot;id&quot;:[895017368020]}]}]}"></span><span dojoType="dijit.tree.ForestStoreModel" id="ForestStoreModel_1" rootLabel="Root" jsId="ForestStoreModel_1" store="ItemFileReadStore_2"></span><span dojoType="dijit.Tree" style="width: 244px; height: 163px; overflow: auto;" showRoot="false" autoExpand="true" model="ForestStoreModel_1"></span>
<input dojoType="dijit.Calendar" datePackage="dojo.date" value="2011-07-25"></input>
</body>
</html>
```

When I put that file into my M2 users/ folder and try to open it, the DataGrid doesn't show and Calendar is messed up.

**Comment by jhpedemonte** [comment] 2011-07-25 18:01
How does that file compare to one you've created using M2?

**Comment by billreed63** [comment] 2011-07-25 18:44
The DataGrid Structure contains:

```
structure="[{&quot;cellType&quot;:&quot;dojox.grid.cells.Cell&quot;,&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot;ID&quot;,&quot;field&quot;:&quot;id&quot;},{&quot;cellType&quot;:&quot;dojox.grid.cells.Cell&quot;,&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot; Label&quot;,&quot;field&quot;:&quot;_label&quot;}]" 

```

The cellType is causing the datagrid not to load, an exception must be eaten by something in dojo

If we remove the cellType from the structure:

```
<span dojoType="dojox.grid.DataGrid" structure="[{&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot;ID&quot;,&quot;field&quot;:&quot;id&quot;},{&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot; Label&quot;,&quot;field&quot;:&quot;_label&quot;}]" autoWidth="false" autoHeight="false" singleClickEdit="false" columnReordering="false" selectable="false" delayScroll="false" style="width: 294px; height: 66px;" store="ItemFileReadStore_1"></span>

```

The page will load.

**Comment by jhpedemonte** [comment] 2011-07-25 19:08
(Bill, not sure if you meant to close this issue.  -> Reopened)

One thing to consider with **migration**: we don't have to handle all cases.  It is perfectly valid to say that this particular issue won't be covered with migration.  User will have old (un-migrated) source and can reconstruct using **M2** based on that source.

**Comment by JonFerraiolo** [comment] 2011-07-25 19:38
Bill, you are saying that DataGrid widgets will migrate if we remove cellType from the structure attribute? Could this be accomplished by a simple addition to our migration script via sed?

**Comment by billreed63** [comment] 2011-07-25 20:52
This seems to be dojo 1.7 regression,  the &quot; around the dojox.grid.cells.Cell in the structure cause dojo to throw

cell_type is not a constructor

line 131 of dojox/grid/_layout

```
var cell_type = inDef.type || inDef.cellType || this._defaultCellProps.type || this._defaultCellProps.cellType || dojox.grid.cells.Cell;
props.unitWidth = getCellWidth(inDef);
// at this point cell_type is a string ""dojox.grid.cells.Cell" instead of a function
return new cell_type(dojo.mixin({}, this._defaultCellProps, inDef, props)); 

```

**Comment by billreed63** [comment] 2011-07-25 21:59
IWe can fix the migration issue by adding the following patch to 

dojox/grid/_layout.js  line 131

```
        if (typeof cell_type === 'string'){
            return (eval(cell_type))(dojo.mixin({}, this._defaultCellProps, inDef, props))

        }
```

After the patch the code is:

```
    var cell_type = inDef.type || inDef.cellType || this._defaultCellProps.type || this._defaultCellProps.cellType || dojox.grid.cells.Cell;

        props.unitWidth = getCellWidth(inDef);
               // Patch for M1 > M2
        if (typeof cell_type === 'string'){
            return (eval(cell_type))(dojo.mixin({}, this._defaultCellProps, inDef, props))
        }
              // end patch
        return new cell_type(dojo.mixin({}, this._defaultCellProps, inDef, props));
```

@peller  should we talk to Bill about this ?

**Comment by billreed63** [comment] 2011-07-25 22:03
Here is a test case for Dojo to use to recreate:

``` html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" 
    "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <title>Test dojox.grid.Grid Backwards Compatibility</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <style type="text/css">
        @import "../_grid/Grid.css";
        @import "../_grid/tundraGrid.css";
        @import "../resources/Grid.css";
        @import "../resources/tundraGrid.css";
        @import "../../../dojo/resources/dojo.css";
        @import "../../../dijit/themes/tundra/tundra.css";
        body {
            font-size: 0.9em;
            font-family: Geneva, Arial, Helvetica, sans-serif;
        }
        .heading {
            font-weight: bold;
            padding-bottom: 0.25em;
        }

        #grid,#grid2 {
            border: 1px solid #333;
            width: 35em;
            height: 30em;
        }
    </style>
    <script type="text/javascript" src="../../../dojo/dojo.js" 
        djConfig="isDebug:false, parseOnLoad: true"></script>
    <script type="text/javascript">
        dojo.require("dijit.dijit");
        dojo.require("dojox.grid.DataGrid");
        dojo.require("dojo.data.ItemFileWriteStore");
        dojo.require("dojo.parser");
    </script>
</head>
<body>
<span dojoType="dojo.data.ItemFileReadStore" id="ItemFileReadStore_1" jsId="ItemFileReadStore_1" data="{&quot;identifier&quot;:&quot;uniqe_id&quot;,&quot;items&quot;:[{&quot;uniqe_id&quot;:1,&quot;id&quot;:&quot;1&quot;,&quot;_label&quot;:&quot; Label 1&quot;},{&quot;uniqe_id&quot;:2,&quot;id&quot;:&quot;2&quot;,&quot;_label&quot;:&quot; Label 2&quot;}]}"></span>
<span dojoType="dojox.grid.DataGrid" structure="[{&quot;cellType&quot;:&quot;dojox.grid.cells.Cell&quot;,&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot;ID&quot;,&quot;field&quot;:&quot;id&quot;},{&quot;cellType&quot;:dojox.grid.cells.Cell,&quot;width&quot;:&quot;auto&quot;,&quot;name&quot;:&quot; Label&quot;,&quot;field&quot;:&quot;_label&quot;}]" autoWidth="false" autoHeight="false" singleClickEdit="false" columnReordering="false" selectable="false" delayScroll="false" style="width: 300px; height: 300px;" store="ItemFileReadStore_1"></span>
</body>

</html>

```

**Comment by waynevicknair** [comment] 2011-07-25 23:03
one difference for sure will be the lack of a "lotusui" class on the 'body'
tag. i'll do some diffing tomorrow.

**Comment by JonFerraiolo** [comment] 2011-07-25 23:54
The "lotusui" class on the body is unlikely to be the source of the problem. Looks like BillR found a problem with latest Dojo code.

**Comment by peller** [comment] 2011-07-26 14:24
Evan applied a patch to 1.6 and 1.7: http://bugs.dojotoolkit.org/changeset/25907

**Closed as completed** 2011-07-26 15:27 UTC
Labels: Widget Libraries, Priority High

**Comment by billreed63** [comment] 2011-07-26 16:15
July 2011
