### ISSUE TITLE
VE 3 test case, step 7 -- checkbox goes into SPAN despite choosing DIV

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1531] opened 2012-01-11 02:18 UTC
In VE 3 test case, step 7, the checkbox seems to go into the span (as indicated by the outline view) despite having hit #2 to select the DIV as the parent.

Environment:
Chrome, local instal
Version: Preview 4
Date: Jan 10, 2012 2:58:23 PM
Build: 3c236b1c2ec48a5...

**Comment by JonFerraiolo** [comment] 2012-01-11 02:44
Likely a dupe of #1525

**Comment by JonFerraiolo** [comment] 2012-03-09 00:50
Working now. Closing.

**Closed as completed by JonFerraiolo** 2012-03-09 00:50 UTC
Labels: Visual Editor, Bug, Priority Med
