### ISSUE TITLE
Tooltip not working properly

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#772] opened 2011-07-22 15:21 UTC
- new HTML file
- drag button onto canvas
- drag tooltip onto button

The tooltip doesn't appear beside the button. 
I tired it on maqetta.org and it worked fine there, so I don't believe I'm doing anything wrong.

Tested on Win/FF
lab14 build:
Version: Preview 2
Date: Jul 22, 2011 7:02:13 AM
Build: d04db9aaeb52c27...

**Comment by jhpedemonte** [comment] 2011-07-22 16:35
Here's the source for the button and tooltip:

``` html
 <input type="button" dojoType="dijit.form.Button" disabled="false" intermediateChanges="false" label="Button" iconClass="dijitNoIcon"></input>
 <span dojoType="dijit.Tooltip" id="dijit_Tooltip_128" connectId="myapp">Foobar!!!!!!</span></body>
```

Notice that the `connectId` attribute for the tooltip is set to **"myapp"**, which is the `id` for `<body>`.

I added an `id` to the button `<input>` and changed `connectId` to use that instead.  Afterwards, it worked in Preview.

**Comment by jhpedemonte** [comment] 2011-07-22 16:35
Since this is a regression, Adam, please try to take a look today.  Hopefully, the fix is easy and straight forward.

**Comment by jhpedemonte** [comment] 2011-07-22 16:41
Here's what the source looked like with Preview 1:

``` html
 <input type="button" dojoType="dijit.form.Button" id="auto_dijit.form.Button_0" disabled="false" intermediateChanges="false" label="Button"></input>
<span dojoType="dijit.Tooltip" connectId="auto_dijit.form.Button_0">Foobar!!!!!!</span></body>
```

The `connectId` was properly set to an auto-generated `id` of button.

---

I notice that the current code adds a State.  However, even after my changes to the source (my 1st comment above), changing to the tooltip state did not show the tooltip in the VE.

@JonFerraiolo

**Comment by JonFerraiolo** [comment] 2011-07-22 21:28
I give low priority for M2 to anything under Untested, even if there is a regression versus Preview 1. The high-order bit is that Tooltip wasn't ready to use with Preview 1 and it's still not ready to use with Preview 2. Not that important to a user between just a little broken versus even more broken, it's still broken.

**Comment by jhpedemonte** [comment] 2011-07-22 21:31
Agreed.  But hopefully Adam can find out what's going on with `connectId` not getting set properly.  But if it's too involved, I'm OK with pushing to M3.

**Comment by peller** [comment] 2011-07-25 02:54
@jhpedemonte

At least in the cases I tried (button, textbox), this line in CreateTool.onMouseUp() from ae00b28c  changes the target from the actual widget to its parent -- usually BODY or a ContentPane.

``` js
            // XXX Have to do this call here, rather than in the more favorable
            //  create() or _create() since different "subclasses" of CreateTool
            //  either override create() or _create().  It is very inconsistent.
            target = this._getAllowedTargetWidget(target);
```

Then, when the Tooltip's create helper expects to have event.target to assign the contentId, it binds the tooltip to the parent instead of the actual widget.

**Comment by jhpedemonte** [comment] 2011-07-25 16:14
Ah, I see.  This is going to take some thinking.

That code is for the case where a widget is dropped on a target with the intent that the dropped widget will be a child of the target.

However, in the case of Tooltip (and other widgets), the user is looking to create an **association between sibling widgets** rather than a **parent-child relationship**.

When Tooltip is dropped on a Button, the latter allows no children, so the code goes up a bit to `<body>` and uses that as the parent.

A quick fix would be to differentiate between **target** and **parent** -- target would not change, but parent would be the result of `this._getAllowedTargetWidget()`.  We pass both to `CreateTool.create()`; most widgets will only care about parent, but widgets like Tooltip will want to make use of the original target.

Going forward, we'd need to abstract this type of relationship to the metadata level, if possible.

What do you guys think?

**Comment by JonFerraiolo** [comment] 2011-07-25 17:49
Your analysis and proposed solutions sound good to me.

**Comment by peller** [comment] 2011-07-26 04:01
yes, sounds good.  my main concern was that the definition of 'target' seems to have changed since preview 1.  I don't know of any code other than Tooltip (helper) which uses it, but I haven't looked very hard.

**Comment by jhpedemonte** [comment] 2011-07-26 04:10
Pushing to **M3** and assigning to myself to redo code according to the [previous comment](https://github.com/maqetta/maqetta/issues/772#issuecomment-1646912).

**Closed as completed** 2011-12-08 05:02 UTC
Labels: Other, Bug, Priority Med, Regression
