### ISSUE TITLE
Can not refresh mobile page preview

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1840] opened 2012-03-01 21:42 UTC
1) Create a html iphone
2) DnD View and header
3) Preview
4) Click the refresh in the preview browsers

Console:

```
735GET http://localhost:8081/maqetta/app/davinci/nls/webContent.js 413 (FULL head)
```

**Comment by JonFerraiolo** [comment] 2012-03-01 21:51
This one is probably a dupe of another bug that was sent to @peller either yesterday or today. @peller:  close this if you think this is a dupe.

**Comment by billreed63** [comment] 2012-03-01 21:52
console log of document.cookie

"DataGridFileSelectionDialog.id1SaveStateCookie=.; DataGridFileSelectionDialog.DataGridFileSelectionDialogSaveStateCookie=.; davinci_ui_Panel_5.id1SaveStateCookie=.; davinci_ui_Panel_6.id1SaveStateCookie=.; davinci_ui_Panel_7.id1SaveStateCookie=.; reviewResourceTreeSaveStateCookie=.review%2Fsnapshot; davinci_ui_Panel_3.id1SaveStateCookie=.%2C.%2Fsample_data%2C.%2Fproject1; davinci_ui_Panel_4.id1SaveStateCookie=.%2C.%2Fproject1%2C.%2Fproject1%2Fsample_data; davinci_ui_Panel_2.id1SaveStateCookie=.%2C.%2Fsample_data%2C.%2FDefault%20Project%2C.%2Fproject1%2C.%2Fproject1%2Fsample_data; SaveStateCookie=myapp%2Cspan_9%2Cspan_0%2C.%2Fapp.css%2Cdiv_0%2Cdiv_6%2Cspan_2%2Cdiv_7%2Cdiv_8%2Cdiv_5%2Cinput_0%2Cinput_1%2C.%2Fthemes%2Fclaro%2FProgressBar.css%2Ctable_0%2Ctbody_0%2Ctr_0%2Ctd_0%2CStackContainer_1%2Cspan_1%2Cdiv_2%2Cdiv_3%2Cdiv_1%2C.%2Fproject1%2Ffile1.css%2C.%2Fproject1%2Ffile1.js%2C.%2Fproject1%2Fthemes%2Fclaro%2FCalendar.css%2C.%2Fproject1%2Fapp.css%2CTabs_0%2CTabContainer_0%2CContentPane_0%2C.%2Fproject1%2Fthemes%2Fcustom_android%2Fandroid.css%2Cdijit_Dialog_3%2CDropDownSelect_0%2Ctbody_1%2Ctr_2%2Ctd_4%2Ctd_5; fileDialogFolderTreeSaveStateCookie=.%2C.%2FDefault%20Project%2C.%2FProject1%2C.%2Fproject1%2C.%2Fproject1%2Ftestfolder%2C.%2Fproject1%2Fthemes%2C.%2Fproject1%2Fthemes%2Fclaro; davinci_ui_Panel_0.id1SaveStateCookie=.%2C.%2Fsample_data%2C.%2FDefault%20Project%2C.%2FDefault%20Project%2Fsample_data%2C.%2Fproject1%2C.%2Fproject1%2Fsample_data%2C.%2Fproject1%2F.%2Fproject1%2Fsample_data; davinci_ui_Panel_1.id1SaveStateCookie=.%2C.%2Fsample_data%2C.%2FDefault%20Project%2C.%2Fproject1%2C.%2Fproject1%2Fsample_data%2C.%2Fproject1%2F.%2Fproject1%2Fsample_data; prefTreeSaveStateCookie=0%2C2%2C4%2Cundefined%2C%2C%2F0%2C%2F2%2C%2F4; dataGridInputFileSelectionTreeSaveStateCookie=.%2Fproject1%2C.%2Fproject1%2F.%2Fproject1%2Fsample_data; DAVINCI.USER=user6; reviewWizardSourceTreeSaveStateCookie=.%2C.%2F.%2Fproject1; resourceTreeSaveStateCookie=.%2C.%2Fthemes%2C.%2FDefault%20Project%2C.%2FProject1%2C.%2Fproject1%2C.%2Fproject1%2Ffolder1%2C.%2Fproject1%2Ftestfolder%2C.%2Fproject1%2Fnnnn%2C.%2Fproject1%2Flib%2Fdojo%2C.%2Fproject1%2Flib%2Fdojo%2Fdojox%2C.%2Fproject1%2Flib%2Fdojo%2Fdojox%2Fmobile%2C.%2Fproject1%2Flib%2Fdojo%2Fdojox%2Fmobile%2Fthemes%2C.%2Fproject1%2Fthemes%2Fcustom_android%2C.%2Fproject1%2Fthemes%2C.%2Fproject1%2Flib%2Fdojo%2Fdojox%2Fmobile%2Fthemes%2Fandroid%2C.%2Fproject1%2Fsample_data%2C.%2Fproject1%2F.%2Fproject1%2Fthemes%2C.%2Fproject1%2F.%2Fproject1%2Fthemes%2F.%2Fproject1%2Fthemes%2Fmyandroid%2C.%2Fproject1%2F.%2Fproject1%2Ffolder1%2C.%2Fproject1%2F.%2Fproject1%2Flib%2C.%2Fproject1%2F.%2Fproject1%2Fthemes%2F.%2Fproject1%2Fthemes%2Fa1%2C.%2Fproject1%2F.%2Fproject1%2Fproject1%2C.%2Fproject1%2F.%2Fproject1%2Fsample_data%2F.%2Fproject1%2Fsample_data%2Fimages%2C.%2Fproject1%2F.%2Fproject1%2Fthemes%2F.%2Fproject1%2Fthemes%2Fclaro1%2C.%2Fproject1%2F.%2Fproject1%2Fthemes%2F.%2Fproject1%2Fthemes%2Fc1%2C.%2Feproject%2C.%2Feproject%2F.%2Feproject%2FWebContent%2C.%2Fproject1%2F.%2Fproject1%2Fmaqetta%2C.%2Fproject1%2F.%2Fproject1%2Fthemes%2F.%2Fproject1%2Fthemes%2Fcustom2%2C.%2Fproject1%2F.%2Fproject1%2Fthemes%2F.%2Fproject1%2Fthemes%2Fclaro2%2C.%2Fproject1%2F.%2Fproject1%2Fimages%2C.%2Fproject1%2F.%2Fproject1%2Fsample_data; reviewCommentExplorerViewTreeSaveStateCookie=.review%2Fsnapshot%2C.review%2Fsnapshot%2F.review%2Fsnapshot%2F20120301152815; undefined=myapp; preview=1; JSESSIONID=my9d6ygpldyi11hok13e767qk"

**Comment by peller** [comment] 2012-03-01 21:59
see #307, #1666, #1809

**Comment by peller** [comment] 2012-03-01 22:02
I need to take the output above and consider it for #1170.  @aerwin I thought we had successfully killed davinci.ui.Panel instances in #1638?

**Closed as completed** 2012-03-02 16:43 UTC
Labels: Bug, Priority High, Mobile
