### ISSUE TITLE
source editor doesn't respond to all keystrokes

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#656] opened 2011-07-05 22:05 UTC
1) create new file in source editor
2) start typing

<div style="margin-top: 5px;">
    <input dojoType="dijit.form.TextBox"
        type="dijit.form.TextBox"></input>
    <input dojoType="dijit.form.Button"
        type="dijit.form.Button"
        label="Button"></input>
</div>

3) i can type with 100% accuracy but the source editor drops about 50% of the characters unless i pause about .5seconds between each keystroke

@jhpedemonte

**Comment by jhpedemonte** [comment] 2011-07-06 02:39
Whoa, I totally remember running in to this previously (months back).  Maybe Phil fixed it at that point?  I wonder what regressed.

@JonFerraiolo

**Comment by jhpedemonte** [comment] 2011-07-07 04:58
I cannot reproduce this when running from source (latest as of July 6 11pm CDT) -- typing keeps up just fine for me.

But with a day-old build, I do see a bit of a lag, but no dropped characters.

**Comment by JonFerraiolo** [comment] 2011-07-07 15:46
I am seeing this problem in a major way with today's build on Win/Chrome. I opened Sample1.html and then attempted to type in an HTML comment (e.g., ). With each keystroke, the visual editor reparses the entire document, causes flashes with each keystroke. (Well-known performance problem - won't be fixing for M2). But the really bad problem is that characters typed during the reparsing/redrawing are lost.

But I've also seen lost characters (less often, but sometimes) when in source-only view, and I'm pretty sure it happens even if editing CSS files (i.e., no visual editor in background). Is the model running when editing a CSS file?

**Comment by childsb** [comment] 2011-07-07 15:46
haven't dug into this much but if i'm running maqetta from the dev setup in eclipse, this problem is REALLY bad.  I notice that eclipse console shows requests nearly every keystroke for:

request: /user/childsb@us.ibm.com/ws/workspace/themes/claro/claro.json, logged in=true

at one point (months ago) the source editor was calling _setSource(...) on every keystroke causing the model to be rebuilt.  i wouldn't be surprised if its something similar now and the built version is fast enough (in standalone) to not notice.

**Closed as completed** 2011-07-08 21:58 UTC
Labels: Source Editors, Bug, Priority Low

**Comment by peller** [comment] 2011-07-08 22:02
we still probably shouldn't be doing things like findResource (I/O) and theme modeling on each content change, but at least now that the keystroke batching is working we should be ok

**Comment by peller** [comment] 2012-03-15 13:19
see #1554
