### ISSUE TITLE
Review comments aren't state-specific

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1960] opened 2012-03-21 00:12 UTC
Maybe this is a well-known bug, bug logging this just in case it isn't.

I created a new review session using Sample1.html and invited myself. When I opened the review session by double-clicking on Sample1.html.rev in the Reviews palette, I added review comments with annotations to both Normal and the Add Task states, but both annotations showed no matter what state I chose in the Scenes palette.

I was using lab9:50020, so my email address should have been my username.

**Comment by waynevicknair** [comment] 2012-03-21 14:46
this is a duplicate of issue #1955. closing, but will reopen if not fixed by 1955 changes.

**Closed as completed by waynevicknair** 2012-03-21 14:46 UTC
Labels: Review and Commenting, Priority High
