### ISSUE TITLE
Sticky note broken

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1279] opened 2011-11-29 19:53 UTC
1) Create new html file
2) Click on sticky note
3)Change text in sticky note
4) Click ok

Sticky note disappears text added at div at bottom of html

**Comment by JonFerraiolo** [comment] 2011-11-29 21:13
@peller

**Comment by JonFerraiolo** [comment] 2011-12-01 16:40
Reassigning to @peller because @billreed63 is all booked up on mobile theme editor issues

**Comment by peller** [comment] 2011-12-03 00:44
works for me.  perhaps related to the stylecommand regression?

**Closed as completed by peller** 2011-12-03 00:44 UTC
Labels: Priority High, Regression
