### ISSUE TITLE
Label smartinput doesn't work

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2332] opened 2012-05-18 17:51 UTC
Drag and drop a label.  Change the value using the smartinput, press ok.  Notice how the label wasn't changed.  Switch to source view, see that the changed value shows up fine there.

**Comment by JonFerraiolo** [comment] 2012-05-18 21:40
-> @billreed63 

I was able to reproduce on mac/chrome running from Eclipse when authoring in sketch mode.

**Comment by doronrosenberg** [comment] 2012-05-18 22:26
Taking since I don';t have much on my plate for m6

**Comment by doronrosenberg** [comment] 2012-05-18 22:37
OK, this applies to a lot of HTML elements, not just label.

**Comment by billreed63** [comment] 2012-05-18 22:52
From smart input we are sending the properties `textContent: "fffccc"`  to ModifyCommand
We then do a `this._oldData = widget.getData();` which returns `children: "fff"`  we then do a 

```
this._newData = {
            type: this._oldData.type,
            properties: dojo.mixin({}, this._oldData.properties, this._properties),
            children: this._children || this._oldData.children,
            scripts: dojo.mixin({}, this._oldData.scripts, this._scripts),
            states: this._oldData.states,
            context: context
        };
```

which gives us the newData we create the widget with 

```
_newData: Object
children: "fff"
context: a
properties: Object
id: "label_0"
isTempID: true
style: ""
textContent: "fffccc"
title: "hhh"
```

Because we have both the model seems to use the textContent, but the dom uses the children

**Comment by doronrosenberg** [comment] 2012-05-18 23:02
We could switch from ModifyCommand to ModifyRichTextCommand - we do that for innerHTML, and changing it to do so for textContent seems to work well.

In fact this would fix another bug I just saw - in m5, label could not support html markup, even if you checked the radio button.

**Comment by JonFerraiolo** [comment] 2012-05-18 23:56
I'm reopening and assigning to me because I'm working on (what I think) is a better fix.

The fix above sets data.children to the text string for the label, thereby making data.children = data.properties.textContent. With this fix, innerHTML in the model is set properly (I believe doubly-set, once because HTMLElement.js has special case logic for property "textContent" which stuffs its value as element content, and secondly via data.children); innerHTML on the canvas is set properly because of data.children; but one downside is that the model adds property `textContent="..."` 

I'm still working on a better fix, but it seems to me that we need to have consistency between the canvas and the model in how it deals with the "textContent" property.

But before doing that I want to research when and how SmartInput for HTML elements got broken.

**Comment by JonFerraiolo** [comment] 2012-05-19 00:25
Here is commit that broke things: eed94aa9775aed498d6ac2dd49920b7085739033 Haven't figured out exactly what went wrong yet... 

(@aerwin)

**Comment by JonFerraiolo** [comment] 2012-05-19 00:29
Ah, here's the reason. The above commit made this change:

```
-                node[name] = properties[name];
+              node.setAttribute(name, properties[name]);
```

But node['textContent'' is special (see: https://developer.mozilla.org/en/DOM/Node.textContent). `node['textContent'] = 'whatever'` is equivalent to setting the innerText of the node to 'whatever'.

**Comment by JonFerraiolo** [comment] 2012-05-19 02:03
With fa5cf614b2 all SmartInput bugs are fixed that have been reported. But @billreed63 should go over the feature (and maybe review the code) to make sure all possible options are operational.

**Closed as completed by JonFerraiolo** 2012-05-19 02:03 UTC
Labels: Bug, Priority High, Smart Input, Regression
