### ISSUE TITLE
Resizing problem with sticky notes

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1071] opened 2011-10-09 21:44 UTC
@jonferraiolo noticed that if you create a sticky note, define some text, then immediately resize the focus box, the selection box changes but the yellow sticky note widget does not resize.  If you try to resize again, it works.  Again, this appears to be a regression, possibly related to the Dojo 1.7 upgrade.  Where does the sticky widget live and where does should the resize go?

**Comment by JonFerraiolo** [comment] 2012-01-01 18:23
Couldn't reproduce just now. @billreed63 OK for you to defer to M5 and raise to Priority-Med. I recommend leaving open to see if we can come up with a reproducible set of steps.

**Comment by billreed63** [comment] 2012-01-04 21:44
I tried for a while also, but was unable to reproduce, dojo should not have and effect of this widget as it is just a "div with style" 

Moving to M5

**Comment by billreed63** [comment] 2012-02-29 17:23
reopen if someone can reprodude

**Closed as completed by billreed63** 2012-02-29 17:23 UTC
Labels: Bug, Priority Med
