### ISSUE TITLE
No password reset e-mail from "external" maqetta-orion-hosted

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3598] opened 2012-12-05 17:26 UTC
I can't login to "external" maqetta-orion-hosted build on maqetta-test. When I try to register it tells me I already have an account (after making me wait for new user email, etc. and filling out new user form). 

So, apparently I've forgotten my password.  But, when going down the forgotten password path, I never receive a reset password e-mail.

**Comment by jhpedemonte** [comment] 2012-12-05 19:05
Duplicate of #3582.

**Closed as completed by jhpedemonte** 2012-12-05 19:05 UTC
Labels: Server, Priority High, Severity 1
