### ISSUE TITLE
error in preview with states

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2899] opened 2012-08-08 17:21 UTC
1) new HTML file
2) add a calendar and button
3) add state A
4) select calendar and make it hidden in state A
5) add an event to button to switch to state A.
6) Show preview, click button and observe error:
[Break On This Error]   

dojoSniffConfig.deps = dojoSniffConfig.deps || [dataMain];

dojo.js (line 643)

event is not defined
[Break On This Error]

**Comment by JonFerraiolo** [comment] 2012-08-08 19:50
Note: I added an event parameter to the setState() method so that the AppStates.js logic could figure out the origin of the click (using event.currentTarget or event.target). This was to support the "nested state containers" features I added back in June to M7.

**Comment by peller** [comment] 2012-08-08 23:57
@childsb, did you get the call stack?  I am unable to reproduce this running from Eclipse.

**Comment by jhpedemonte** [comment] 2012-08-09 03:06
Does this error affect anything?  If so, we should move this to M7.

**Comment by peller** [comment] 2012-08-09 13:10
we need to reproduce it first.

**Comment by aerwin** [comment] 2012-08-26 14:58
@peller @jhpedemonte 

Assuming it's the same thing, then I can reproduce in preview when running from Eclipse. And, it appears to have negative side effects (e.g., I hit it while looking at #2991). It also seems to go away when I remove the zazl parm from the URL. Given this, should we move back to M7?

Simple scenario:
1. New HTML file
2. Drag button
3. New state
4. Configre onClick on button to switch to new state
5. Run in preview and click on button:

```
Uncaught TypeError: Cannot read property 'byId' of undefined _javascript:20687
(anonymous function) _javascript:20687
target.(anonymous function).dispatcher _javascript:3422
on.emit _javascript:3821
on.emit _javascript:3871
Evented.emit _javascript:4428
publish _javascript:4457
connect.publish _javascript:5801
States.setState _javascript:19642
(anonymous function)
declare._onClick _javascript:20745
inherited _javascript:1884
declare._onClick _javascript:20850
lang.hitch _javascript:1120
handles _javascript:14724
```

NOTE: The first time you run the stack trace is much more difficult to read because there's a bunch of gibberish interjected between each line. The stack trace above is after reloading the preview page.

And, unfortunately, it appears this exception has side effects. For example:
1. New HTML file
2. New button
3. Drag GridX onto page
4. New state
5. Make GridX invisible in Normal state
6. Ensure GridX is visible in new state
7. Set on click on button to switch to new state

The same exception appears and my GridX has no data in it:

![GitHub Logo](http://i.imgur.com/3fORr.png)

When I remove zazl attribute and reload the page, then when I click the button there's no exception and there's data in my GridX.

![GitHub Logo](http://i.imgur.com/lQsNR.png)

**Comment by peller** [comment] 2012-08-26 15:02
Do you have updates from last night?

**Comment by aerwin** [comment] 2012-08-26 15:41
@peller Must have merged those in pretty late! :) But, yes, after doing a git pull this morning things seem to be working. So, guess seems like we could close.

**Closed as completed** 2012-08-26 15:42 UTC
Labels: Priority High, Severity 2

**Comment by JonFerraiolo** [comment] 2012-08-26 16:24
I haven't studied this issue in depth, but in terms of what happened yesterday:

I discovered yesterday that the Outline palette had changed its logic for eyeball icon from using `display:none` to `display:none !important`, so I added logic to AppStates.js yesterday to deal with the possibility the `!important` was included in the state-specific style settings. That was a bit tricky because of the need to work around browser quirks.
