### ISSUE TITLE
Maqetta doesn't work for new users on maqetta.org

### ISSUE THREAD

**Issue by mbenitez01** [maqetta/maqetta#3972] opened 2013-06-01 03:04 UTC
Actual presentacion has nothing to do with youtube videos.
I start a new html file......and that's it...
the middle welcome screen doesn't change at alll, the widget do not appear at the left,
the component files do not load at the botton left......to resume :nothing happens (i tried chrome and firefox, under a windows 7 machine....)

**Comment by JonFerraiolo** [comment] 2013-06-01 15:15
@jhpedemonte @peller @billreed63 

@mbenitez01 is right. Things don't work for new users right now on maqetta.org. No problem with existing users.
 When I log in with an existing account, no problem. When I created a new account , I see the same things that @mbenitez01 sees, and I see similar projects when I try to create a new project from an existing account.

The Chrome console shows this for a brand new user when the app tries to load:

```
GET http://app.maqetta.org/maqetta/cmd/createResource?path=.%Fproject1%2Flib%isFolder=true 500 org.eclipse.core.runtime.CoreException: Count not write file /var/lib/maqetta/users/IDK/lib.)
```

which then cascades into a few other errors, such as Error loading view: davinci.ve.Palette.

When I log in as an existing user and try to create a new project, the console shows this:

```
davinci.js:50487
Resource interpreted as Document but transferred with MIME type image/svg+xml: "http://app.maqetta.org/maqetta/app/preview/images/iphone.svg". davinci.js:50487
GET http://app.maqetta.org/maqetta/cmd/createProject?name=project2&projectToClone=&eclipseSupport=false&projectTemplate= 500 (org.eclipse.core.runtime.CoreException: Could not write file: /var/lib/maqetta/users/IDQ/app.css.) dojo.js:3952
_4ca {stack: "Error: Unable to load cmd/createProject?name=proje…?f1554971890cef6693dcc67abd889d64370fcabd:3867:5)", message: "Unable to load cmd/createProject?name=project2&pro…eclipseSupport=false&projectTemplate= status: 500", response: Object, status: 500, responseText: "<html>↵<head>↵<meta http-equiv="Content-Type" cont…                                ↵</body>↵</html>↵"…}
 dojo.js:4587
```

It looks like the broken feature is new project creation. When I log into an existing account (and therefore I enter an existing project), I was able to create a new html file, save it, refresh my browser window, and then reopen the file I just created. 

I'm scratching my head on this one. Something is failing on the project creation side of things.

**Comment by JonFerraiolo** [comment] 2013-06-01 15:18
@mbenitez01 - thanks for the report. While we are trying to figure out how to fix things, you could try to download a local version of Maqetta at http://maqetta.org/downloads/, with instructions here: 
- http://app.maqetta.org/maqetta/app/docs/index.html#install

**Comment by JonFerraiolo** [comment] 2013-06-01 16:08
Restarting the Maqetta application (`service maqetta restart`) didn't fix things.

**Comment by peller** [comment] 2013-06-01 17:22
We may have hit the limit for number of files in a directory... possibly a 32K limit, depending on the filesystem

```
maqetta@maqetta.org [/var/lib/maqetta/users]# mkdir qqq
mkdir: cannot create directory `qqq': Too many links
```

Regardless, we're probably paying a performance penalty for having so many files in one dir

**Comment by peller** [comment] 2013-06-01 17:24
@jhpedemonte can we buy some time by cleaning out inactive users?  The only way around this might be to change the way we structure the users dir.

**Comment by JonFerraiolo** [comment] 2013-06-01 22:38
I did see some web pages that claim that Centos has a 32k limit on the number of subfolders within a given folder. For example, this page says that: http://serverfault.com/questions/98235/how-many-files-in-a-directory-is-too-many-downloading-data-from-net

**Comment by jhpedemonte** [comment] 2013-06-02 15:17
(Updated summary)

> can we buy some time by cleaning out inactive users? The only way around this might be to change the way we structure the users dir.

Nuts!

Unfortunately, there's no easy way to clear out inactive users in Orion (as far as I know).  Easiest thing would be to delete the oldest directories (i.e. projects) in the **users** dir.  Maybe those from 2012?

---

Currently, the **users** dir consists of all the project directories from every user.  Orion does support a `userTree` layout, where the **users** dir is instead organized by user id, with the project dirs under the user id dirs ([info](http://wiki.eclipse.org/Orion/Server_admin_guide#Configuring_project_layout)).

But we cannot easily switch to using `userTree`.  There are 2 issues:
1. We'd need to update the Maqetta code to properly support `userTree`.  I believe we assume a `flat` layout in a few places.
2. We'd need to somehow migrate the existing **users** dir to the new structure.

**Comment by mbenitez01** [comment] 2013-06-09 22:51
ok...downloaded version to my machine..didn´t work either..
now, web application opens page, but does n't finish central pane
loading.....can you please take a look at it and advise?

regards

Marcelo Benitez
15-6209-0968
4661-9462
pedromarcelobenitez(skype)
soluciones.16mb.com

**Comment by peller** [comment] 2013-06-10 00:37
Marcelo, more information would be needed to determine the cause of the problem.   Please check the console on the server and the Javascript console on the client.  Feel free to share the contents here, perhaps using a service like pastebin.com.

**Comment by jhpedemonte** [comment] 2013-06-10 01:14
@mbenitez01 The app at maqetta.org should be good now.  However, I wonder if there may not be issues with your account.  You tried to create a new account when the server was in a bad state and it may not have initialized your account correctly.  **Do you mind if I delete your account?**  You can then re-register.

(**Note:** You would lose any existing files, but it doesn't sound like you have any to begin with.)

As for the issues you are seeing with your local version, there isn't enough information to tell what is wrong.  See @peller's comment above.

**Comment by mbenitez01** [comment] 2013-06-10 02:33
Javier:

Thanks for your help.
I managed to create a new user and seems it works ok.

Yes, please, go ahead and erase mbenitez01. Please let me know when done so
I can reset it.

Regards

Marcelo Benitez
15-6209-0968
4661-9462
pedromarcelobenitez(skype)
soluciones.16mb.com

**Comment by jhpedemonte** [comment] 2013-06-10 13:26
Done -- I have deleted the 'mbenitez01' user.

Closing this bug as fixed.

**Closed as completed by jhpedemonte** 2013-06-10 13:26 UTC
