### ISSUE TITLE
SourceEditor is difficult to type in (often causing me to delete widgets)

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2358] opened 2012-05-21 19:46 UTC
In working through the SourceEditor/basic.html test plan (in particular the "Adding and deleting primitive widgets" section), I'm having difficulty with the parts that ask me to change a property value in the source pane.

Using Chrome on Mac...
1. Create new HTML file
2. Drop button onto canvas
3. Go to horizontal split view
4. Find the label attribute of the <button> element and click in it
5. Entire button element is selected, so click again within label attribute to unselect element and get cursor where you want it
6. Start typing some characters and eventually the entire button element will get reselected in source and my next key stroke to update the button label deletes the entire button element from source. It seems whenever the design view gets updated to reflect my source changes that the button element will get reselected. So, quite difficult to type more than a few characters as part of a property update without inadvertently deleting the element.

**Comment by aerwin** [comment] 2012-05-21 19:52
Going into the next section of the test plan, it's difficult to do any typing (not just property updates). E.g., try to type the following in the source editor for Step 10 of the "Container widgets" section without blowing something else away.

```
<div></div>
```

**Comment by jhpedemonte** [comment] 2012-05-21 19:56
-> @doronrosenberg, since you've been in this code recently.  Also cc @peller

**Comment by JonFerraiolo** [comment] 2012-05-21 19:58
Maybe we need to turn off the feature for M6 where selecting in design view causes the corresponding text in source view to be selected? Very bad to turn that off, but we might have to.

**Comment by doronrosenberg** [comment] 2012-05-21 20:02
Hence the reason I suggested to get rid of DOM selection and have the editor do the selecting via css classes.

We also can't distinguish event origin I believe, so if we only want to handle this state it could get a bit tricky.

**Comment by doronrosenberg** [comment] 2012-05-21 20:11
The problem isn't design to source, its when clicking in source view we select the selected widget.

**Comment by doronrosenberg** [comment] 2012-05-22 17:05
Moving to m7 so we can reenable this

**Comment by JonFerraiolo** [comment] 2012-05-29 20:58
-> @peller

**Comment by peller** [comment] 2012-08-01 17:24
seems to have been fixed by removing the timeout in 513e2f077f37aeb2182357226b06ecc288403c9d

**Comment by aerwin** [comment] 2012-08-08 16:16
Reopening... just ran into this doing the SourceEditor/basic.html test case... in particular, the part where it says to add a div (e.g., trying to type `<div></div>`.

**Comment by peller** [comment] 2012-08-10 05:19
It appears this regressed with a7d8ede1 @JonFerraiolo

**Closed as completed** 2012-08-10 05:28 UTC
Labels: Source Editors, Priority High, Severity 2
