### ISSUE TITLE
Can't remove class from button

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#2107] opened 2012-04-20 14:45 UTC
Drag and drop button 
Select button in properties->class type "testClass"
Click away
click button 
in properties ->class clear comboEdit click away from button 
Select button notice the class is still set also the source is still set..

**Comment by billreed63** [comment] 2012-04-20 15:10
I also just noticed that I can't assign a class to a newly dropped button

**Comment by doronrosenberg** [comment] 2012-04-20 18:41
@JonFerraiolo @jhpedemonte 

I don't think this is a regression actually.  If you click away from the button into the canvas on maqetta.org, the same thing happens.  Same issue occurs with the id input for me, which hasn't changed.  If you click away into an area that is not the canvas it works correctly.

The issue is that once you click away, this._widget is nulled out by onWidgetSelectionChange, which fires before the onChange finishes for the property wdget.  In fact this happens on all properties.

Probably a usability issue - we could send the widget as a parameter rather than rely on this._widget.

**Comment by JonFerraiolo** [comment] 2012-04-20 19:50
@childsb 

@doronrosenberg is right - we've had this usability issue forever. Assigning to me to try to fix. Maybe @doronrosenberg has already sketched out the fix and it's a matter of making certain things happen in a slightly different order.

One more thing - assigning to me because the Property palette stuff sometimes is hugely complicated with major learning curve.

**Comment by doronrosenberg** [comment] 2012-04-20 20:05
I don't think we can change the event ordering here easily.  More likely we would have to pass in the affected widget reference through in each onChange handler.  The question is if this should wait if we are going to redo the property palette in the near future anyways and make sure we correctly handle this case

**Comment by JonFerraiolo** [comment] 2012-04-20 22:05
You might be right, but I'll take a look at this and see if there is a relatively easy and safe fix for time being.

**Comment by JonFerraiolo** [comment] 2012-05-02 01:52
Changing to Prio-Med because we've had this problem forever.

**Comment by JonFerraiolo** [comment] 2012-05-03 03:45
@doronrosenberg - reassigning to you. Hope that's OK.

I think I see what the problem is here and how to fix. I got into the debugger and compared how the 'class' and 'id' fields worked versus the widget-specific properties (WidgetProperties.js) and in the process discovered (duh!) we recreate the entire 2 lines for the toolbar area with each widget selection change event. As a result, when a user clicks on the canvas, the 'class' and 'id' INPUT fields get removed from the document, and as a result, the onchange handlers don't get fired. I'm 90% sure that if we don't clobber the INPUT fields, then onchange will fire, and we won't lose the user's changes to 'class' or 'id'.

Anyway, it's bad, wasteful, unnecessary programming to recreate the INPUT boxes each time a user changes the selection. We should create the INPUT boxes for 'class' and 'id' at program startup time and then fiddle with the inner content only with widget selection changes. In particular, we should only change the values of the fields and not recreate the fields when a new widget is selected. When no widget is selected, we should make a DIV that holds the 'id' and 'class' properties invisible.

I expect rewriting this bit of logic will prove to be: (a) straightforward relatively easy programming, (b) but a non-trivial amount of time to do. I fooled around some and concluded that the best place to put the creation logic for the various DIVs and SPANs for the revised toolbar would be in a postCreate() method because this.domNode exists by then and at that point we can attach classes and inner content to this.domNode.

One option is to combine this task with #2132

**Comment by doronrosenberg** [comment] 2012-05-03 18:00
@JonFerraiolo The issue isn't the clobbering of the input fields - the real issue is that _widget is nulled out before the onchange fires, which happens when the user clicks on the canvas.

Now for the other parts of properties, it seems that clicking on say Label for button and then clicking into the canvas does not cause a blur even, so we are handling this somehow already in the auto generated props.

**Comment by doronrosenberg** [comment] 2012-05-03 18:29
Looks like Context.js::blockChange is the magic we need

**Comment by JonFerraiolo** [comment] 2012-05-03 18:31
> the real issue is that _widget is nulled out before the onchange fires, which happens when the user clicks on the canvas.

Yes, and the reason _widget is nulled out is that clicking on the canvas calls Context.select() (for null or a different widget), which ultimately invokes the widget selection change callback in WidgetToolBar.js, which causes a reassignment of this.domNode.innerHTML, which causes destruction of the old INPUT elements and creation of new INPUT elements. Because the old INPUT elements are destroyed, the browsers don't fire the onchange events on those elements.

> clicking into the canvas does not cause a blur even

Yes, I don't understand why blur events aren't getting fired always. However, onchange events are indeed fired for other properties, and the onchange events are triggers assignment of the revised value to the currently selected widget (i.e., what was selected before the click on the canvas).

**Closed as completed** 2012-05-03 18:47 UTC
Labels: Priority Med, Regression
