### ISSUE TITLE
TypeError: cs is null when reloading browser page

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3279] opened 2012-09-06 17:25 UTC
Using FF on Mac going to moketta...

I've noticed this exception several times when coming back up from reloading the browser page. Seems to happen if there are a couple editors open before the reload. Not sure if there are side effects.

```
TypeError: cs is null
[Break On This Error]   

...e){_1a7.charOrCode=_1a7.keyCode;_19f.deprecated("keyCode attribute parameter for...

dijit.js (line 15)
```

**Comment by aerwin** [comment] 2012-09-06 17:28
Really does seem to require 2 editors be open... not seeing if only one editor open when reload the page.

**Comment by jhpedemonte** [comment] 2012-09-06 19:16
@doronrosenberg @aerwin @billreed63 -> can one of you please investigate?

**Comment by doronrosenberg** [comment] 2012-09-07 01:59
hccss.js

```
    // Has() test for when background images aren't displayed.  Don't call has("highcontrast") before dojo/domReady!.
    has.add("highcontrast", function(){
        // note: if multiple documents, doesn't matter which one we use
        var div = win.doc.createElement("div");
        div.style.cssText = "border: 1px solid; border-color:red green; position: absolute; height: 5px; top: -999px;" +
            "background-image: url(" + (config.blankGif || require.toUrl("./resources/blank.gif")) + ");";
        win.body().appendChild(div);

        var cs = domStyle.getComputedStyle(div);
```

cs is null in this case.  @peller, the stack is all dojo

**Comment by doronrosenberg** [comment] 2012-09-07 02:07
Stack starts with:

```
forEach(vector=[function()], callback=function())dojo.js (line 93) signal(type="idle", args=[])dojo.js (line 331)
guardCheckComplete(proc=function())dojo.js (line 1230)
checkComplete()dojo.js (line 1240)
onLoadCallback()dojo.js (line 1402)
onLoad(e=load )dojo.js (line 1636)
```

Seeing ready makes me wonder if the document isn't ready yet when this is called?

**Comment by peller** [comment] 2012-09-07 03:38
yeah, does sound that way, but based on the stack, that's surprising.  What's the full stack and how far up the stack does it go before it's handled?

**Comment by doronrosenberg** [comment] 2012-09-07 15:09
@peller:

```
(?)()hccss.js (line 34) has(name="highcontrast")dojo.js (line 135)
(?)()hccss.js (line 48)
(?)()ready.js (line 104)
onLoad()ready.js (line 35)
requestCompleteSignal()ready.js (line 51)
onLoad()ready.js (line 43)
(?)(listener=function())dojo.js (line 332)
forEach(vector=[function()], callback=function())dojo.js (line 93)
signal(type="idle", args=[])dojo.js (line 331)
guardCheckComplete(proc=function())dojo.js (line 1230)
checkComplete()dojo.js (line 1240)
onLoadCallback()dojo.js (line 1402)
onLoad(e=load )dojo.js (line 1636)
```

**Comment by JonFerraiolo** [comment] 2012-09-07 23:42
Over the past several months, I've run into multiple exceptions in dojo.style where cs is undefined or null at document startup time. It's not that Dojo isn't ready or the doc isn't loaded - the problem is that the browsers for performance optimization reasons don't calculate computed style immediately always, and sometimes calculates computed style in a separate logic thread. 

There is logic in a few places in Maqetta to only call dojo.style() if computed style is finally available. For example, in _ShapeCommon.js:

```
        if (this.shapeNode && this.shapeNode.ownerDocument && this.shapeNode.ownerDocument.defaultView) {
```

But in this issue, it looks like Dojo itself is trying to get the computed style before the layout logic is ready to provide a computed style value. So, in this case, I don't think we can put an IF statement in Maqetta. Instead, the IF statement needs to be in Dojo. 

High-contrast logic? I'll bet we can figure out who on the Dojo team we should be working with.

-> @peller for M8 Prio-High

**Comment by peller** [comment] 2012-09-08 01:44
this stuff is registered at onload, which I thought was a pretty safe bet for calling getComputedStyle.  @wkeese, any idea?  Actually, it's currently using dojo/ready, and is called prior to the parser

**Comment by wkeese** [comment] 2012-09-08 10:23
It sounds safe to me too.  Never seen what Jon is talking about.

Maybe fallout from trying to use dojo/domReady! In sync mode?  I forget if
you are using the sync or asynchronous loader.

Or maybe at that point win.doc is pointing to a different doc that isn't
loaded, the Iframe doc of a dijit.Editor.

**Comment by JonFerraiolo** [comment] 2012-09-08 14:57
I expect the difference with the Maqetta page editor is that widgets are constructed dynamically, not using Dojo's normal onload parsing. In particular, at Context.js:1160 we have this logic:

```
        // special handling for 'data-dojo-config' attr
        djConfig = djConfig ? require.eval("({ " + djConfig + " })", "data-dojo-config") : {};
        // give precedence to our 'config' options, over that in file; make sure
        // to turn off parseOnLoad
        lang.mixin(djConfig, config, {
            async: true,
            parseOnLoad: false
        });
```

so parseOnLoad is turned off. Then we register a domReady callback in newfile.template.html:

```
        <script>
            // base dependencies needed for VE
            require([
                'dojo/parser',
                'dojox/html/_base',
                'dojo/domReady!'
                {additionalModules}
            ], top.loading{id});
        </script>
```

Within that `top.loading{id})` function, we do a ton of processing, with a few different async threads that are synchronized using dojo deferreds. In the first thread, we do things such as set BODY's width and height to 100%. I think it's the same thread that injects the LINK or STYLE elements into the HEAD that correspond to the CSS themes that the user's document is using, followed by this logic which I believe does an innerHTML assignment onto the BODY, but without invoking the dojo parser yet:

```

        // Set content
        //  Content may contain inline scripts. We use dojox.html.set() to pull
        // out those scripts and execute them later, after _processWidgets()
        // has loaded any required resources (i.e. <head> scripts)
        var scripts;
        // It is necessary to run the dojox.html.set utility from the context
        // of inner frame.  Might be a Dojo bug in _toDom().
        this.getGlobal()['require']('dojox/html/_base').set(containerNode, content, {
            executeScripts: true,
            onEnd: function() {
                // save any scripts for later execution
                scripts = this._code;
                this.executeScripts = false;
                this.inherited('onEnd', arguments);
            }
        });
```

Then call `Context.js:_processWidgets()` which appears to invoke the dojo parser asynchronously once all of the prereqs have been satisfied (but I'm not sure whether this is when widgets actually get parsed and instantiated or not - I'm pretty sure the answer is no):

```
    _processWidgets: function(containerNode, attachWidgets, states, scripts) {
        var prereqs = [];
        dojo.forEach(query("*", containerNode), function(n){
            var type =  n.getAttribute("data-dojo-type") || n.getAttribute("dojoType") || /*n.getAttribute("oawidget") ||*/ n.getAttribute("dvwidget");
            //doUpdateModelDojoRequires=true forces the SCRIPT tag with dojo.require() elements
            //to always check that scriptAdditions includes the dojo.require() for this widget.
            //Cleans up after a bug we had (7714) where model wasn't getting updated, so
            //we had old files that were missing some of their dojo.require() statements.
            prereqs.push(this.loadRequires(type, false/*doUpdateModel*/, true/*doUpdateModelDojoRequires*/));
            prereqs.push(this._preProcess(n));
//          this.resolveUrl(n);
            this._preserveStates(n, states);
        }, this);
        var promise = new Deferred();
        all(prereqs).then(function() {
            this.getGlobal()["require"]("dojo/ready")(function(){
                try {
                    this.getGlobal()["require"]("dojo/parser").parse(containerNode);
                    promise.resolve();
                } catch(e) {
... snipped ...
                }

                if(attachWidgets){
                    this._attachAll();
                }

                if (scripts) {
                    try {
                        dojox.html.evalInGlobal(scripts, containerNode);
                    } catch(e) {
                        console.error('Error eval script in Context._setSourceData, ' + e);
                    }
                }
            }.bind(this));
        }.bind(this));

        return promise;
    },
```

Finally `this._attachAll()` runs through the widgets on the page and calls `getWidget()`, which if my memory is correct, is where we call the constructors for the widget. @peller @jhpedemonte feel free to correct this.

But my key point is that the Maqetta page editor manipulates the inner iframe's DOM in a manner much different than simple parsing of Dojo markup, which in my experience sometimes results in `defaultView` having no value at page load time.

**Comment by wkeese** [comment] 2012-09-09 00:15
Wow, complicated.   Not sure why that would cause a problem though.

Two other things to check are that, at the time that code runs, <body>
isn't display:none and it's well formed HTML (ex: no missing closing tags).

**Comment by peller** [comment] 2012-09-11 01:25
@wkeese we're using the asynchronous loader for everything now.  I'm seeing this error on occasion in both hccss and uacss

**Comment by peller** [comment] 2012-09-11 01:41
@wkeese I think you found it.  display is none (dijitHidden is set on an ancestor of the containing iframe)  We're loading the document in a hidden tab, which must be a regression.  The tabs are loaded in succession, and now that we use async, other tabs appear pushing the document to the background before onload fires.

**Comment by wkeese** [comment] 2012-09-11 11:22
@peller: Ok good, so hopefully you can fix maquetta not to hide the iframe
as it loads?   Seems like hiding it could cause other problems too
especially with layout widgets.

**Comment by peller** [comment] 2012-09-21 20:22
accidentally checked in an experiment 1c6f34c8baea451b068fa7923c7751075e6abb21 to defer selecting the pane until all tabs were loaded (still fails), which had flaws corrected by @JonFerraiolo 66eaac97a071fbf7985c7309c726c5ac7a0dddc8

**Comment by JonFerraiolo** [comment] 2012-09-22 00:08
@peller - Can you look at the above commit (off in branch 3279CsNullExceptionFix)? I may have found the source of the problem and come up with a fix. 

What I was observing was that the IF statement at EditorContainer.js:84:

```
                    if(dijit.byId(editorsContainer).selectedChildWidget.domNode == this.domNode){
```

was picking the wrong initial editor because (I am guessing) selectedChildWidget gets updated each time we do an `addChild` on the StackContainer (the "EditorsContainer" stack container), and because of timing issues, sometimes the initially selected editor's ContentPane hasn't been added yet to that StackContainer, so the value of selectedChildWidget does not correspond to the initially selected editor.

My fix was to compare against `davinci.Workbench._state.activeEditor` instead. The reason for using that variable for the comparison is that it has the proper value both at program initialization (when no editors have been created yet) and throughout execute as we switch between editors. I realize that it's bad to use hidden variables outside of local scope, but before cleaning up the code, my first question is "does my fix work"?

The one thing I can say is that I had a 100% reproducible scenario when running Mac/FF where without my fix I always got the cs null exception, and after my fix I never get the exception.

**Comment by peller** [comment] 2012-09-22 01:00
I traced that code back to this checkin about a year ago f5cad4500176626dbe6dbeb2d497b301c41d86f9  The intent was to check to see if the editor was actually the one visible in the TabContainer.  The original check did just that... perhaps with all the async callbacks, there's an opportunity for that condition to change before the code finishes execution?  I guess, once things settle down, if the selection matches what it ought to be (i.e. activeEditor) then that test is more valid?

**Comment by JonFerraiolo** [comment] 2012-09-22 15:40
> I guess, once things settle down, if the selection matches what it ought to be (i.e. activeEditor) then that test is more valid?

By "settle down", you mean all of the initialization process have been completed? Yes, once all of the tabs are properly initialized, then the selected child check would work, but with all of our async processes, my conclusion is that it is better to check against activeEditor rather than selected tab because `davinci.Workbench._state.activeEditor` doesn't change during the initialization process (it is set before any calls to OpenEditor) and doesn't change in the switchEditor process, whereas selected child gets updated during the initialization process as each editor is added to the StackContainer via addChild() because addChild() automatically selects the newly added child.

The reason we see the error more on FF than Chrome is that Chrome is faster, so in a higher percentage of the time, all of the editors have already finished their addChild() logic, so the selected child check tends to choose the correct initial editor.

**Comment by JonFerraiolo** [comment] 2012-09-27 02:54
@jhpedemonte 

Reopening - the fix for this didn't get properly cherry-picked into the M7_0_1 branch.

**Comment by JonFerraiolo** [comment] 2012-09-27 13:24
@jhpedemonte - I just cherry-picked and pushed f5052b7c75e4029ad92b45187f730e393e222e7b from master into M7_0_1 branch. Somehow we missed that commit when creating the M7_0_1 branch. . Let's retest when a new build is available.

**Comment by JonFerraiolo** [comment] 2012-09-27 23:41
Closing again. Appears to be fixed in M7_0_1 builds.

**Closed as completed by JonFerraiolo** 2012-09-27 23:41 UTC
Labels: Visual Editor, Priority High, Severity 2
