### ISSUE TITLE
Unable to change button width 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#964] opened 2011-09-09 15:13 UTC
Test case: 
Properties palette basic tests (part 4): CSS cascade features

Create a virgin user environment navigating away from Maqetta, clearing browser cache, killing the server, removing users/ folder, restarting the server, and navigating browser back to Maqetta. (For server-hosted, create a new user)
Clone the "claro" theme into a new theme using the "New Theme" command. For example, create theme "mytheme".
Issue a "New HTML File" command.
Drag a Button onto canvas.
Go to Properties palette and go to 'width' property. Click on the right-pointing icon at the right side of the 'width' property to show the CSS cascade.
You should see a list of CSS selectors, at least one of which should include within it ".claro .dijitButtonNode". You should not see an "element.style" entry.
Up above in the type-in area of the 'width' property, type "200px", then press Enter to try to commit the value.
This operation if completed would modify one of the CSS rules in the (read-only) Claro theme. Any rules that would modify a read-only theme should be disabled. This isn't working completely yet. Here is a pending bug: https://github.com/maqetta/maqetta/issues/258
If you see the "about to change a global CSS rule, are you sure", click "Cancel".

Click on the Switch themes icon on the toolbar, and change to your new theme ("mytheme").
Go again to Properties palette and go to 'width' property and the CSS cascade view for that property. Up above in the type-in area of the 'width' property, type "200px", then press Enter to try to commit the value. You should see an "about to change a global CSS rule, are you sure".
This operation attempts to change one of the style rules within one of the CSS files for your new "mytheme" theme.
Click "OK" to make a global change such that all Buttons will have width 200px. The currently selected button should now be 200px wide.

**Comment by JonFerraiolo** [comment] 2011-09-09 15:18
Dupe of #958

**Closed as completed by JonFerraiolo** 2011-09-09 15:18 UTC
Labels: Bug, Priority High
