### ISSUE TITLE
Save As over same file makes it so that file will not open completely

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#629] opened 2011-06-30 23:11 UTC
- Create new HTML file
- Select Save
- Select Save As
- Chose to overwrite the current file (file1.html)
- Try to open the file (file1.html) again

It brings up the widget palette on the left and the outline on the right but doesn't bring up the canvas.
Chrome console reports: Uncaught TypeError: Cannot call method 'set' of undefined
Testing in Windows/Chrome with lab14 build

**Comment by JonFerraiolo** [comment] 2011-07-01 00:39
Brad, can you look into this one?

**Comment by childsb** [comment] 2011-07-05 18:47
This works for me on osx/FF and osx/Chrome.  Maybe fixed in another bug?

Cindy - could verify and re-open if you still see this issue?

**Comment by JonFerraiolo** [comment] 2011-07-05 18:56
I am able to reproduce using today's build on Win/FF5 and running the unbuilt version (launch from Eclipse) on Mac/Chrome. What I did:
- New HTML file
- Add Button
- Save
- Show debugger console
- SaveAs to save file name
  Result=> Uncaught TypeError: Cannot call method 'set' of undefined. /dijit/layout/StackController.js:158

**Comment by childsb** [comment] 2011-07-05 19:03
ok let me try this on windows then

**Comment by childsb** [comment] 2011-07-05 19:17
I tried both built and unbuilt versions on FF5/Chrome in windows and still no error.  Are you sure your browser cache is clear/clean workspace?

**Comment by childsb** [comment] 2011-07-05 19:49
ok finally found my problem!  gotta save as with the same file name.  i'll fix this.

**Comment by childsb** [comment] 2011-07-05 21:04
Fixed with commit 10a3cf6d148feeaf3ea24c50c27946d29808aa18

The deleteResource() call was closing the editor without removing it from the parent, and when you went back to create a new instance of the editor, it used the same id (same file name), and thought the editor already existed even though it didn't.

**Closed as completed by childsb** 2011-07-05 21:04 UTC
Labels: Bug, Priority High
