### ISSUE TITLE
We are eating exceptions during widget creation

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2780] opened 2012-07-18 16:22 UTC
@peller @jhpedemonte 

Drag and drop a ScreenSizeAware widget from untested - it fails and throws an exception internally, but never shows in the console.  The exception is in DijitWidget.js line 71

**Comment by JonFerraiolo** [comment] 2012-07-18 17:02
Setting to M7/Prio-Low - would be nice to look at this. I've noticed that something changed in last couple of months where exceptions aren't showing in console in some cases.

**Comment by peller** [comment] 2012-07-18 19:37
there are known regressions in Deferred/DeferredList which are due to be fixed in 1.8.0rc1

**Comment by peller** [comment] 2012-07-18 19:39
moving to promise/all seems to have fixed this.

**Closed as completed by peller** 2012-07-18 19:39 UTC
Labels: Bug, Priority Low, Severity 3
