### ISSUE TITLE
Some way for users to set parameters on sub-items on widgets like Tree and DataGrid

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#74] opened 2011-05-02 20:24 UTC
Right now, our mini-language for data entry only allows simple textual content.
## For Tree, we have something like:

Item 1

> Item 1.1
> ## Item 1.2
> 
> but there is no provision for setting different properties for different items.
> In particular, sometimes the designer wants to put a particular icon on the
> TreeItem. This capability is a must for creating UI mockups.

The question is how best to do this. Here are some ideas off the cuff:

(1) If you put the type-in point on line N within inline edit, the property
palette will present Widget-specific properties for the hidden widget that
corresponds to that item. (My guess is this is not a good idea)

(2) Make our current inline edit language more complicated, such as allowing
something like @iconClass=whatever

(3) Provide a datagrid data entry setup for inline edit for certain widgets
where the text appears in column 1 and various item-specific values are entered
into the other columns

(4) Provide an alternate data entry approach for "advanced data entry" where
the user types in a JSON literal instead of plain text

(5) something else???

Another big requirement is putting onclick handlers on the sub-items. For
example, putting onclick onto a MenuItem or a TreeItem

**Comment by billreed63** [comment] 2011-05-05 17:18
duplicate of issue #79

**Closed as completed** 2011-05-05 17:18 UTC
Labels: Visual Editor, Widget Libraries, Feature, Priority High
