### ISSUE TITLE
Hang on Create new page - session management problems?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3234] opened 2012-09-04 18:06 UTC
I was testing on our staging server this morning (moketta) using Mac/Safari, and got distracted by other things for awhile (30 minutes? an hour?) and then went back to my Maqetta window in Mac/Safari and tried to issue a "Create Desktop Application" command. The dialog came up, but after clicking on "Create" in the dialog, nothing happened, the software just sat there. No warning. No session redirect.

I then refreshed my Maqetta browser window, and I was able to issue the Create Desktop Application command successfully.

Unfortunately, I didn't have my debugger window open at the time...

**Comment by JonFerraiolo** [comment] 2012-09-04 18:10
@childsb @jhpedemonte @peller @aerwin @doronrosenberg

**Comment by peller** [comment] 2012-09-04 18:19
I think you can bring up the console after the fact.  Close until we have some data?

**Comment by JonFerraiolo** [comment] 2012-09-04 18:24
No, I think we have a problem somewhere in our session logic which is a major ship-stopper. I suggest @billreed63 pound on that area to make sure session timeout logic is solid. We can't have the app hanging on people if they walk away for 30 minutes.

**Comment by JonFerraiolo** [comment] 2012-09-04 19:13
Just saw this again using Mac/Safari. After clicking Create, the network panel shows "502 Bad gateway" when attempting a `/maqetta/cmd/createResource`. Full response:

```
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.2.3</center>
</body>
</html>
```

**Comment by aerwin** [comment] 2012-09-04 19:18
Just saw this one too...

Using FF on Mac going to moketta...

Working along on mobile theme editor tests and tried to create a new mobile application. Nothing happened and noticed following in console. Reloaded page to see if it would go away and was taken to login page.

```
GET https://app.moketta.org/maqetta/cmd/createResource?path=.%2Ftest201209-04%2Ffile2.html

502 Bad Gateway
        200ms   
dojo.j...vision@ (line 4720)

"NetworkError: 502 Bad Gateway - https://app.moketta.org/maqetta/cmd/createResource?path=.%2Ftest201209-04%2Ffile2.html"

create...e2.html

RequestError: Unable to load cmd/createResource?path=.%2Ftest201209-04%2Ffile2.html status: 502

uncaught exception: Folder.createResource failed: name=file2.htmlresponse=undefined

```

**Comment by jhpedemonte** [comment] 2012-09-04 19:23
OK, this implies that Nginx couldn't forward on the request to Maqetta, for some reason.  The hosting company support was looking into the email issue and they may have done something to bring Maqetta down temporarily.

Let's keep this one open as we test and see if we run into it again.

**Comment by JonFerraiolo** [comment] 2012-09-06 03:34
Running localhost, my machine was closed for a couple of hours, and when I tried to resume work in Maqetta, I see this in the console. Most importantly, there was no session timeout popup, and I was not taken to the login screen.

```
GET http://localhost:8081/maqetta/cmd/removeWorkingCopy?path=.%2Fproject1%2Fapp.css 401 (Unauthorized) xhr.js:210
ErrorCtor
 xhr.js:473
ErrorCtor
 "RequestError: Unable to load cmd/removeWorkingCopy?path=.%2Fproject1%2Fapp.css status: 401
    at handleResponse (http://localhost:8081/maqetta/app/dojo/request/xhr.js?@revision@:50:12)
    at <error: Error: INVALID_STATE_ERR: DOM Exception 11>
    at xhr (http://localhost:8081/maqetta/app/dojo/request/xhr.js?@revision@:210:9)
    at Object.dojo.xhr (http://localhost:8081/maqetta/app/dojo/_base/xhr.js?@revision@:657:11)
    at Object.dojo.xhrGet (http://localhost:8081/maqetta/app/dojo/_base/xhr.js?@revision@:680:15)
    at Object.Runtime.serverJSONRequest (http://localhost:8081/maqetta/app/davinci/Runtime.js?@revision@:380:8)
    at declare.removeWorkingCopy (http://localhost:8081/maqetta/app/davinci/model/resource/File.js?@revision@:103:11)
    at declare._close (http://localhost:8081/maqetta/app/davinci/workbench/EditorContainer.js?@revision@:186:25)
    at declare.onClose (http://localhost:8081/maqetta/app/davinci/workbench/EditorContainer.js?@revision@:196:15)
    at okToClose (http://localhost:8081/maqetta/app/davinci/Workbench.js?@revision@:1468:30)" instrumentation.js:18
PUT http://localhost:8081/maqetta/cmd/setWorkbenchState 401 (Unauthorized) xhr.js:210
ErrorCtor
 xhr.js:473
```

**Comment by JonFerraiolo** [comment] 2012-09-06 18:10
Just saw this again on the staging server when attempting a New Theme... command. The app just hung. When I hit browser refresh, the login screen came up. Unfortunately, I didn't have the debugger window open at the time.

**Comment by aerwin** [comment] 2012-09-06 18:19
Just saw these errors in my FF console when dragging a widget onto a page. No redirect to login or other indication in UI that my session had gone bad.

```
GET http://app.moketta.org/maqetta/app/metadata/html...am.json?3f389b2d6a9f5fbb347870178289f2b9ae90ac1b

304 Not Modified
        71ms    
dojo.j...vision@ (line 4720)
PUT http://app.moketta.org/maqetta/test20120906/file3.html.workingcopy

403 Forbidden
        80ms    
dojo.j...vision@ (line 4720)

"NetworkError: 403 Forbidden - http://app.moketta.org/maqetta/test20120906/file3.html.workingcopy"

file3....ingcopy

RequestError: Unable to load ./test20120906/file3.html.workingcopy status: 403

An error occurred: davinci.model.resource.File.prototype.setContents RequestError: Unable to load ./test20120906/file3.html.workingcopy status: 403 : ./test20120906/file3.html.workingcopy


...or("An error occurred: davinci.model.resource.File.prototype.setContents "+err+"...
```

**Comment by jhpedemonte** [comment] 2012-09-06 18:33
Not sure why we'd get 401 and 403 errors.  That seems odd.

**Comment by jhpedemonte** [comment] 2012-09-06 18:43
Also, both of these issues are related to working copies.  Wonder what's different about them?  @childsb, have any ideas?

**Comment by jhpedemonte** [comment] 2012-09-06 18:46
Next time you see this error, stop immediately and ping me, so I can check the server logs and the state of your workspace.

**Comment by peller** [comment] 2012-09-06 20:06
wonder if there's some confusion between dojo/xhr and dojo/request layers.  Each has its own error handler, and the new dojo/request seems to be getting used under the covers.  Perhaps we should register one on each to make sure we get called? [UPDATE: I'm assured that this isn't the case... dojo/xhr should still use dojo/io/error, for compat reasons]

**Comment by peller** [comment] 2012-09-06 20:18
Perhaps we should instrument Workbench.handleIoError with some logging to assure it's getting called and see why the dialog isn't getting posted?  Seems like it should be...  How hard is this to reproduce?

**Comment by peller** [comment] 2012-09-06 20:23
> Not sure why we'd get 401 and 403 errors. That seems odd.
> Don't know if there's any chance #1950 is related to this.  HTTP error code trivia may have real implications when we're using proxy servers.

Also @childsb, didn't you say that workingcopy requests were abstracted away on the server?  Should the client ever see workingcopy files or use them in REST calls?

**Comment by jhpedemonte** [comment] 2012-09-06 21:34
> Perhaps we should instrument Workbench.handleIoError with some logging

@peller, please do (as long as the logging doesn't dump a bunch of info in the logs).

**Comment by jhpedemonte** [comment] 2012-09-10 15:28
Closing.

**Closed as completed by jhpedemonte** 2012-09-10 15:28 UTC
Labels: Priority High, Regression, Severity 2
