### ISSUE TITLE
NPE when closing visual editor

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#860] opened 2011-08-25 22:07 UTC
0) enable halt on errors in FF debugger
1) Open sample1.html
2) close sample1.html
3) observe error: "davinci.Runtime.currentEditor is null "

**Comment by JonFerraiolo** [comment] 2011-08-26 14:43
Assigning to @peller just so that it isn't unassigned but maybe should go to @waynevicknair

**Comment by peller** [comment] 2011-08-26 14:49
I can't reproduce this.  @childsb, can you?

**Closed as completed** 2011-08-29 21:18 UTC
Labels: Visual Editor, Bug, Priority Low
