### ISSUE TITLE
Toolbar does not appear for text editing

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#577] opened 2011-06-20 17:32 UTC
testing MainMenu-New Menu: New File - in root directory, with save. at step 4, there is no apparent save button nor is there a toolbar that i can find to save my 'a.txt' file.

**Comment by waynevicknair** [comment] 2011-06-20 17:32
oops. forgot to mention: running FF5.

**Comment by JonFerraiolo** [comment] 2011-06-20 18:26
Duplicate of #43

**Closed as completed by JonFerraiolo** 2011-06-20 18:26 UTC
Labels: Visual Editor, Bug
