### ISSUE TITLE
When editing source, cursor jumps back to first position

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1078] opened 2011-10-13 20:06 UTC
To reproduce:
1. Drop a **dojox.mobile.View** in new page.
2. Drop **Heading**, name it "View 1".
3. Drop another **View** on page (this creates a sibling view to first one).
4. Drop **TabBar** onto second View.
5. Open split editor.
6. In source editor, try to add the text **fixed="top"** as an attribute to the TabBar.

For me, in the middle of typing, the cursor jumps up to the first position in the text.

@JonFerraiolo

**Comment by JonFerraiolo** [comment] 2011-10-13 20:51
Very cool that there is a reproducible case for this seemingly intermittent bug! See #891 and #992. I hope there is a single bug that fixes all of the jumping scenarios.

I was able to reproduce on both Mac/FF and Mac/Chrome. When trying to add `fixed="top"`` to the TabBar widget in source view, I can type "fix" ok, but somehow the "e" doesn't take, and if I continue on and manage to enter "fixed=", then when I try to enter the double-quote character, the cursor jumps up to the top of the source doc.

**Comment by waynevicknair** [comment] 2011-10-18 20:44
yep, i can now recreate this bug at will. good going javier!

**Comment by peller** [comment] 2011-10-19 18:24
yes, great example!  Verified on the new Orion M3 code. I'm noticing that clicking on the tab bar does not select the text and vice versa.  Clicking on the tab bar selects the whole document. Perhaps that has something to do with the change in focus?  We must have circular select events where this sort of mismatch (change in widget selection where the widget should not have changed -> change in editor text selection) would change our cursor position.

**Comment by waynevicknair** [comment] 2011-12-14 18:38
i cannot reproduce this issue anymore as the caret completely disappears. i believe that it is now a duplicate of issue #1369

**Comment by waynevicknair** [comment] 2011-12-23 20:06
the behavior here has changed such that editing in source view is only impacted when there are multiple dojox.mobile.Views on the page. additionally, the user can now move the cursor freely and edit text without any cursor jumping. However, when widgets are selected in visual editor pane or outline view the cursor jumps to top of file. 

this behavior is far less annoying than before. therefore i am lowering the priority of this bug to low.

**Comment by JonFerraiolo** [comment] 2011-12-23 22:29
Moving to Priority-High. We really should have source view working well with Views, and should hold up shipping M4 until we get there. Every mobile UI will have Views, mobile is the big new feature, and source editing is a key existing feature. May need multiple people around at once to get to bottom of this. @peller, @jhpedemonte

**Comment by waynevicknair** [comment] 2011-12-23 23:17
i agree with the principle of making editing the best it can be. however, given that this error occurs only in SPLITVIEW in the visual editor with multiple 'dojox.mobile.Views' on the page and that the bug is present in M3 and has not been reported by maqetta.org users, and that there is no data loss, i believe priority high is uncalled for. @peller @jhpedemonte

**Comment by waynevicknair** [comment] 2011-12-24 00:21
what's happening is the ViewHelper is modifying the DOM in its '_updateVisibility()' method using editor commands that modify the source (adding/removing  'display="none"' to/from the source HTML). the source editor is reacting to the changes and clearing selection. i believe that is the default behavior of the editor (@peller please correct me if i'm wrong). it may be possible to circumvent this behavior and reselect the previous selection in the special case of switching between mobile Views.

**Comment by JonFerraiolo** [comment] 2011-12-24 20:24
OK, I had a chance to test with latest build. The worst of the problems are fixed! I was actually able to follow the steps in this bug report without cursor jumping when using ScrollableView instead of View, and people shouldn't be using fixed with View anyway. Also, this was a more critical problem before we added support for the 'fixed' property in the Properties palette. 

@waynevicknair I suggest closing this bug and then open whatever remaining issues are left in different new issues, and my guess is that those issues could be addressed in subsequent releases. (I'd have to see the details - small chance there is still something we might want to address in M4)

**Closed as completed** 2011-12-24 22:44 UTC
Labels: Source Editors, Priority High
