### ISSUE TITLE
Opening a theme file from the File Explorer should be improved

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#551] opened 2011-06-17 16:40 UTC
@jmockler @jinsil
UI Review - Jun 10, 2011
Using Firefox 4.0

Currently when I go into the theme folder and search for a theme file to open, I must search for it at the same level at the CSS files.

We can improve this by setting the theme file as the parent in the tree, with the multiple CSS files as children of the theme file. This will help make it very obvious which files are CSS files, and which are theme files

**Comment by JonFerraiolo** [comment] 2011-06-17 18:34
Duplicate of #144

**Closed as completed by JonFerraiolo** 2011-06-17 18:34 UTC
