### ISSUE TITLE
Reloading R&C page doesn't save open pages

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1566] opened 2012-01-12 17:52 UTC
When I reload the R&C page, the review page I had open doesn't get reopened (as editors are done when reloading VE page).

Open pages should be saved and reopened when loading R&C page again.

@JonFerraiolo

**Comment by JonFerraiolo** [comment] 2012-01-12 18:00
Hopefully this will just fall out with the R/C merge because review sessions should just be additional editior tabs, right?

**Comment by waynevicknair** [comment] 2012-01-12 18:48
i believe that is correct target behavior. yes.

**Comment by JonFerraiolo** [comment] 2012-03-10 00:55
Dupe of #1817

**Closed as completed by JonFerraiolo** 2012-03-10 00:55 UTC
Labels: Review and Commenting, Priority Med
