### ISSUE TITLE
Session timeout logic not working

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2995] opened 2012-08-19 14:39 UTC
@childsb @peller 

I've been testing, taking a break, then returning to test some more, and the session has timed out, but I'm not seeing the "session timeout" user interface with the link back to the login page in all of the same situations as we had for M6. Three likely suspects:
1. Orion server isn't providing the same info that our previous server did
2. Our new async logic is confusing the checks we implemented in M6
3. Something changed in Dojo 1.8

@billreed63 - can you please do the initial investigation?

**Comment by billreed63** [comment] 2012-08-20 17:18
With Maqetta stand alone server we set the `MaxInactiveInterval` in Login.java and Tryit.java

```
session.setMaxInactiveInterval(IDavinciServerConstants.SESSION_TIMEOUT);

```

by default the time is set to 60 minutes
The client UserActivityMonitor retrieves this value by calling the KeepAlive command

```
public class KeepAlive extends Command {

    @Override
    public void handleCommand(HttpServletRequest req, HttpServletResponse resp, IUser user) throws IOException {

            HttpSession session = req.getSession(true);
            this.responseString =  "{MaxInactiveInterval:" + session.getMaxInactiveInterval() +"}";
           //Date d = new Date();
           //System.err.println("Poll: " + d);

    }
}

```

With the orion maqetta. Login.java is not called so we are not setting the `MaxInactiveInterval`  with the `IDavinciServerConstants.SESSION_TIMEOUT` 
value. It is getting set by orion somewhere to 14400 (4 hours) @childsb  do you know how/where the ``MaxInactiveInterval` gets set for orion?

**Comment by billreed63** [comment] 2012-08-20 20:02
The timeout value needs to be set to a lower value on the server 
-> @childsb

**Comment by childsb** [comment] 2012-08-20 21:10
I'm not sure where this is set in Orion.  It's not going through our login/logoff command anymore though, and probably out of our reach.

**Comment by JonFerraiolo** [comment] 2012-08-28 15:38
-> @billreed63

**Comment by billreed63** [comment] 2012-08-28 18:47
http://git.eclipse.org/c/orion/org.eclipse.orion.server.git/tree/bundles/org.eclipse.orion.server.configurator/src/org/eclipse/orion/server/configurator/ConfiguratorActivator.java 3:07  lin 116
2:42:36 PM: Bradley (Brad) Childs: theres where they do it in Orion
2:43:35 PM: Bradley (Brad) Childs: oh so it looks like we already have an activator
2:43:36 PM: Bradley (Brad) Childs: org.davinci.server.internal.Activator
2:43:42 PM: Bradley (Brad) Childs: probably could just stuff some code in there

**Comment by billreed63** [comment] 2012-08-28 21:21
I am certainly no expert on but it appears to me that the code in http://git.eclipse.org/c/orion/org.eclipse.orion.server.git/tree/bundles/org.eclipse.orion.server.configurator/src/org/eclipse/orion/server/configurator/ConfiguratorActivator.java hard codes the session timeout value in  `Acrivate.start()`
`properties.put(JettyConstants.CONTEXT_SESSIONINACTIVEINTERVAL, new Integer(4 * 60 * 60)); // 4 hours` 
As well as setting other server properties, the code then starts the server `JettyConfigurator.startServer("MasterJetty", properties); //$NON-NLS-1$`

So it would seem that anything we do in our activate would either replace all the server properties or be replaced when Orion starts the server.

I would thing the best way to resolve this issue is to ask Orion to add a parameter to web-ide.conf that users can use to set the session timeout `orion.session.MaxInactiveInterval=3600`

**Comment by billreed63** [comment] 2012-08-29 21:16
@childsb  is going to open an issue with orion to make the session timeout a settable parm for M8

**Comment by peller** [comment] 2012-09-20 13:47
see also logging added in #3234 (ffa3287ba836a2c8a40c41b6ce2c7a634c1a16a3) which should now be removed.

I logged a bug against Dojo for what looks like a back-compat problem: http://bugs.dojotoolkit.org/ticket/16023  In handleIoError, the object passed in for `reason` no longer has a status property.  It may be necessary to look at `reason.response.status` now instead.

**Comment by billreed63** [comment] 2012-09-20 13:53
Adam is correct, I have added code to check the reason.response.status and we now redirect to login on 401, 403

**Comment by jhpedemonte** [comment] 2012-10-01 20:05
-> M8

**Comment by JonFerraiolo** [comment] 2012-10-02 17:40
-> @jhpedemonte M8 Prio-High

**Comment by jhpedemonte** [comment] 2012-11-27 14:46
Back to @billreed63.

What remains to be done here?  Also, looks like we need to [remove logging code](https://github.com/maqetta/maqetta/issues/2995#issuecomment-8728984).

**Comment by billreed63** [comment] 2012-11-27 14:49
@childsb was going to open an issue with orion to make the session timeout a settable parm for M8, I do not know if that ever happened..

Back to @jhpedemonte

**Comment by jhpedemonte** [comment] 2012-12-12 03:11
-> M9

**Comment by JonFerraiolo** [comment] 2012-12-12 03:39
Note that during a demo I gave today I had to re-login a couple of times even though I was definitely actively involved making changes.

**Comment by billreed63** [comment] 2012-12-12 14:41
Was this locally? I would bet that the problem is in the way we handle xhr errors, when we get xhr errors we send the your to login.

**Comment by JonFerraiolo** [comment] 2012-12-12 15:35
yes, I was running from Eclipse

**Comment by peller** [comment] 2013-04-24 00:09
this might be helped by https://github.com/maqetta/maqetta/pull/3860  Should we consider this for M10?

**Comment by peller** [comment] 2013-04-24 00:10
-> @billreed63

**Comment by jhpedemonte** [comment] 2013-04-24 01:09
I haven't seen any issues around this.  @billreed63 or @JonFerraiolo ?

**Comment by billreed63** [comment] 2013-04-24 13:13
The timeout logic seems to be working well for me, I think we could close this one

**Closed as completed** 2013-04-24 13:15 UTC
Labels: Runtime, Server, Priority High, Severity 2

**Comment by JonFerraiolo** [comment] 2013-04-24 13:55
just after @billreed63 closed this issue - I haven't seen anything horrible on the session timeout front, but it does seem like sometimes the session closes too soon, and really our timeout period should be much longer, like a day. Many of the hot web sites allow you to go for days without having to reenter your credentials.

**Comment by peller** [comment] 2013-04-24 14:40
Among other things, the pull request
- eliminates an xhr on startup, taking a precious network connection during the bootstrapping process
- hooks the new io events for dojo/request, which may resolve the problem @JonFerraiolo mentions

**Comment by jhpedemonte** [comment] 2013-04-24 16:46
I'm worried about taking @peller's fix this late.  But if it fixes this issue, might be worthwhile.

> the session closes too soon, and really our timeout period should be much longer, like a day.

I believe Orion has a 4 hour timeout (right?).  Why do we go with 1 hour?  Let's at least follow Orion's lead.
