### ISSUE TITLE
Incorrect font appears

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1451] opened 2012-01-04 16:56 UTC
while testing the theme editor i selected the ComicSans font from the font drop down list in the properties palette. the font on the selected button changed; however, the font that appeared was not ComicSans. i don't know which font it was.

Steps:
1) clone the claro theme and call the new theme myclaro. this will open the theme editor.
2) select the button widget in the theme editor
3) select the font properties in the properties palette
4) click the drop down menu for font-family and select ComicSans

Result: the button's font will change, but not to ComicSans

**Comment by peller** [comment] 2012-01-04 17:00
@JonFerraiolo 

@waynevicknair, do you have a comicsans font on your system?  I don't think there's a way to make font name portable across operating systems without providing an ordered list, then it's really not a font list anymore but a list of preferences.

**Comment by JonFerraiolo** [comment] 2012-01-04 17:19
There very well might be bugs in this area.

Just a note: Our list of fonts in the Properties palette comes from various web sites that provide a list of "standard web fonts" that are available by default in browsers on a cross-platform basis (where I believe cross-platform means Windows and Mac). Because Mac and Windows have different fonts by default, there is some aliasing going on where the font-family value because a list of font names in some cases because the same font (more or less same glyphs) has different names on different systems.

**Comment by JonFerraiolo** [comment] 2012-01-04 17:44
@billreed63, @childsb 

I did some more poking around. Reassigning to @billreed63 because I wonder if there is a theme metadata design issue that is throwing a wrench in the works. We are putting 'font-family' on element.style for the root node of Button (which seems like the right thing to do), but an interior subnode of Button has 'font:inherit', which causes the inherited value of the 'font' shorthand to be used, which due to shorthand processing wipes out the 'font-family' inheritance.

I can think of a few options for addressing this problem, but they are all ugly.
- The easiest thing to do from a Maqetta perspective would be if Dojo/Dijit would change the dijitReset definition from `font:inherit` to `font:inherit; font-family:inherit; font-size:inherit; ...`. I think that would work in this case, but I can imagine resistance from the Dojo guys because the same approach would be needed for all shorthands that are set by dijitReset, and this would cause extra runtime processing and memory.
- On the Maqetta side, for particular widgets, we could stuff in the 'font' shorthand property instead of 'font-family' and other specific font properties, triggered by yet another flag in the theme metadata that says for this particular widget (Button) for this particular property (font-family, etc.) we need to inject the shorthand.

**Comment by waynevicknair** [comment] 2012-01-04 18:29
@peller yes, i have comicsans font on my machine.

**Comment by jhpedemonte** [comment] 2012-03-15 02:41
-> M6

**Comment by billreed63** [comment] 2012-03-15 13:02
I have a fix for this just doing some final testing...

The issue is that the Font combobox is not returning the `value` from the FontDataStore ComboBox only returns the `searchAttrbute` in this case name so when the user selects a font ie Comic Sans the value retrieved from the combo box is the name Comic Sans not the value 'Comic Sans MS',cursive

**Comment by billreed63** [comment] 2012-03-15 13:51
dojo.form.ComboBox when used with a data store only uses the search attribute for   setting the Name and Value fields of the comboBox in the case of FontDataStore the  searchAttribute is name. But we want the to display to the user the name feild from the  data store and use the date store item value field to set the css font. So we override the default behaviors of the getters and setters.

**Closed as completed** 2012-03-15 13:53 UTC
Labels: Properties View, Priority Med

**Comment by billreed63** [comment] 2012-03-15 18:06
more info on why we have to use this solutions in #1915
