### ISSUE TITLE
Publish review invitations on maqetta-test (Orion 1.0) - server errors

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3792] opened 2013-03-04 19:41 UTC
seeing this in logs: 

```
Caused by: com.sun.mail.smtp.SMTPAddressFailedException: 550 5.1.1 <B>... User unknown

        at com.sun.mail.smtp.SMTPTransport.rcptTo(SMTPTransport.java:1145)
        ... 57 more
```

so looks like it's coming in with your user name ("B") instead of your email

**Comment by jhpedemonte** [comment] 2013-03-04 22:21
Most likely this is a dupe of #3790.  I'll retest once that issue is fixed.

**Closed as completed** 2013-03-05 02:15 UTC
Labels: Review and Commenting, Priority High, Priority Critical, Severity 2
