### ISSUE TITLE
multi widget DnD order should be dependent on document order

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#963] opened 2011-09-09 03:19 UTC
description borrowed from #789:

Steps to recreate:
- Create new HTML file.
- Add **Button**, **TextBox**, and **ComboBox** to page.
- Open **split view** for source editor.
- Add `<div></div>` as first element in `<body>` (above the other widgets).
- Cmd+ Click on ComboBox, TextBox and Button (to select the 3 widgets).
- Drag the 3 widgets up into the DIV.

Depending on the order in which you select the widgets, you'll see them appear in the reverse of that order.  They should appear in the order in which they appear in the document.

@JonFerraiolo

probably for M4

**Comment by JonFerraiolo** [comment] 2011-09-09 15:23
I moved to M4

**Comment by JonFerraiolo** [comment] 2011-12-12 22:37
Changed to Priority-Low for M4, wouldn't be end of world to defer to M5.

**Comment by JonFerraiolo** [comment] 2012-01-01 18:39
Reassigned to me, pushed to M5. I'm pretty sure the problem is that the ReparentCommand or whatever is being used doesn't support an "index" or position value and the onExtentChange would need to use that when doing multiple selection reparenting. I'll be rewriting sections of the drag/drop logic in flow layout during M5.

**Comment by peller** [comment] 2012-01-02 03:53
Right now, I think it's as simple as the fact that there's an ordered list (the selection) and the paste operation simply iterates through that list -- note that the paste order is identical to the selection.  So the logic that actually determines the proper document order is what I think needs to happen here.  Perhaps additional work to reparent or insert the widgets would need to follow.

**Comment by JonFerraiolo** [comment] 2012-03-13 23:26
Dupe of #1445, closing.

**Closed as completed by JonFerraiolo** 2012-03-13 23:26 UTC
Labels: Visual Editor, Bug, Priority Med
