### ISSUE TITLE
Annotations not displayed correctly - xpath compare problem

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3354] opened 2012-09-11 04:56 UTC
@jhpedemonte discovered an xpath compare problem in the review code, makes it so that sometimes annotations don't show when they should

**Comment by jhpedemonte** [comment] 2012-09-11 14:42
Scenario:
1. Create a mobile app which consists of a single View and some widgets within that view.
2. Create a review for this page.
3. Add a comment to the review.  Use one of the annotations (i.e. arrow or rectangle) and add it on top of the View.
4. Click **Submit** on the review comment.  Notice that the annotation disappears.

Before (3), `getCurrentScenes()` in "davinci/review/editor/Context" creates XPaths like **"/html/body/div"**.  This is because there is only a single DIV that is the child of BODY.

After (3), however, the annotation DIV resides as a child of BODY as well, so there are now 2 DIVs.  That means that the XPaths in `getCurrentScenes()` now look like **"/html/body/div[1]"**.  The rest of the code in "davinci/review/editor/Context" does simple string compares of the XPaths, and those fail.  For that reason, the annotation is hidden.

---

Possible solutions:
1. In the XPath creation, always add the index (i.e. "/html[1]/body[1]/div[1]"), even if there is only one of that element.  This could be an option to the `getXPath()`.
2. Create a compare function, wherein an element without an index is considered equivalent to the first index:  "div" === "div[1]".

But that's for M8.

**Comment by JonFerraiolo** [comment] 2012-09-14 00:59
@jhpedemonte is this a candidate for 7.0.1?

**Comment by jhpedemonte** [comment] 2012-09-14 17:08
Yes.  -> 7.0.1

What's your take on my proposed solutions?  Ideally, the XPath code would ignore annotations.  Since this is in R&C, we don't have access to the model, correct?

Perhaps we can create an adapter to XPathUtils that ignores annotations, when generating the XPath?  Although that might create issues if the XPath is actually used to select an element on the page.

**Comment by aerwin** [comment] 2012-09-19 15:20
--> @aerwin for investigation

**Comment by aerwin** [comment] 2012-09-19 17:10
@jhpedemonte @JonFerraiolo 

Without being totally versed in this area, my gut feeling is that it's best for `XPathUtils.getXPath` to return consistent results. So, @jhpedemonte 's first proposal seems like the best.

And, indeed, I was able to fix the problem at hand with a relatively simple fix modification (marked below with `AWE TODO`):

```
getXPath: function(node, Adapter) {
        function _get(path, elem) {
            var tag = elem.name(),
                parent = elem.parent();
            if (parent) {
                var idx = elem.index();
                if (idx) {
                    tag += '[' + idx + ']';
                } else {
                    tag += '[' + 1 + ']'; //AWE TODO
                }
                path = tag + (path ? '/' + path : '');
                return _get(path, parent);
            }
            return '/' + tag + '/' + path;
        }

        Adapter = Adapter || DOMAdapter;
        var elem = new Adapter(node);

        return _get('', elem).toLowerCase();
    },
```

I also confirmed that this works with a mobile page with multiple scenes and multiple annotations per scene. So, I feel confident that this is a good fix for R&C.

Do you guys have thoughts if this might have other ramifications across Maqetta? I see `getXPath` is used in a number of places. `SelectTool` is one example, and I don't see any obvious problems with selection in the page editor after my change.

**Comment by JonFerraiolo** [comment] 2012-09-19 17:21
@aerwin - I had come to the same conclusions. My feeling is that we should commit/push this fix and explicitly test the parts of the code that use XPath before shipping 7.0.1.

**Comment by aerwin** [comment] 2012-09-19 18:40
Closing with above commit.

**Closed as completed by aerwin** 2012-09-19 18:40 UTC
Labels: Review and Commenting, Priority High, Severity 2

**Comment by JonFerraiolo** [comment] 2012-09-27 01:52
verified in latest build that the problem has been fixed
