### ISSUE TITLE
Properties palette2 - get JS exception dropping calendar

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#579] opened 2011-06-20 18:29 UTC
get: "TypeError: Result of expression 'this.value' [null] is not an object." 
earlier in davinci.ve.widget._getData() we request a the value of the property named "value" on the calendar widget we are trying to add which returns null and causes the exception later in the call chain.

**Comment by JonFerraiolo** [comment] 2011-06-20 18:44
Dupe of #458

**Closed as completed by JonFerraiolo** 2011-06-20 18:44 UTC
Labels: Visual Editor, Bug
