### ISSUE TITLE
Context._restoreStates: this._loadFileStatesCache missing

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3048] opened 2012-08-22 22:33 UTC
Seeing this intermittently when Maqetta comes back up after I reload the browser page... not sure if it's causing any real trouble, but I see a red screen of death flicker in and out out of the current editor, so looks kind of bad.

```
Context._restoreStates: this._loadFileStatesCache missing davinci.js:48360
_21c8._restoreStates davinci.js:48360
_21c8.activate davinci.js:47416
_564.around.advice dojo.js:6950
_55f.(anonymous function)._564 dojo.js:6934
_1ba0._connectCallback davinci.js:38888
_21c8._continueLoading davinci.js:48007
(anonymous function) davinci.js:47966
runFactory dojo.js:1081
execModule dojo.js:1210
checkComplete dojo.js:1245
guardCheckComplete dojo.js:1225
checkComplete dojo.js:1240
onLoad dojo.js:1295
detectReady domReady.js:22
```

Making prio high so we get some deeper assessment for M7...

**Comment by JonFerraiolo** [comment] 2012-08-22 23:24
I think I'm closing in on this one. I can reproduce with 2 HTML editors open, and hitting browser refresh. The RSOD happens with one of the HTML files, and then gets fixed up with the second one. The `window[loading...]` logic gets hit twice for the same document.

**Comment by JonFerraiolo** [comment] 2012-08-23 02:05
Sending to @peller. 

To reproduce, simply have two open documents and then do a browser refresh. What's happening is that the following logic at Context.js:987:

```
            window["loading" + this._id] = function(parser, htmlUtil) {
                var callbackData = this;
                try {
                    var win = windowUtils.get(doc),
                        body = (this.rootNode = doc.body);
...
```

gets invoked twice, one for each document, but the `this` variable in both cases is the second document. For instance, if you have file1.html and file2.html open, and hit browser refresh, then if you look at the `this` object for both times into that logic, in both cases the `this` object is pointing to file2.html. This messes up downstream logic.

I'm not sure why this logic worked in M6 and isn't working in M7. Maybe we have a different issue where in M7 we have lost the lazy loading logic from M6? Nevertheless, we should find a way to make the `window["loading" + this._id] = function...` logic is operating on the correct `this` object. I figure our JavaScript whiz @peller can easily figure out how to make that happen. Personally, I'm scratching my head because the `window["loading" + this._id] = function...` has a `bind(this)` at the end. Must be some crazy closure behavior that's biting us.

**Comment by JonFerraiolo** [comment] 2012-08-23 02:34
@peller can't reproduce but pointed out how the `window["loading" + this._id] = function` logic gets invoked (via newfile.template.html). I'm taking this one back now.

**Closed as completed** 2012-08-23 03:07 UTC
Labels: Visual Editor, Priority High, Severity 3

**Comment by jhpedemonte** [comment] 2012-08-23 03:38
Why not just declare `var contextCount = 0;` inside the closure, but still outside of the `declare()`?  Then:

```
this._id = "_edit_context_" + contextCount++;
```

**Comment by JonFerraiolo** [comment] 2012-08-23 03:58
> Why not just declare var contextCount = 0; inside the closure

See  4960a5a512
