### ISSUE TITLE
ScrollableView - child widgets are mispositioned in page editor

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1577] opened 2012-01-12 20:36 UTC
@peller 
- New HTML File - iphone
- Add a ScrollableView
- Add a Heading

Result=> Heading is shifted up by several pixels. Selection doesn't align with widget, but selection is probably correct.
- Add a RoundRectList

Result=> Similar problem

**Comment by jhpedemonte** [comment] 2012-03-09 06:01
This is caused by the [fix](https://github.com/maqetta/maqetta/commit/28ab8fb9f1a6dd4809789ea26b4d1925a1c84c8d) to #1144.

**Comment by jhpedemonte** [comment] 2012-03-09 06:16
@JonFerraiolo, I think we need a better fix for #1144.

I'm a bit confused as to why the scrollbars appear at all.  I too see that if I disable `margin` for the RoundRect, then the scrollbars disappear.  But the height of the View is the same in both cases (480px).  So why do the scrollbars show?

(I no longer see `-webkit-margin-before: 1em;` -- might have changed in a Dojo update?)

**Comment by jhpedemonte** [comment] 2012-03-09 06:38
Notice this isn't an issue with ScrollableView.  Something I noticed in the past is that View (by default) is not 100% height, but ScrollableView is.  If I disable the `height: 100%` rule on `body` added by app.css, then the scrollbar disappears when using View.  But still doesn't explain why this isn't an issue with ScrollableView.

**Comment by jhpedemonte** [comment] 2012-03-09 06:43
Answered my own question: difference is that ScrollableView has `overflow: hidden` (at least for the code that Maq produces).

**Comment by jhpedemonte** [comment] 2012-03-09 07:05
Load up this [page](https://dl.dropbox.com/u/257742/dojoxMobileViews-1577.html), which is a stripped down version of the file created in Maqetta (I simply removed the Maqetta-specific files: app.css, States.js, maqetta.js).  Notice no scrollbars.

Now, in the inspector, add `height: 100%` to both _html_ and _body_ elements; now we get a scrollbar.  This simulates what we are doing with app.css inside of Maqetta.

---

Also noticed that when you add a lot of widgets, such that View is taller than viewport, scrolling has no effect on the content (even though scrollbar moves up and down).

**Comment by jhpedemonte** [comment] 2012-03-09 18:43
Closing this.  Further issues handled in #1892.

**Closed as completed by jhpedemonte** 2012-03-09 18:43 UTC
Labels: Model, Visual Editor, Priority High
