### ISSUE TITLE
Can not add line or rectangle to review comment

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3687] opened 2013-01-23 18:29 UTC
I have created two low fi sketch pages the pages are below:
file9.html

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "clipart/Browser",
  "clipart/VScrollBar",
  "shapes/Rectangle",
  "shapes/Text",
  "clipart/Rss",
  "clipart/Twitter",
  "clipart/Facebook",
  "clipart/ShoppingCart",
  "dijit/form/TextBox",
  "clipart/Search",
  "dijit/MenuBar",
  "dijit/PopupMenuBarItem",
  "dijit/MenuItem",
  "dijit/Menu"
]);
</script>
<style>@import "themes/sketch/sketch.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="absolute" data-maq-comptype="sketchlofi" data-maq-ws="collapse" data-maq-appstates="{'states':[]}" id="myapp">
 <img data-dojo-type="clipart.Browser" style="position: absolute; z-index: 900; width: 952.953125px; height: 551.390625px; left: 12.046875px; top: 17px;"></img>
 <img data-dojo-type="clipart.VScrollBar" style="position: absolute; z-index: 900; left: 945px; top: 96px; height: 445px;"></img>
 <div data-dojo-type="shapes.Rectangle" style="border: 3px solid black; position: absolute; z-index: 900; left: 24px; top: 101px; width: 908px; height: 42px;"><span data-dojo-type="shapes.Text" style="position: absolute; z-index: 900; font-size: 18px; left: 35px; top: 9px;">Company Name here</span>
<img data-dojo-type="clipart.Rss" style="position: absolute; z-index: 900; left: 879px; top: 13px;"></img>
<img data-dojo-type="clipart.Twitter" style="position: absolute; z-index: 900; left: 857px; top: 13px;"></img>
<img data-dojo-type="clipart.Facebook" style="position: absolute; z-index: 900; left: 831px; top: 13px;"></img>
<img data-dojo-type="clipart.ShoppingCart" style="position: absolute; z-index: 900; left: 522px; top: 13px;" onclick="location.href='cart.html'"></img>
<input type="text" data-dojo-type="dijit.form.TextBox" style="position: absolute; z-index: 900; left: 568px; top: 7.5px;"></input>
<img data-dojo-type="clipart.Search" style="position: absolute; z-index: 900; left: 761px; top: 13.5px;"></img>
</div>
<span data-dojo-type="dijit.MenuBar" tabIndex="0" style="position: absolute; z-index: 900; left: 24px; top: 149px; width: 902px;"><span data-dojo-type="dijit.PopupMenuBarItem" label="Menu 1" iconClass="dijitNoIcon"><span data-dojo-type="dijit.Menu"><span data-dojo-type="dijit.MenuItem" label="Menu Item 1.1"></span><span data-dojo-type="dijit.MenuItem" label="Menu Item 1.2"></span>
 </span>
 </span><span data-dojo-type="dijit.PopupMenuBarItem" label="Menu 2" iconClass="dijitNoIcon"><span data-dojo-type="dijit.Menu"><span data-dojo-type="dijit.MenuItem" label="Menu Item 2.1"></span><span data-dojo-type="dijit.MenuItem" label="Menu Item 2.2"></span>
 </span>
 </span>
 </span></body>
</html>

```

cart.html

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "clipart/Browser",
  "clipart/VScrollBar",
  "shapes/Rectangle",
  "shapes/Text",
  "clipart/Rss",
  "clipart/Twitter",
  "clipart/Facebook",
  "clipart/ShoppingCart",
  "dijit/form/TextBox",
  "clipart/Search",
  "dijit/MenuBar",
  "dijit/PopupMenuBarItem",
  "dijit/MenuItem",
  "dijit/Menu",
  "dijit/layout/ContentPane",
  "clipart/Trash",
  "clipart/Home"
]);
</script>
<style>@import "themes/sketch/sketch.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="absolute" data-maq-comptype="sketchlofi" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
 <img data-dojo-type="clipart.Browser" style="width: 952.953125px; height: 551.390625px; position: absolute; z-index: 900; left: 38px; top: 37px;"></img>
 <img data-dojo-type="clipart.VScrollBar" style="height: 445px; position: absolute; z-index: 900; left: 971px; top: 116px;"></img>
<span data-dojo-type="dijit.MenuBar" tabIndex="0" style="width: 902px; position: absolute; z-index: 900; left: 50px; top: 169px;"><span data-dojo-type="dijit.PopupMenuBarItem" label="Menu 1" iconClass="dijitNoIcon"><span data-dojo-type="dijit.Menu"><span data-dojo-type="dijit.MenuItem" label="Menu Item 1.1"></span><span data-dojo-type="dijit.MenuItem" label="Menu Item 1.2"></span>
</span>
</span><span data-dojo-type="dijit.PopupMenuBarItem" label="Menu 2" iconClass="dijitNoIcon"><span data-dojo-type="dijit.Menu"><span data-dojo-type="dijit.MenuItem" label="Menu Item 2.1"></span><span data-dojo-type="dijit.MenuItem" label="Menu Item 2.2"></span>
</span>
</span>
</span><div data-dojo-type="shapes.Rectangle" style="border: 3px solid black; width: 908px; height: 42px; position: absolute; z-index: 900; left: 50px; top: 121px;">
<span data-dojo-type="shapes.Text" style="position: absolute; z-index: 900; font-size: 18px; left: 36px; top: 9px;">Company Name</span><img data-dojo-type="clipart.Rss" style="position: absolute; z-index: 900; left: 879px; top: 13px;"></img>
<img data-dojo-type="clipart.Twitter" style="position: absolute; z-index: 900; left: 857px; top: 13px;"></img>
<img data-dojo-type="clipart.Facebook" style="position: absolute; z-index: 900; left: 831px; top: 13px;"></img>
<input type="text" data-dojo-type="dijit.form.TextBox" intermediateChanges="false" trim="false" uppercase="false" lowercase="false" propercase="false" selectOnClick="false" style="position: absolute; z-index: 900; left: 568px; top: 7.5px;"></input>
<img data-dojo-type="clipart.Search" style="position: absolute; z-index: 900; left: 761px; top: 13.5px;"></img>
<img data-dojo-type="clipart.Home" style="position: absolute; z-index: 900; left: 507px; top: 13.5px;" onclick="location.href='file9.html'"></img>
</div>
<div data-dojo-type="dijit.layout.ContentPane" title="Pane" doLayout="false" style="position: absolute; z-index: 900; height: 300px; left: 163px; top: 219px; width: 583px;"><span data-dojo-type="shapes.Text" style="font-size: 14px; position: absolute; z-index: 900; left: 41px; top: 39px;">Dog food</span><span data-dojo-type="shapes.Text" style="font-size: 14px; position: absolute; z-index: 900; left: 41px; top: 85px;">Dog bed</span>
<img data-dojo-type="clipart.Trash" style="position: absolute; z-index: 900; left: 511px; top: 42px;"></img>
<img data-dojo-type="clipart.Trash" style="position: absolute; z-index: 900; left: 511px; top: 85px;"></img>
</div>
</body>
</html>

```

file9.html has a cart in the company banner when the user clicks on the cart icon the cart.html page is loaded

I then created a review for file9.html, then the review clicks on the cart icon the review tab contents change to the cart.html but if I add a comment I am unable to add an arrows or boxes form the reviewers tool palette.

**Comment by JonFerraiolo** [comment] 2013-01-23 20:49
The correct fix for this might be having the R/C code intercept the hyperlink command and replace it with a call to open the other file as a new review editor.

**Comment by JonFerraiolo** [comment] 2013-02-04 22:27
-> M10

**Comment by JonFerraiolo** [comment] 2013-02-06 18:34
Closing this as a dupe of a newer issue I created today: #3737

**Closed as completed by JonFerraiolo** 2013-02-06 18:34 UTC
Labels: Review and Commenting, Priority High, Severity 3
