### ISSUE TITLE
Preview in browser should reuse same preview window

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#163] opened 2011-05-03 21:56 UTC
Once upon a time, the preview-in-browser function for a given HTML file (e.g,
file1.html) would reuse the same browser tab/window if you did a second preview
for the same file. Now, each time you click on the preview-in-browser function,
you get a new browser tab/window for each different preview. I think it would
be better to reuse the existing browser tab/window if it exists.

I forget how I implemented the reuse logic before. window.name? target?

**Comment by jhpedemonte** [comment] 2011-06-16 02:57
Duplicate of #1.

**Closed as completed by jhpedemonte** 2011-06-16 02:57 UTC
Labels: Visual Editor, Bug, Priority Low
