### ISSUE TITLE
Browser refresh: review editors for other people's reviews don't reopen

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2012] opened 2012-03-27 15:50 UTC
@aerwin, @waynevicknair 

If I open two review editors, one for a review that I created, and another for a review that someone else created, so that I have two review editors open, and then I hit browser refresh, only the review that I created comes up after the browser refresh occurs.

I think the reason for this is clear. Here is the workbench settings file that came down from the server:

{"editors":[".review/snapshot/20120327102648/bbb/Muestra1.html",".review/snapshot/20120327102744/eproj3/WebContent/Sample1.html"],"project":"eproj3","activeEditor":".review/snapshot/20120327102648/bbb/Muestra1.html"}

As you can see, there is no indication about which user/workspace for the given review, so Maqetta is assuming that it should look in the current user's `.review` folder.

**Comment by aerwin** [comment] 2012-04-13 19:00
@JonFerraiolo Are you still seeing this? I can't replicate in my local environment.

**Comment by JonFerraiolo** [comment] 2012-04-13 20:08
reassigning to me to test and make sure this has gone away

**Comment by JonFerraiolo** [comment] 2012-05-15 20:33
-> @aerwin could you please examine this one? (cc @childsb)

I just reproduced this when testing latest code on macwayne2, and I think I found the culprit in the sources. Look at Workbench.js:178 (in initializeWorkbenchState()):

```
        for (var i=0;i<state.editors.length;i++) {

            var isReviewRes = isReview(state.editors[i]);
            if(isReviewRes){
                var reviewProject = getReviewProject(state.editors[i]);
                if(reviewProject!=project) continue;
```

Since other people's reviews are in a different project pretty much by definition, we aren't reopening other people's reviews.

Can we change the code to open other people's reviews (even though they are in a different project)? You know, safely at this late point in M6 cycle?

**Comment by aerwin** [comment] 2012-05-16 15:57
@JonFerraiolo So, I must be missing something in your scenario because I still can't reproduce. :)

In the screenshot below I have reviews open from userA (Sample1.html.rev) and userB (Sample2.html.rev), and I can keep hitting refresh and the editors continue to reopen.

![Screenshot](http://i.imgur.com/LWriv.png)

Any ideas what I'm missing?

**Comment by aerwin** [comment] 2012-05-16 16:03
Ok... guess you ran on macwayne... let me try that. My attempt was from Eclipse. So, not sure what would be different.

**Comment by aerwin** [comment] 2012-05-17 01:55
When I ran on macwayne earlier today, I was able to replicate this problem. BUT, I realized I was using reviews created a long time ago. I think well before @childsb 's changes to the review directory structure.

I then created a brand new review. I also created a brand new user. In that new user's account, I could open the new review and it stayed open during browser refresh.

So, @JonFerraiolo I created another review and I just invited you to it. I'd be curious if you can open it and have it stay open during browser refresh.

**Comment by JonFerraiolo** [comment] 2012-05-17 13:51
Two problems when I tried to open new review:
- Once I got past the following bullet's problems, when I logged into the staging server, the new review invitation opened automatically, but if I hit browser refresh, the review editor does not reopen
- The invitation's link does point to the staging server, but somehow or other the redirect logic on the staging server has maqetta.org redirect URLs, so (in order to login) I was taken to maqetta.org login page rather than the staging server login page. That's probably OK for short-term since one would expect that everything will work OK once we post on maqetta.org, but I logged #2313 in case we can fix that.

**Comment by aerwin** [comment] 2012-05-18 19:13
@JonFerraiolo invited me to a review on Macwayne, and I finally saw the problem (e.g., the review he created would not stay open for me between browser refreshes). He happened to mention he was using an Eclipse project.

With that new tidbit of info, I've finally been able to replicate in my local development environment. It seems reviews created from  regular projects stay open on reload, but reviews created from an Eclipse project do not. In addition, it seems if you are currently working in an Eclipse project that other people's reviews will not stay open even if those reviews were created from regular projects.

**Comment by aerwin** [comment] 2012-05-18 19:23
Ok, it's also looking like it doesn't matter who creates the review (or if the project is an Eclipse based project). E.g., if I'm working in `project1` and have opened a review for a file in another one of my projects (say `project2`), then if I reload the page the review for the other project doesn't reopen. But, if I have a review open for a file in `project`' will reload.

**Comment by aerwin** [comment] 2012-05-18 20:05
Fixed with above commit.

**Closed as completed by aerwin** 2012-05-18 20:05 UTC
Labels: Server, Review and Commenting, Priority High

**Comment by childsb** [comment] 2012-05-21 15:43
one issue to note--

this fix will cause any review a user has open to open for every project.
