### ISSUE TITLE
Rendering corrects itself after switching to source editor

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2602] opened 2012-06-21 00:41 UTC
I'm noticing this with all the latest pulled into my Eclipse dev environment...

Here's the simplest example:
1. New HTML file
2. Drag button onto canvas
3. Open source pane and rendering of button changes (and I think changes to the correct rendering)

I first noticed it with a slightly more complicated example involving HTML tables:
1. New HTML file
2. Drag HTML table onto canvas
3. Double-click first cell and enter some text (say "test text")
4. Select the table and change cellpadding to 25 (and note nothing happens)
5. Open source pane and see cellpadding get applied

And, yet another example involving table headers:
1. while source pane from last scenario is still open
2. add a row of table headers immediately after the TBODY element and see TH's properly rendered in page editor

```
<tr>
       <th>
         test header</th>
       <th>
         ⁠</th>
     </tr>
```
1. Reload Maqetta and notice styling reverts
2. Open source pane again and notice TH's get rendered properly again

**Comment by jhpedemonte** [comment] 2012-06-21 03:14
@JonFerraiolo @peller 

Is this a document.css related issue?  Is that style script not initially set?

**Comment by JonFerraiolo** [comment] 2012-06-21 03:46
Assigning to me

**Comment by aerwin** [comment] 2012-06-25 18:07
@JonFerraiolo I don't see this in the Sprint 3 Plan, but I'd like to petition it be handled sooner rather than later. I'm pushing on this in particular because of the table related examples (which make the new Table Input dialog) seem broken (see examples above). And, per and #2567, it appears to affect the preview in the Table Input Dialog as well as requiring the user to open the source pane after clicking ok in the Table Dialog to see certain properties take affect.

**Comment by JonFerraiolo** [comment] 2012-07-09 21:37
Closing this as a dupe of these bugs:
- #2513 document.css sometimes not there for preview-in-browser
- #2541 document.css missing from one of our themes

Actually, the initial rendering of the Button is correct, and the rendering after bringing up split view is wrong. The key difference is that when you first drop the Button, document.css is included in the document, but when split view shows, after a 1 second pause, the page is reparsed, and the reparsing causes document.css to get removed from the rendered page. You see, document.css must be present in order to have the proper font properties that the claro designers intended.

**Comment by JonFerraiolo** [comment] 2012-07-09 21:38
On second thought, reopening and assigning to @billreed63 as a reminder when he gets to the document.css fixes.

**Comment by aerwin** [comment] 2012-07-09 21:46
@JonFerraiolo So, you'd say the table rendering issues I mentioned are correct (before reparse) as well? I guess meaning claro mucks around with them?

**Comment by JonFerraiolo** [comment] 2012-07-09 23:01
See #2709.

With tables, document.css has the opposite effect. As mentioned in #2709, document.css adds style rules for all TD and TH elements that set padding to zero. These style rules have higher precedence than the "inherited" value from the cellpadding property on the TABLE element. As a result, if you use the table SmartInput to set cellpadding to 25 at document creation time (when document.css happens to be present in our current implementation), then document.css overrides cellpadding. But when split view comes up (and you wait 1 second), the page re-renders, which (in our current implementation) does not include document.css, so cellpadding of 25 will show. But we need document.css to work in all cases. Therefore, I created #2709.

**Comment by doronrosenberg** [comment] 2012-08-02 19:37
Was this supposed to be assigned to me? I thought someone else wad doing document.css work already

**Comment by JonFerraiolo** [comment] 2012-08-02 23:38
Can @doronrosenberg, @peller and @billreed63 figure out who should own this issue?

**Comment by billreed63** [comment] 2012-08-13 20:59
I don't understand what this issue is trying to describe as the problem, currently document.css is being applied as soon as the first widget is added to the document. document.css stays loaded in the document as long as not dojox.molbile widgets are present.

When I DnD a table I see that document.css is added to the head and the style of the table is from document.css as @JonFerraiolo  describes. 

I have done a far bit of work on loading and unloaded document.css, so I think I resolved this issue with that work also.

**Closed as completed by billreed63** 2012-08-13 20:59 UTC
Labels: Visual Editor, Priority High, Severity 2
