### ISSUE TITLE
spin wheel contents have quotes and brackets

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#3156] opened 2012-08-28 20:50 UTC
drop a mobile spinwheel on a page and preview.  the data A, B, C, etc. have stray characters.  @ykami points out:

the array syntax has been changed to align with dojo.parser.
http://livedocs.dojotoolkit.org/dojox/mobile/differences-17-18#dojox-mobile-parser

If your SpinWheel encounters the deviceTheme problem, its label text does not align center and you cannot spin the slots well. This is because layout calculation at initialization time fails without styles for SpinWheel.

**Comment by jhpedemonte** [comment] 2012-08-28 21:30
Dupe of #1484?

**Comment by doronrosenberg** [comment] 2012-08-28 22:18
@peller @ykami If that is true, why does http://download.dojotoolkit.org/release-1.8.0/dojo-release-1.8.0/dojox/mobile/tests/test_SpinWheel-custom.html still use label="[]"?

**Comment by doronrosenberg** [comment] 2012-08-28 22:27
fixed by f1c4107e78dd218a87556b243b0006215c898621

**Closed as completed by doronrosenberg** 2012-08-28 22:27 UTC
Labels: Bug, Priority Med, Mobile, Severity 3

**Comment by ykami** [comment] 2012-08-29 02:25
> why does http://download.dojotoolkit.org/release-1.8.0/dojo-release-1.8.0/dojox/mobile/tests/test_SpinWheel-custom.html still use label="[]"?

fair question.
In that test case, data-dojo-props is used to pass the array value. In this case, you need to give it in the correct json syntax. On the other hand, when you pass it through an html attribute, i.e. the labels attribute in this case, you need to give something like "A,B,C,D,E". This is how dojo.parser behaves, and dojox.mobile.parser is following this dojo.parser's behavior.
