### ISSUE TITLE
themesets add/remove theme icon is doubled

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#2984] opened 2012-08-16 21:55 UTC
In FireFox the + and - buttin within the theme sets dialog is doubled.  

Recreate:
1) launch maqetta
2) bring up the theme sets dialog (click on the gears icon, and select "theme sets")
3) Under the Them Sets box on the left notice that theres
+
Triangle shape

for the plus

and 
- -

for the minus icon

**Comment by JonFerraiolo** [comment] 2012-08-16 23:08
-> me with Prio-High to investigate. Probably a regression due to my CSS hacking

**Comment by JonFerraiolo** [comment] 2012-08-17 17:23
Fixed by checkins I did last night.

**Closed as completed by JonFerraiolo** 2012-08-17 17:23 UTC
Labels: Priority High
