### ISSUE TITLE
Cannot create New HTML file in nested folder

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1291] opened 2011-11-30 05:16 UTC
@JonFerraiolo

create new folder called "folder1"    Select it and choose file->new HTML file.  Where does not get set based on the selection (maybe ok)  Select folder1 and use the default filename of "file1.html".  Click OK.  An alert says folder already exists.  And then the following stack trace appears in the console:

```
Uncaught TypeError: Cannot call method 'getChild' of undefined
dojo.mixin.createResourcesystem/resource:71
require.cache.davinci/ui/Resource.dojo.mixin.newHTML._94fdavinci/davinci:12049
(anonymous function)davinci/davinci:4567
_312dojo.js:3801
_421.(anonymous function)dojo.js:5337
require.cache.davinci/ui/widgets/NewFile.dojo.declare._okButtondavinci/davinci:31381
_312dojo.js:3797
_421.(anonymous function)dojo.js:5337
require.cache.dijit/form/_ButtonMixin._1a8._onClickdavinci/davinci-common:2035
_260dojo.js:2641
require.cache.dijit/form/Button._126._onClickdavinci/davinci-common:1378
_312dojo.js:3797
require.cache.dijit/_OnDijitClickMixin._1e3
```

**Comment by childsb** [comment] 2011-12-14 21:48
I believe this is a dupe of (or very similar to) a bug I fixed a few days ago.  I double checked and can't recreate so closing.

**Closed as completed by childsb** 2011-12-14 21:48 UTC
Labels: Bug, Priority High
