### ISSUE TITLE
Preview doesn't work if choose custom theme from New HTML File

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1322] opened 2011-12-02 05:13 UTC
- New HTML File
- Choose options Mobile, Blackberry, and click on pencil icon and set the theme for all mobile devices to "custom"
- Add a View and a Heading
- Save
- Preview

Result=> Nothing shows in preview - silhouette is there but nothing is inside

Note that if you accept the Blackberry theme from the New HTML file dialog and then switch theme in the page editor, then preview will work fine.

**Comment by billreed63** [comment] 2011-12-02 15:58
when the file is created it is created correctly

``` html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="maqetta/maqetta.js"></script>
<script type="text/javascript" src="maqetta/States.js"></script>
<style>@import "app.css";@import "themes/claro/claro.css";
</style>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'async':true,'parseOnLoad':true,'modulePaths':{'widgets':'undefined/lib/widgets'}"></script>
<script type="text/javascript">
require(["dijit/dijit"]);
require(["dojo/parser"]);
require(["dojox/mobile"],function(dojoxMobile){dojoxMobile.themeMap=[["Android","",["themes/custom/custom.css"]],["BlackBerry","",["themes/custom/custom.css"]],["iPad","",["themes/custom/custom.css"]],["iPhone","",["themes/custom/custom.css"]],[".*","",["themes/custom/custom.css"]]];dojoxMobile.themeFiles = [];});
require(["dojox/mobile/deviceTheme"]);
require(["dojox/mobile/compat"]);</script>
</head>
<body class="claro" data-maqetta-device="blackberry" dvFlowLayout="true">
</body>
</html>
```

when the first widget is drop the file is butchered, the dojo/dojo.js is moved below the requires

``` html
<DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="maqetta/maqetta.js"></script>
<script type="text/javascript">
require(["dijit/dijit"]);
require(["dojo/parser"]);
require(["dojox/mobile"],function(dojoxMobile){dojoxMobile.themeMap=[["Android","",["themes/custom/custom.css"]],["BlackBerry","",["themes/custom/custom.css"]],["iPad","",["themes/custom/custom.css"]],["iPhone","",["themes/custom/custom.css"]],[".*","",["themes/custom/custom.css"]]];dojoxMobile.themeFiles = [];});
require(["dojox/mobile/deviceTheme"]);
require(["dojox/mobile/compat"]);
require(["dojox/mobile"]);</script>
<script type="text/javascript" src="maqetta/States.js"></script>
<style>@import "app.css";@import "themes/claro/claro.css";
</style>
<script type="text/javascript" data-dojo-config="'async':true,'parseOnLoad':true,'modulePaths':{'widgets':'undefined/lib/widgets'}" src="lib/dojo/dojo/dojo.js"></script>
</head>
<body class="claro" data-maqetta-device="blackberry" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp">
 <div id="View_0" dojoType="dojox.mobile.View" style="height: 100%;" selected="true"></div>
</body>
</html>

```

**Comment by billreed63** [comment] 2011-12-02 19:37
The root of the problem is the first time we drop a widget we search for the requires in ve/context.addHeaderScriptText for example

```
require(["dojox/mobile"]);
```

In the case of mobile we have added a function, so the search fails

```
require(["dojox/mobile"],function(dojoxMobile){dojoxMobile.themeMap=[["Android","",["themes/custom/custom.css"]],["BlackBerry","",["themes/custom/custom.css"]],["iPad","",["themes/custom/custom.css"]],["iPhone","",["themes/custom/custom.css"]],[".*","",["themes/custom/custom.css"]]];dojoxMobile.themeFiles = [];});

```

So when we add the dojox.mobile requires we add the script element back in as the first child of the head...

**Comment by billreed63** [comment] 2011-12-02 20:22
fixed by above

**Closed as completed by billreed63** 2011-12-02 20:22 UTC
Labels: Theme Editor, Priority High, Mobile

**Comment by jhpedemonte** [comment] 2011-12-13 17:55
I reverted the first commit because it was too fragile and not the right thing to do.

I [redid `addHeadScriptText`](https://github.com/maqetta/maqetta/commit/0f04021bc5514c94fd300bfdc4e2b63e69598f13) and that seems to have taken care of this issue as well.  Please let me know if you find an issue.

(Note, as of this writing, the commit is only on the **script-loading-redo** branch.  If everything tests well, I'll commit to **master** soon.
