### ISSUE TITLE
Unable to DnD html items onto ListItem

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1799] opened 2012-02-22 17:26 UTC
tweetView:

If I create a page with a RoundRecList and then attempt to add html items like <img> or <div> to the ListItem, I can not drop theme on the list item in page designer, but I can take the img in the outline view and DnD it on the ListItem. But then the ListItem in the outline tree does not show the img as a child, but looking at the source it is their

**Comment by JonFerraiolo** [comment] 2012-02-22 22:20
@peller @jhpedemonte 

As an experiment I temporarily set the package.json metadata for ListItem to have allowedChildren=ALL. This would allow me to drop arbitrary widgets into a ListItem and see what happens. 

Upon trying it out by dragging/dropping a LABEL into ListItem, things fail (ultimately in ModifyRichTextCommand) because the target parent node is set to the following node (with this class):

"mblListItemTextBox HtmlWidget"

which is probably an inner node of the ListItem rather than the rootnode of the ListItem. Addressing this issue will represent non-trivial effort.

**Comment by JonFerraiolo** [comment] 2012-03-07 22:29
Pushing to M6 and reassigning to @jhpedemonte  Too difficult and too risky to attempt to fix for M5.

In playing with the code some, I think this will be a non-trivial amount of work that will involve at least a couple of helper methods, and probably some helper methods we haven't ever used before. I suspect we will need to use a getChildren() helper to show the children of the ListItem, and an addChild() helper to inject a new widget as a child widget (although maybe getContainerNode() helper will be sufficient). My gut is that this one is about a week worth of work for someone already up learning curves with widgets, helpers, and dojox.mobile.

Important to address this because ListItem is one of the workhorses for dojox.mobile.

**Comment by doronrosenberg** [comment] 2012-04-20 00:49
I an concur with @JonFerraiolo, the issue is we are hitting an inner node as a target, which has no id and thus AddCommand breaks early.

Would simply walking up the dom tree until we find a widget (I guess perhaps check if the node has an id and check if that is a widget id) work in this case rather than add more helper functionality?

**Comment by JonFerraiolo** [comment] 2012-04-20 03:21
Yes, walking up the dom tree looking for container widget sounds like something to try. We already do this sort of thing in various places in the app.

**Comment by doronrosenberg** [comment] 2012-04-20 20:30
@JonFerraiolo 

So the real issue I think is that ListItem has in Outline an `<a>` child which then has a `<div>` in it.  Select say the `<a>` in outline throws:

```
TypeError: widget._srcElement is undefined
```

And in all the chooseParent code, those 2 nodes are marked as isWidget true.  If I understand it correctly, that `<a>` node and its children should not appear in the Outline, correct?

**Comment by JonFerraiolo** [comment] 2012-04-20 22:04
In debugger, I see this:

```
<li id="ListItem_0" data-dojo-type="dojox.mobile.ListItem" class="mblListItem" style="" widgetid="ListItem_0">
  <a class="mblListItemAnchor mblListItemAnchorNoIcon">
    <div class="mblListItemTextBox"><span class="mblListItemLabel">Item 1</span></div>
  </a>
</li>
```

What I think we want to have happen is:
- Outline palette only shows things that Maqetta treats as widgets. Therefore, with a ListItem that has only text content, Outline palette shows no children for ListItem
- Text content for ListItem isn't a widget, but can be edited via SmartInput, and can contain rich HTML markup (e.g., this is <b>bold</b>)
- But if user adds other widgets as children of ListItem, then those widgets appear in the Outline palette as children of the ListItem

But I don't know if the above is possible or reasonably easy to implement the above approach because I don't know how ListItem works. Do child widgets end up inside of the (a) A element, or (b) do they get stuffed inside of DIV.mblListItemTextBox, or (c) somewhere else?

Whatever, we will probably need a couple of custom helper functions to pull this off.

**Comment by doronrosenberg** [comment] 2012-04-20 22:19
```
<li data-dojo-type="dojox.mobile.ListItem">
  Item 2<input type="checkbox" data-dojo-type="dojox.mobile.CheckBox"></input>
</li>
```

translates to:

```
<li id="li_1" data-dojo-type="dojox.mobile.ListItem" class="mblListItem" widgetid="li_1">
  <a class="mblListItemAnchor mblListItemAnchorNoIcon HtmlWidget" properties="[object Object]">
    <div class="mblListItemTextBox HtmlWidget" properties="[object Object]">
      <span class="mblListItemLabel HtmlWidget" properties="[object Object]">Item 2</span>
      <input type="checkbox" id="input_0" data-dojo-type="dojox.mobile.CheckBox" class="mblCheckBox" tabindex="0" widgetid="input_0" style="-moz-user-select: none;">
    </div>
  </a>
</li>
```

**Comment by doronrosenberg** [comment] 2012-04-20 22:21
So I think the dnd code is working fine, just need to get rid of that HTMLWidget class I think.

**Comment by JonFerraiolo** [comment] 2012-04-20 23:22
Yes, agree that we need to get rid of HTMLWidget stuff.

But given that widgets get added as content inside of DIV.mblListItemTextBox, _maybe_ we should treat the DIV.mblListItemTextBox as a widget. That should allow widgets to be dropped before and after the TextBox, with the blinking cursor showing where the new widget would be added. That would mean defining widget metadata for DIV.mblListItemTextBox. (Just an idea, I don't know the implementation implications.)

**Comment by doronrosenberg** [comment] 2012-04-21 00:16
Hmm, where would all this HTMLWidget creating occur? I can't find the code where we build the model where we would be adding the <a> widget and children.

**Comment by JonFerraiolo** [comment] 2012-04-21 00:46
I would put a break point in createWidget within widget.js and see if it gets called recursively when creating a ListItem. I don't remember the details, but maybe put a breakpoint in _processWidgets in Context.js.

**Comment by peller** [comment] 2012-04-21 04:27
IIRC, it all happens in a method inappropriately named 'getWidget' (that is, it has side-effects of actually creating a structure)  See davinci/ve/widget.js  Context._attachChildren iterates through the dom calling getWidget and attach on the results.

**Comment by doronrosenberg** [comment] 2012-04-24 17:55
I was over complicating things - because we set allowChild to ANY, the html nodes ListItem generates are being added to the outline and treated as widgets.  Shouldn't we be building the outline based on the model and not the generated DOM?

**Comment by JonFerraiolo** [comment] 2012-04-24 18:26
@jhpedemonte says the same sort of thing (use model instead of canvas's DOM) at least once a week, on a comprehensive basis across the code base, and we have an explicit bug for the Outline palette: #750. I haven't look at the Outline palette recently, but I would guess that it wouldn't be that much work (a few days?) to change that one part of the code, even if we fix others parts later.

Note that @peller and @jonferraiolo have had various recent discussions about other fixes to Outline palette to greatly simplify the implementation. My experiments show that we can probably have a small amount of code if we use dojo.store.Memory and custom treenode creation methods. I can't find the issues which captured that discussion - @peller was that an email conversation, or is there an issue about possible ways to simplify outline palette? Whatever, I recommend coordinating with @peller if you are messing with Outline palette.

**Comment by doronrosenberg** [comment] 2012-04-24 18:34
this is happening in Context.js::attach, so fixing it there will hopefully fix the Outline palette without any code changes to the palette.

**Comment by peller** [comment] 2012-04-24 19:25
the discussion was mostly verbal.  A related ticket is #2045

**Comment by JonFerraiolo** [comment] 2012-04-24 19:59
@doronrosenberg If the fix is restricted to Context.js::attach, sounds like good news to me

**Comment by doronrosenberg** [comment] 2012-04-24 20:03
the "fix" to get children from the model and not the DOM breaks dnd pretty badly (only the body becomes a target, probably because the model doesn't have dimensional data), so I think that having a helper getChildren would work better.  This would also allow us perhaps to add some sort of dummy "Label" widget so that people can drop before/after the label.

**Comment by JonFerraiolo** [comment] 2012-04-24 21:30
You probably have already figured this out, but just in case: it really should be the case that there is a one-to-one correspondence between widgets in the model and traversing the DOM on the canvas looking for nodes that have a _dvWidget property on them. One widgets in the model should have this property. If there are nodes on the canvas that have a _dvWidget property and don't appear in model, then that's a bug we should fix. You mention above that there might be some nodes that have `HTMLWidget` on them when they shouldn't. My guess is that this would be the same problem as a widget having an erroneous _dvWidget property.

**Comment by doronrosenberg** [comment] 2012-04-24 21:50
@JonFerraiolo 

here is the code that I think is the culprit (in _Widget.js):

```
    _getChildren: function(attach) {
        var containerNode = this.getContainerNode(),
            children = [];

        if (containerNode) {
            dojo.forEach(containerNode.children, function(node) {
                if (attach) {
                    children.push(require("davinci/ve/widget").getWidget(node));
                } else {
                    var widget = node._dvWidget;
                    if (widget) {
                        children.push(widget);
                    }
                }
            });
        }

        return children;
    },
```

If attach is passed through, we generate widgets for all children, even non-dvWidgets.

**Closed as completed** 2012-04-25 17:50 UTC
Labels: Visual Editor, Bug, Priority High, Mobile
