### ISSUE TITLE
Pages / Work lost during session

### ISSUE THREAD

**Issue by trinea-us** [maqetta/maqetta#1816] opened 2012-02-28 22:53 UTC
When working with
the preview 4 release
with windows 7
starting maqetta in localhost mode with the supplied start script
every now and then the currently edited pages vanishes.

i.e.
it no longer exists in the file system
if you want to save to saving does not work
ich you quit the page its gone and all the work is lost

regards,
ulrich

**Comment by JonFerraiolo** [comment] 2012-02-28 23:19
@childsb - I'm almost certain we have/had a bug for this that is/was Priority-High for M5. Maybe same as #1491

**Comment by trinea-us** [comment] 2012-02-28 23:31
well i just read 1491 ...

i also loose pages intermittently ...

which means the file exists.
i edit it later. make some changes.
then press the save button.

and the the file is gone completely.
it does not happen all the time
but every now and then and i can not yet say which actions lead to it exactly

**Comment by JonFerraiolo** [comment] 2012-02-29 00:03
I wonder if the intermittent problems might be related to issues with either server errors or session timeouts. Maybe we can bulletproof things somehow to make sure we don't lose files if something goes amiss with server or session timeout occurs. (Very bad to lose files!)

**Comment by childsb** [comment] 2012-03-02 18:04
I believe this issue is resolved per fix 53cb818--

The problem is on Windows server--

When we create files on the server, we skip over writing if the content length = 0.

For some reason, just getting a URLConnection on windows then not writing anything would cause the JVM to lock the file in the thread.  This resulted in any file.delete() to fail (and leave the file on the file system).

## I changed the code to write 0 bytes and set content length to 0 for empty files.  This resolved the file lock.

i'm closing this bug for now.  if you still notice the problem, please re-open with as much detail as possible

**Closed as completed by childsb** 2012-03-02 18:04 UTC
Labels: Files View, Priority High
