### ISSUE TITLE
Dialog appears (disabled) behind smart input

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2968] opened 2012-08-16 03:14 UTC
**_Tests > Widget Palette: Mobile Data Store Based > EdgeToEdgeDataList: Data file from workspace**_:

Clicking on folder icon in smart input brings up the "Select a source" dialog **behind** the smart input.  Also, dialog is disabled (smart input still has focus), so cannot complete test.

**Comment by doronrosenberg** [comment] 2012-08-16 03:16
dupe of #2965

**Closed as completed by doronrosenberg** 2012-08-16 03:16 UTC
Labels: Bug, Priority High, Smart Input, Severity 2
