### ISSUE TITLE
Surround with div -- div is oddly placed

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3288] opened 2012-09-06 20:05 UTC
Probably for M8, and probably specific to absolute layout...

Using FF on MAc going to staging server... using HTML source below
1. Select leftmost button labeled "Button23"
2. Right-click and select "Surround with div"
3. While button is put inside of a div from a modeling perspective, the div isn't around the button from a rendering perspective:

![GitHub Logo](http://i.imgur.com/3elmL.png)

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/form/Button",
  "dijit/Calendar",
  "dijit/form/TextBox",
  "dijit/layout/ContentPane",
  "dijit/layout/AccordionContainer",
  "dijit/layout/TabContainer",
  "dijit/form/CheckBox",
  "dijit/ColorPalette",
  "dijit/form/ComboBox",
  "dijit/form/HorizontalSlider",
  "dijit/form/HorizontalRule",
  "dijit/form/HorizontalRuleLabels"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="false" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">

 <input type="text" data-dojo-type="dijit.form.TextBox" style="position: absolute; z-index: 900; left: 262px; top: 132px;"></input>
 <div data-dojo-type="dijit.layout.ContentPane" title="Pane" doLayout="false" style="position: absolute; z-index: 900; left: 13px; top: 262px; width: 300px; height: 300px;">
  <input type="button" data-dojo-type="dijit.form.Button" intermediateChanges="false" label="Button" iconClass="dijitNoIcon" style="position: absolute; z-index: 900; left: 82px; top: 36px;"></input>
  <input type="checkbox" data-dojo-type="dijit.form.CheckBox" style="position: absolute; z-index: 900; left: 40px; top: 135px;"></input>
  <input data-dojo-type="dijit.Calendar" style="width: 281px; height: 214px; position: absolute; z-index: 900; left: 220px; top: 137px;"></input>
</div>
<span data-dojo-type="dijit.layout.AccordionContainer" style="min-width: 1em; min-height: 1em; position: absolute; z-index: 900; width: 304px; height: 343px; left: 403px; top: 304px;">
<div data-dojo-type="dijit.layout.ContentPane" title="Pane 1" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" doLayout="false">
 <div data-dojo-type="dijit.ColorPalette" style="position: absolute; z-index: 900; left: 38px; top: 23px;"></div>
<span data-dojo-type="dijit.layout.TabContainer" style="min-width: 1em; min-height: 1em; position: absolute; z-index: 900; width: 300px; height: 300px; left: 11.5px; top: 177px;" controllerWidget="dijit.layout.TabController">
<div data-dojo-type="dijit.layout.ContentPane" title="Tab 1" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" doLayout="false">
 <input type="button" data-dojo-type="dijit.form.Button" intermediateChanges="false" label="Button" iconClass="dijitNoIcon" style="position: absolute; z-index: 900; left: 32.5px; top: 21px;"></input>
</div>
<div data-dojo-type="dijit.layout.ContentPane" title="Tab 2" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" doLayout="false"></div>
</span></div>
<div data-dojo-type="dijit.layout.ContentPane" title="Pane 2" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" doLayout="false"></div>
</span><span data-dojo-type="dijit.layout.TabContainer" style="min-width: 1em; min-height: 1em; position: absolute; z-index: 900; left: 77px; top: 594px; width: 300px; height: 300px;" controllerWidget="dijit.layout.TabController">
<div data-dojo-type="dijit.layout.ContentPane" title="Tab 1" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" doLayout="false">
 <div data-dojo-type="dijit.form.HorizontalSlider" intermediateChanges="false" discreteValues="Infinity" style="position: absolute; z-index: 900; left: 51px; top: 68px; width: 200px; height: auto;">
   <div data-dojo-type="dijit.form.HorizontalRule" container="bottomDecoration" style="height: 5px;"></div>
   <ol data-dojo-type="dijit.form.HorizontalRuleLabels" container="bottomDecoration" labels="0%,50%,100%" style="height: 20px;"></ol>
 </div>
</div>
<div data-dojo-type="dijit.layout.ContentPane" title="Tab 2" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="selected" closable="false" doLayout="false"></div>
</span>
<div style="position: absolute; z-index: 900; left: 425px; top: 663px; width: 155px; height: 208px;">
<select data-dojo-type="dijit.form.ComboBox" value="Item 1" intermediateChanges="false" trim="false" uppercase="false" lowercase="false" propercase="false" invalidMessage="$_unset_$" pageSize="Infinity" searchDelay="200" style="position: absolute; z-index: 900; left: 60px; top: 67px;">
<option value="Item 1" selected="selected">
Item 1</option>
<option value="Item 2">
Item 2</option>
<option value="Item 3">
Item 3</option>
</select>
</div>
<input data-dojo-type="dijit.Calendar" style="width: 281px; height: 214px; position: absolute; z-index: 900; left: 152.81666870117186px; top: 112.90001220703124px;"></input>
<input type="button" data-dojo-type="dijit.form.Button" intermediateChanges="false" label="Button23" iconClass="dijitNoIcon" style="position: absolute; z-index: 900; left: 221.5px; top: 62.90000915527342px;"></input>
<input type="button" data-dojo-type="dijit.form.Button" intermediateChanges="false" label="Button23" iconClass="dijitNoIcon" style="position: absolute; z-index: 900; left: 13.816665649414052px; top: 91.90000915527342px;"></input>
<img src="samples/SampleBanner.jpg" style="width: 454px; height: 67px; position: absolute; z-index: 900; left: 458.81666870117186px; top: -4.099987792968761px;"></img>
</body>
</html>

```

**Comment by JonFerraiolo** [comment] 2012-09-06 20:23
Closing as dupe of #396. Added a reference to this issue in that issue.

**Closed as completed by JonFerraiolo** 2012-09-06 20:23 UTC
Labels: Visual Editor, Priority High, Severity 3
