### ISSUE TITLE
Launch with query url leads to metadata loading failures

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#2929] opened 2012-08-14 03:20 UTC
@jhpedemonte 

I think this is a regression we've seen before with partial url "math", but not sure of the issue #

Go to a url like this:

http://localhost:8081/maqetta/?resetWorkspace=true

And the workbench loads, but with errors on the console, like this:

```
Uncaught SyntaxError: Unexpected token < :8081/maqetta/?resetWorkspace=true/app/metadata/html/0.8/html/table/TableAction.js&@revision@:1
Uncaught TypeError: string is not a function Workbench.js:967
Uncaught SyntaxError: Unexpected token < :8081/maqetta/?resetWorkspace=true/app/metadata/html/0.8/html/table/SelectTableAction.js&@revision@:1
```

Filing as prio-high for evaluation.  Feel free to bump as necessary.

**Comment by childsb** [comment] 2012-08-23 18:46
Dupe of #2348

**Closed as completed by childsb** 2012-08-23 18:46 UTC
Labels: Bug, Priority High, Regression
