### ISSUE TITLE
DojoX Mobile Carousel exception

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3403] opened 2012-09-17 16:54 UTC
@doronrosenberg 

Using Chrome on Mac going to local server with latest...

Opening against 7.0.1 for investigation...
1. New Mobile Application
2. Drag Carousel onto canvas
3. Click OK on smart input and see:

```
ErrorCtor
 "Error
    at Error (unknown source)
    at new ErrorCtor (http://localhost:8081/maqetta/app/dojo/errors/create.js?@revision@:13:21)
    at Deferred.cancel.promise.cancel (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:287:16)
    at declare.expand (http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:243:27)
    at declare._expandNode (http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:1622:9)
    at lang.hitch (http://localhost:8081/maqetta/app/dojo/_base/lang.js?@revision@:375:55)
    at signalListener (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:37:21)
    at Deferred.then.promise.then (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:252:5)
    at declare._expandNode (http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:1621:22)
    at selectPath (http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:1002:11)
    ----------------------------------------
    rejected at Deferred.cancel.promise.cancel (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:289:6)
    at declare.expand (http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:243:27)
    at declare._expandNode (http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:1622:9)
    at lang.hitch (http://localhost:8081/maqetta/app/dojo/_base/lang.js?@revision@:375:55)
    at signalListener (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:37:21)
    at Deferred.then.promise.then (http://localhost:8081/maqetta/app/dojo/Deferred.js?@revision@:252:5)
    at declare._expandNode (http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:1621:22)
    at selectPath (http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:1002:11)
    at http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:986:6
    at Object.array.map (http://localhost:8081/maqetta/app/dojo/_base/array.js?@revision@:282:15)
    ----------------------------------------
[object Deferred]
    at new <anonymous> (http://localhost:8081/maqetta/app/dojo/_base/declare.js?@revision@:384:8)
    at declare.collapse (http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:316:35)
    at declare.removeChild (http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:486:9)
    at declare._onItemDelete (http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:1735:13)
    at Object.array.forEach (http://localhost:8081/maqetta/app/dojo/_base/array.js?@revision@:240:15)
    at declare._onItemDelete (http://localhost:8081/maqetta/app/dijit/Tree.js?@revision@:1728:10)
    at inherited (http://localhost:8081/maqetta/app/dojo/_base/declare.js?@revision@:189:30)
    at declare._onItemDelete (http://localhost:8081/maqetta/app/davinci/ui/widgets/OutlineTree.js?@revision@:152:8)
    at lang.hitch (http://localhost:8081/maqetta/app/dojo/_base/lang.js?@revision@:373:45)
    at target.(anonymous function).dispatcher [as onDelete] (http://localhost:8081/maqetta/app/dojo/aspect.js?@revision@:94:38)" instrumentation.js:18
```

**Comment by doronrosenberg** [comment] 2012-09-17 23:42
I figured out the first exception, Carousel was calling reparent for no reason during a bad time.

The 2nd exception occurs because we remove and readd all the children of the Carousel.  ViewHelper focuses another view as a view is being removed, but the view that is being focused gets removed before the focus code runs.

**Comment by doronrosenberg** [comment] 2012-10-04 15:03
Not sure how to fix this, we have the helper and the createtool out of sync.

**Comment by JonFerraiolo** [comment] 2012-10-04 15:38
-> @JonFerraiolo

**Comment by JonFerraiolo** [comment] 2012-12-05 16:14
Closing - can't reproduce with latest builds. I tried on both Mac/Chrome and Mac/Firefox. I tried with a brand-new Maqetta session where first widget was a Carousel and I tried with a brand-new session where I added a ScrollableView and then a Carousel as first widgets. I tried bringing up SmartInput multiple times, and couldn't get the console messages to appear.

**Closed as completed** 2012-12-05 16:14 UTC
Labels: Priority High, Mobile, Severity 2
