### ISSUE TITLE
Source editor duplicates last character with Mac/Firefox

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#759] opened 2011-07-21 04:52 UTC
(Adam, could you please forward this to the Orion team if the problem appears to be in their code?)

Following this particular sequence of events, the source editor duplicates the last character in the source file. Happens on Mac/FF, but not on Mac/Chrome. Haven't tried Windows yet.

In Maqetta, do a new CSS files and enter the following text:

```
.foo3 {
    color:red;
    /* this is a comment
        that spans multiple lines */
    font-size:13pt;
}
```

Now select all characters on the 2 comment lines and the font-size line and hit Ctl-C to cut. The content will now look like this:

```
.foo3 {
    color:red;
}
```

with the type-in point just before the closing "}". Now touch the command key or click in front of the string 'color:red'. Magically, a second closing "}" appears just after (or before) the first one.

**Comment by peller** [comment] 2011-07-21 05:02
need to verify on latest Orion code

**Comment by peller** [comment] 2011-10-18 20:00
@waynevicknair

Problem does not occur with Orion M3 code in their standalone example at web/examples/editor/minimaleditor.html but does still occur when the M3 code is integrated into davinci.ui.Editor.  May have something to do with our styler (which we could replace with Orion)

**Comment by peller** [comment] 2011-10-19 14:46
In ModifyRichTextCommand, widget.getContainerNode is returning null, so the entire document is getting reparsed -- which of course is bad, since the widgets already exist (are not detached)  I think the intent of this code is to only reparse the contents of the widget (widget.domNode and children)

Seems to be the getAllowedChild logic here 7aa9bf9f    Is this appropriate for getContainerNode?  Shouldn't the container always be returned?

@billreed63

**Comment by JonFerraiolo** [comment] 2012-07-18 16:04
Set to M7/Prio-Med so at least we can see if bug still exists and determine how critical the issue is. After that analysis, then jiggle the milestone, priority and severity.

**Comment by jhpedemonte** [comment] 2012-08-30 13:01
Couldn't reproduce.  Closing.

**Closed as completed by jhpedemonte** 2012-08-30 13:01 UTC
Labels: Source Editors, Priority Med, Severity 2
