### ISSUE TITLE
can't move widgets in flow mode (VE test #2)

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1392] opened 2011-12-19 18:17 UTC
1) Create a new HTML file
2) Add a few widgets (buttons, checkboxes, DIVs)
3) try and move the widgets above or below one another.  notice they wont budge.

@jhpedemonte assigning to you to re-assign or prioritize.

**Comment by jhpedemonte** [comment] 2011-12-19 18:50
I tested this on Chrome and Firefox but could not reproduce.  @JonFerraiolo @peller can you guys reproduce?

**Comment by peller** [comment] 2011-12-19 18:53
title says "absolute" mode but description implies "flow" mode.  Both work for me.

**Comment by childsb** [comment] 2011-12-19 19:34
It's flow layout.  Maybe i'm doing it wrong?  i am running with firebug open if that makes a dif.

**Comment by peller** [comment] 2011-12-19 21:18
Perhaps you're trying to DnD by clicking on the widget itself?  You have to click on the focus rectangle that goes around the widget.

**Comment by JonFerraiolo** [comment] 2011-12-20 15:18
Works for me, too, using Mac/FF with Firebug on, in both flow and absolute mode. Note that there is a bug #1220 which says we should try to allow dragging from the middle of the widget and not just the outline. Of course, there will be complexities with container widgets because we need to allow the mouse to pick widgets inside of the container, and we also want to allow for dragging out a rectangle to select all widgets inside of the rectangle: #363

**Comment by jhpedemonte** [comment] 2011-12-22 23:08
Closing as currently working.

**Closed as completed by jhpedemonte** 2011-12-22 23:08 UTC
