### ISSUE TITLE
HTML Table: Insert column before adds row and column

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3286] opened 2012-09-06 19:51 UTC
HTML

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/form/Button"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
<table border="1" style="border-collapse: collapse; table-layout: fixed; width: 100%; height: auto;">
<colgroup>
    <col></col>
    <col></col>
    <col></col>
    <col></col>
    <col></col>
    <col></col>
    <col></col>
    <col></col>
    <col></col>
    <col></col>
  </colgroup>
  <tbody>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
    <tr>
      <td>
        A</td>
      <td>
        b<b>gggxxxxxxxxx</b>
      </td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
    </tr>
    <tr>
      <td>
        cat</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
    </tr>
    <tr>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
    </tr>
    <tr>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
    </tr>
    <tr>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
    </tr>
    <tr>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
    </tr>
    <tr>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
    </tr>
    <tr>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
      <td>
        &nbsp;</td>
    </tr>
  </tbody>
</table>
</body>
</html>

```

Select  row 1 column 2 (bgggxxx....)
right click to get context menu, select  insert column before

Note that a new row has been added above the old header row

**Comment by billreed63** [comment] 2012-09-06 19:52
insert column after adds row also

**Comment by aerwin** [comment] 2012-09-06 20:08
@billreed63 Could you list out steps? You must have done something to add header row? E.g., did you check the header row box in table smart input at some point?

**Comment by billreed63** [comment] 2012-09-06 20:10
remove column does not refresh table. ![GitHub Logo](http://i.imgur.com/65qNV.png)

**Comment by aerwin** [comment] 2012-09-06 20:17
@billreed63 For the remove column addition, I again need repro steps. And, doesn't it really sound like a separate problem?

**Comment by billreed63** [comment] 2012-09-06 20:27
You can put them in separate issues if you feel that is best

To reproduce use the HTML at the top of the defect

then in page designer
For the remove column issue select any cell I selected row 2 column 3 and then used context menu remove column
for insert before
Select row 1 column 2 (bgggxxx....)
right click to get context menu, select insert column before

This was on FF 15

Are you not able to reproduce with the HTML provided?

**Comment by aerwin** [comment] 2012-09-06 20:37
Well, one reason I wanted steps is that when I glanced at the HTML it didn't make sense:

E.g., the table smart input would put `&nbsp` chars in the `<th>` elements:

```
<tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
```

So, wondered if this is HTML you edited by hand or if the table smart input is generating unexpected HTML, etc.

And, then I guess I'm confused by your steps... so basically remove column fails and then the insert stuff fails? I'd have guessed by the way you opened the report (and the title) that you inserted cols, that failed, and then remove failed. 

So, I'm rather confused. :)

**Comment by billreed63** [comment] 2012-09-06 21:03
I created a 10x10 table with headers from the smartInput
I then double clicked in row 1 col 2 to get smartInput I entered `a<b>bbbbb</b>` clicked the html radio and then ok
I then selected row 1 col 2, right clicked to get the context then selecte insert column before

That is when I got a row inseted above row 1 and a col to the left  of col 2.

I said snap that is not what I want an click on the undo icon.. the action was undone  

I then tried to insert before again and got the same behavior.

from that point I continued insert after, it added the row so again I click undo (undo works great :)  ) 
and continued....

So maybe it all started because I had html markup in the second header cell

**Comment by jhpedemonte** [comment] 2012-09-06 21:42
@aerwin, please assess impact for M7.  It's getting late.

**Comment by jhpedemonte** [comment] 2012-09-06 21:42
cc @JonFerraiolo

**Comment by aerwin** [comment] 2012-09-07 03:57
@billreed63 

As far as I can tell there's no issue here, so closing with explanation below. @billreed63 , if you disagree, please let me know.

Starting from the HTML source in the initial report, I don't think it's really adding a new row. Instead, at the start state, the header row has a height of 0 (because all of the TH elements are missing `&nbsp;`). And, as part of adding a new column, it creates a new TH cell that includes `&nbsp;`. So, now all of the sudden, the header row has a non-zero height. So, it just looks like a new row was added.

```
 <tr>
      <th></th>
      <td>
        &nbsp;</td>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
```

So, a big question I have (as I alluded to in one of my earlier comments) is how all of the `&nbsp;`'s got removed from the TH elements.

But, following the steps as I understand them, I can't reproduce that either. So, please let me know if I missed something and you have a scenario that removes the `&nbsp;`'s chars.

My steps:
1. New HTML file 
2. Drag HTML table onto page 
3. Set rows and cols to 10x10 and select header row checkbox
4. Use smart input to set HTML contents of Row 1, Col 2
5. After above steps, I end up with the following rendering and the following source (which contains `&nbsp;`'s in all of the TH elements).

![GitHub Logo](http://i.imgur.com/WGkbu.png)

```

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
 <table style="border-collapse:collapse;table-layout:fixed;width:100%;height:auto;" border="0">
   <colgroup>
     <col></col>
     <col></col>
     <col></col>
     <col></col>
     <col></col>
     <col></col>
     <col></col>
     <col></col>
     <col></col>
     <col></col>
   </colgroup>
   <tbody>
     <tr>
       <th>
         &nbsp;</th>
       <th>
         &nbsp;</th>
       <th>
         &nbsp;</th>
       <th>
         &nbsp;</th>
       <th>
         &nbsp;</th>
       <th>
         &nbsp;</th>
       <th>
         &nbsp;</th>
       <th>
         &nbsp;</th>
       <th>
         &nbsp;</th>
       <th>
         &nbsp;</th>
     </tr>
     <tr>
       <td>
         &nbsp;</td>
       <td>
         a<b>bbbbb</b>
       </td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
     </tr>
     <tr>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
     </tr>
     <tr>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
     </tr>
     <tr>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
     </tr>
     <tr>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
     </tr>
     <tr>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
     </tr>
     <tr>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
     </tr>
     <tr>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
     </tr>
     <tr>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
       <td>
         &nbsp;</td>
     </tr>
   </tbody>
 </table>
</body>
</html>
```

**Closed as completed** 2012-09-07 03:57 UTC
Labels: Bug, Priority High, Lib: HTML Tables
