### ISSUE TITLE
Icon container doesn't show icons in firefox when previewing

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#801] opened 2011-07-27 16:18 UTC
- new HTML file
- drop View and IconContainer onto canvas
- preview in browser

The labels show but the icons do not

Tested in Win/FF

**Comment by JonFerraiolo** [comment] 2011-07-27 17:33
@jhpedemonte, @peller

I haven't gotten to the bottom of this, but somehow or other browser caching seems to be involved. I was able to reproduce with Mac/Chrome. If I do a View Source on the preview window, the UL/LI elements for the IconContainer are not in the source file. But if I Clear Browsing Data and then refresh the preview window, the IconContainer widget appears.

**Comment by JonFerraiolo** [comment] 2011-08-24 17:20
@peller This might be a good one for you to grab from me.

**Comment by peller** [comment] 2011-08-25 13:31
looks like a bug in IconContainer.  The `IconItem.onError` method (which populates defaultIcon if none is specified) never fires.  Apparently, FF does not consider `<img src="">` to be an error.  The same behavior can be seen here:

http://archive.dojotoolkit.org/dojo-2011-08-25/dojotoolkit/dojox/mobile/tests/test_BlackBerry-IconContainer.html

FWIW, no matter how much I clear cache or reload, I never see these icons

**Comment by peller** [comment] 2011-08-25 14:07
http://bugs.dojotoolkit.org/ticket/13755

**Comment by peller** [comment] 2011-08-26 18:27
github didn't seem to catch the checkin: fbf29b9b92b982456dec

**Comment by jhpedemonte** [comment] 2011-09-10 00:18
Didn't notice until recently, but the switch to `iconBase` makes it not work when **IconContainer** is first dropped on the page.  Worse, on WebKit browsers, it causes an infinite loop, where it tries to load the icon but fails, and so on.

Although, it works fine with `iconBase` in every other case: preview, reopening file.  Even on WebKit.

**Comment by jhpedemonte** [comment] 2011-09-10 00:22
Infinite loop issue is fixed in Dojo 1.7b5.  But still shows broken image icon instead of the default icon when widget is first added to page.

**Comment by jhpedemonte** [comment] 2011-09-10 01:05
OK, the problem with the icon not showing when IconContainer is first dropped on page is as follows:

Normally, IconItem calls the method `inheritParams()`, which inherits the parameters from its parent container, IconContainer.  But this depends on the Dojo parser, which first instantiates a widget and then instantiates its children.

But we it **backwards**: `davinci.ve.widget.createWidget()` first creates the children and then the parent.  So in the case where a user drops an IconContainer on to the page, first the IconItem is created, but `inheritParams` finds no parent and therefore does not properly set its `icon` property.

Not sure if there is a fix for this.  Maybe a CreateTool?

**Comment by peller** [comment] 2011-09-10 02:06
yeah, I suppose you could set the value with a helper.

**Comment by jhpedemonte** [comment] 2011-09-11 15:04
Fixed by b4fe5986b5789c56bed72cd3dcf216684a58c7f9.

**Closed as completed by jhpedemonte** 2011-09-11 15:04 UTC
Labels: Bug, Mobile
