### ISSUE TITLE
Major issues with Review and Commenting

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1885] opened 2012-03-09 00:46 UTC
With Chrome and lab9:50010, I'm seeing many issues with review and commenting. I almost think multi-user review and commenting is fairly well broken, so I'm going to list a few issues in this report. If we need separate issues as we investigate, I can open those.
1. User B's comments are not saved. (At first I thought maybe just User A couldn't see UserB's comments, but if I add some comments as UserB and then open/close the review as User B, none of the comments have been saved.)

Of course, # 1 is a show stopper and maybe make these irrelevant for now, but I also see:
1. User B can edit User A's comments, but not his own.
2. User B's comments are same color as User A's comments

Also... With Chrome and lab9:50020, there are no reviews in my Reviews tab despite having created a few. Thought I saw this on lab9:50010 at least once as well, but I think logging in and out fixed it.

**Comment by JonFerraiolo** [comment] 2012-03-09 04:25
We need to fix all of the above and a handful of other things (to be detailed in upcoming issues).

**Comment by waynevicknair** [comment] 2012-03-20 20:47
number 1 in the in the first numbered list is working on Mac Chrome and Safari. 
will fix number 1 in the second numbered list under issue #1953. 
number 2 in the second numbered list is a duplicate of issue #1838.

closing this issue to fix problems under individual issues.

**Closed as completed by waynevicknair** 2012-03-20 20:47 UTC
Labels: Review and Commenting, Priority High
