### ISSUE TITLE
Widget palette interaction and presentation improvements

### ISSUE THREAD

**Issue by jmockler** [maqetta/maqetta#556] opened 2011-06-17 16:53 UTC
@jmockler @jinsil 
UI Review - Jun 10, 2011
Using Firefox 4.0

@jmockler will post the previous designed specifications for improvements to the widget view.

**Comment by JonFerraiolo** [comment] 2012-07-18 15:30
Closing. Dupe of #192

**Closed as completed by JonFerraiolo** 2012-07-18 15:30 UTC
