### ISSUE TITLE
M4->M5 migration using localhost:50000, I see user name "localhost user" 

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2017] opened 2012-03-27 20:53 UTC
@childsb @jhpedemonte 

Upon trying out an M4->M5 migration using localhost:50000, I see user name "localhost user" using M5 even though I'm running the "server" version.

Here is what I did:
- Clear browser cache and cookies on localhost
- Launch Preview 4 server on localhost:50000 using "server" script
- Open up debugger in browser, with Network panel open
- Login, app shows, open app.css, close app.css.
- Look at cookies for files that are downloaded (eg workbench.css). This is what I see:

resourceTreeSaveStateCookie=.%2Fproject1; reviewCommentExplorerViewTreeSaveStateCookie=.review%2Fsnapshot; maqExplorer=.%2Fproject1; undefined=.%2Fproject1%2Fapp.css; DAVINCI.USER=Ferraiolo; JSESSIONID=wo4fmd3z2kth14p4s5estrbbu; DAVINCI.USER=
- Logout (should be optional)
- Copy the users/ folder from the Preview 4 installation folder into the Preview 5 installation folder
- Launch Preview 5 server on localhost:50000 using "server" script
- Open up debugger in browser, with Network panel open
- Login using same login as when running Preview 4

NOTICE: user name is "localhost user", not the login you entered
- Look at cookies for files that are downloaded (eg workbench.css). This is what I see:

maqExplorer=.%2Fproject1; resourceTreeSaveStateCookie=.%2Fproject1; reviewCommentExplorerViewTreeSaveStateCookie=.review%2Fsnapshot; undefined=.%2Fproject1%2Fapp.css; DAVINCI.USER=; JSESSIONID=1xh27jiiehjzbdrl6jrhlxc4e; DAVINCI.USER=Ferraiolo

I'm not sure how cookies work when there are two values for the same cookie.

**Comment by jhpedemonte** [comment] 2012-03-28 03:16
-> closing

I tested with latest code on Chrome and Firefox and could not reproduce.  Each time, when loading M4 users on M5, Maqetta properly displayed my username, not "localhost user".

**Closed as completed by jhpedemonte** 2012-03-28 03:16 UTC
Labels: Priority High, Migration
