### ISSUE TITLE
Can't find org.eclipse.orion.server.configurator

### ISSUE THREAD

**Issue by wcnjeusr** [maqetta/maqetta#3983] opened 2013-12-24 10:11 UTC
Can't find org.eclipse.orion.server.configurator,how can I run it?
坑货。。。

**Comment by jhpedemonte** [comment] 2014-01-02 19:59
Please post questions like this to the [users](https://groups.google.com/forum/#!forum/maqetta-users) or [developers](https://groups.google.com/forum/#!forum/maqetta-devs) forums.

Closing as this is not a bug.

**Closed as completed by jhpedemonte** 2014-01-02 19:59 UTC
