### ISSUE TITLE
Empty file after multiple saves

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#1065] opened 2011-10-06 20:16 UTC
# Simple scenario
- New File
  Maqetta: *file1
  WinExplorer: file1.html.workingcopy
- Drag BorderContainer onto workspace
- Preview:
  Maqetta: file1
  WinExplorer: file1.html
- Preview again:
  Maqetta: file1
  WinExplorer: file1.html.workingcopy
- Close file1 tab
  Maqetta: file1
  WinExplorer: NOTHING
- Open file1 again
  Get lots of errors in Maqetta cmd window
  Maqetta browser shows file has no content (blank canvas and outline)
# Another similar scenario
- New File
  Maqetta: *file1
  WinExplorer: file1.html.workingcopy
- Save File
  Maqetta: file1
  WinExplorer: file1.html
- Preview
  Maqetta: file1
  WinExplorer: file1.html
- Close Preview tab
  Maqetta: file1
  WinExplorer: file1.html
- Drag button onto workspace
  Maqetta: *file1
  WinExplorer: file1.html
  WinExplorer: file1.html.workingcopy
- Preview
  Maqetta: file1
  WinExplorer: file1.html.workingcopy
- Close Preview tab
  Maqetta: file1
  WinExplorer: file1.html.workingcopy
- Close file1 Tab
  Maqetta: file1
  WinExplorer: NOTHING
- Maqetta: Open file1 again
  Get lots of errors in Maqetta cmd window
  Maqetta browser shows file has no content (blank canvas and outline)

2011-10-06 08:51:00.234:WARN::ERROR:  /maqetta/cmd/loadFile
java.lang.NullPointerException
        at org.davinci.server.internal.command.LoadFile.handleCommand(Unknown So
urce)
        at org.davinci.server.DavinciCommandServlet.doGet(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.davinci.server.DavinciCommandServlet.service(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrap
per.service(ServletManager.java:180)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service
(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(P
roxyServlet.java:126)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyS
ervlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHtt
pServiceServlet.service(HttpServerManager.java:317)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511
)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:3
90)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:1
82)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:7
65)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:1
52)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:54
2)
        at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpCo
nnection.java:924)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.ja
va:409)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.j
ava:582)
2011-10-06 08:51:09.390:WARN::ERROR:  /maqetta/cmd/saveFile
java.lang.NullPointerException
        at org.davinci.server.internal.command.SaveFile.handleCommand(Unknown So
urce)
        at org.davinci.server.DavinciCommandServlet.doPut(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:730)
        at org.davinci.server.DavinciCommandServlet.service(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrap
per.service(ServletManager.java:180)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service
(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(P
roxyServlet.java:126)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyS
ervlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHtt
pServiceServlet.service(HttpServerManager.java:317)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511
)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:3
90)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:1
82)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:7
65)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:1
52)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:54
2)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnectio
n.java:939)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.ja
va:409)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.j
ava:582)
2011-10-06 08:51:16.218:WARN::ERROR:  /maqetta/cmd/saveFile
java.lang.NullPointerException
        at org.davinci.server.internal.command.SaveFile.handleCommand(Unknown So
urce)
        at org.davinci.server.DavinciCommandServlet.doPut(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:730)
        at org.davinci.server.DavinciCommandServlet.service(Unknown Source)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.equinox.http.registry.internal.ServletManager$ServletWrap
per.service(ServletManager.java:180)
        at org.eclipse.equinox.http.servlet.internal.ServletRegistration.service
(ServletRegistration.java:61)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.processAlias(P
roxyServlet.java:126)
        at org.eclipse.equinox.http.servlet.internal.ProxyServlet.service(ProxyS
ervlet.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.eclipse.equinox.http.jetty.internal.HttpServerManager$InternalHtt
pServiceServlet.service(HttpServerManager.java:317)
        at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511
)
        at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:3
90)
        at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:1
82)
        at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:7
65)
        at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:1
52)
        at org.mortbay.jetty.Server.handle(Server.java:326)
        at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:54
2)
        at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnectio
n.java:939)
        at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
        at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
        at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
        at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.ja
va:409)
        at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.j
ava:582)

**Comment by JonFerraiolo** [comment] 2012-07-18 17:09
Had been unassigned. -> @childsb M7 Prio-High. Mostly a dupe of other similar bugs. @childsb please verify that the above scenarios are fixed, and if so, please close.

**Comment by childsb** [comment] 2012-07-19 16:26
i can't reproduce, closing.

**Closed as completed** 2012-07-19 16:26 UTC
Labels: Runtime, Files View, Priority High, Severity 1
