### ISSUE TITLE
SourceEditor Tests - Container widgets delete fails

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#658] opened 2011-07-05 22:27 UTC
this is the scenario where we delete a DIV (HTML widget) that has dijit children.

```
TypeError: Result of expression 'this._srcElement._getAttribute("id")' [undefined] is not an object. 
```

shows up in javascript console. Exception is coming from line 773 of 'davinci/ve/widget.js' which looks like:

``` javascript

    getId: function(){
        if (!this.id) // equals "dojo_form_button_0"
        {
            if( !this.domNode.id || !this.type){
                return undefined;
            }

            var id = this.domNode.id;
            var base = (this.isHtmlWidget ? this.getTagName() :this.type).replace(/\./g, "_") + "_";
            if(id.length > base.length && id.substring(0, base.length) == base){
                // auto-generated id
                return undefined;
            }
        }
        if (this._srcElement && this._srcElement._getAttribute("id").noPersist) // line 773 
            return undefined;
        return this.id;
    },
```

looks like even though 'this.id' was set to "dijit_form_button_0" doesn't mean that 'this._srcElement' has an 'id' attribute.

**Comment by JonFerraiolo** [comment] 2011-07-06 00:04
Assigned to me to scope out the problem regarding how serious this bug is for user and how difficult and risky to fix.

**Comment by jhpedemonte** [comment] 2011-07-07 04:51
I can't reproduce this.

Following the **Container Widgets** subsection of the **SourceEditor** tests.  I added a **DIV**, changed its **margin-top** style, then added a Dijit **TextBox** and **Button**.

Selected the DIV and deleted it, but saw no error in the console.

**Comment by jhpedemonte** [comment] 2011-07-07 05:46
Setting **Priority Low** for now.  If this can be reproduced, we can up the priority (but probably only to **Med**).

**Comment by JonFerraiolo** [comment] 2011-07-07 14:32
I couldn't reproduce either in Win/FF.

@waynevicknair: Can you try to reproduce again, and if you can reproduce, can you provide exact steps that caused the problem, including which system and browser you are using?

If you can't reproduce, please close.

**Comment by waynevicknair** [comment] 2011-07-07 18:16
running Safari 5.0.5 on Snow Leopard (same as when i opened issue) i could not reproduce on today's build. however, i when it occurred i debugged down to the exact line of code which failed. does anyone know the relationship between '_srcElement' and 'domnode' on a dijit widget? do we want to add defensive code there because 'this._srcElement' is _not_ guaranteed to have an 'id' attribute?

**Comment by JonFerraiolo** [comment] 2011-07-07 18:27
Oh, yeah, most of us know the difference between domNode and _srcElement. Somewhat depends on which domNode you are talking about (Dijit has one, maybe widget.js has a different one), but it refers to a (no surprise here) to the root DOM node for a particular widget within the iframe's HTML document. _srcElement points to the corresponding node within the model, which is a whole separate parallel structure for the same document as is showing in the iframe. If you have an auto-generated ID on a widget, then there will be a temporary ID on the DOM node in the iframe but no ID on the _srcElement's corresponding node because the _srcElement holds what gets serialized into the file system.

**Comment by waynevicknair** [comment] 2011-07-07 23:22
right then. that sounds like "yes, we should strengthen the test before we call on something that can be validly null."

**Comment by jhpedemonte** [comment] 2011-07-08 04:36
I'm fine with adding a **null** check there.  Also, get rid of the **return undefined** lines -- really no point, can just be **return**.

**Comment by waynevicknair** [comment] 2011-07-08 16:02
added `null` check to getId() with commit 2ad4de9c13f80d864285

**Comment by JonFerraiolo** [comment] 2011-07-08 20:09
Closing this issue. Hard to reproduce, and Wayne provided a speculative fix for the problem.

**Closed as completed by JonFerraiolo** 2011-07-08 20:09 UTC
Labels: Source Editors, Bug, Priority Low
