### ISSUE TITLE
CSS paths in HTML files not based on current project name (e.g., point at "project1")

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2912] opened 2012-08-10 20:57 UTC
Found this while trying to import recent Maqetta project into RAD...
1. Create new Eclipse based project
2. Create new HTML file
3. Look at HTML source and see "project1" hard-coded in a number of paths (like @import "../../project1/themes/claro/document.css";" so if you delete "project1" or try to render in a different environment (like RAD) without a "project1" then rendering will fail

```

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'packages':[{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'dojo-src','location':'..'},{'name':'clipart','location':'../../clipart'},{'name':'shapes','location':'../../shapes'},{'name':'gridx','location':'../gridx'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/Calendar"
]);
</script>
<style>@import "../../project1/themes/claro/document.css";@import "../../project1/themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
 <input data-dojo-type="dijit.Calendar"></input>
</body>
</html>
```

**Comment by aerwin** [comment] 2012-08-14 02:59
This also breaks R&C if create review in project not named "project1":

```
GET http://localhost:8081/maqetta/user/aerwin/ws/workspace/.review/snapshot/20120813215324/project1/themes/claro/document.css 404 (Not Found) file1.html:6
GET http://localhost:8081/maqetta/user/aerwin/ws/workspace/.review/snapshot/20120813215324/project1/themes/claro/claro.css 
```

**Comment by aerwin** [comment] 2012-08-14 20:01
Also, note that aside from the wrong project name that "WebContent" is missing in the case of Eclipse-enabled projects in paths like

```
 @import "../../project1/themes/claro/document.css";"
```

**Comment by childsb** [comment] 2012-08-14 20:32
i created a new eclipse project, then a new HTML file and the CSS links look fine.  i tried eproject1, zzproject1, both with no problems. also tested on maqetta-test.austin.ibm.com with no issues.

could you clear workspace and try again?  maybe old files..?

**Comment by aerwin** [comment] 2012-08-14 20:43
Here's what I just did:
1. Stopped server
2. Cleared workspace
3. Did git pull
4. Run server from Eclipse
5. Clear browser cache
6. Signup as new user
7. Choose Create - Project from menu and create Eclipse-enabled project called "myEclipseProject20120814"
8. Create new HTML file
9. Drop Calendar on new file
10. View source and see bad CSS paths in source:

```

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'packages':[{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'dojo-src','location':'..'},{'name':'clipart','location':'../../clipart'},{'name':'shapes','location':'../../shapes'},{'name':'gridx','location':'../gridx'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/Calendar"
]);
</script>
<style>@import "../../project1/themes/claro/document.css";@import "../../project1/themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
 <input data-dojo-type="dijit.Calendar"></input>
</body>
</html>
```

**Comment by childsb** [comment] 2012-08-14 21:08
can you reproduce this with your ID on maqetta-test?

**Comment by billreed63** [comment] 2012-08-14 21:19
@aerwin what run config are you using maqetta.orion?

I just followed @aerwin steps and this is what I see

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'packages':[{'name':'dojo-src','location':'..'},{'name':'gridx','location':'../gridx'},{'name':'idx','location':'../../idx'},{'name':'idxThemes','location':'../../../themes'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/Calendar"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
 <input data-dojo-type="dijit.Calendar"></input>
</body>
</html>

```

**Comment by aerwin** [comment] 2012-08-14 21:21
Here's the generated source from just trying to reproduce on maqetta-test. My Eclipse project was called "myEclipseProjectOrion20120814". There's actually more references to "project1" than when I tried from my dev environment. However, they are in different places.

```

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'packages':[{'name':'dojo-src','location':'..'},{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'widgets','location':'../../custom'}],'themeMap':[['Android','',['../../project1/themes/android/android.css']],['BlackBerry','',['../../project1/themes/blackberry/blackberry.css']],['iPad','',['../../project1/themes/ipad/ipad.css']],['iPhone',null,['../../newProject2/themes/iPhone2/iPhone2.css']],['.*','',['../../project1/themes/iphone/iphone.css']]],'mblThemeFiles':[]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/Calendar"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
 <input data-dojo-type="dijit.Calendar"></input>
</body>
</html>
```

**Comment by billreed63** [comment] 2012-08-14 21:21
Oh wait, I think you need to update your submodules inperticual dojo 1.8

**Comment by childsb** [comment] 2012-08-14 21:35
This is my HTML when creating on the test machine.  Notice only yours has that themeMap object.  Any idea where this is coming from @billreed63?:

``` html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'packages':[{'name':'dojo-src','location':'..'},{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/Calendar"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-device="iphone" data-maq-flow-layout="true" data-maq-ws="collapse" data-maq-appstates="{}" id="myapp">
 <input data-dojo-type="dijit.Calendar"></input>
</body>
</html>
```

**Comment by aerwin** [comment] 2012-08-14 21:36
At @billreed63 's request I tried with the local maqetta.orion launch script from Eclipse and the output looked ok:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'packages':[{'name':'dojo-src','location':'..'},{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dijit/Calendar"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
 <input data-dojo-type="dijit.Calendar"></input>
</body>
</html>
```

So, appears local maqetta.multi-user is broken. (As well as whatever is currently on maqetta-test).

**Comment by childsb** [comment] 2012-08-20 17:20
since we're not shipping the maqetta.multi user (only orion) i'm lowering priority.

**Comment by JonFerraiolo** [comment] 2012-08-28 15:40
@aerwin - do we really need this for M7? If so, any chance you could help out with the issue you filed?

**Comment by aerwin** [comment] 2012-08-28 15:47
@JonFerraiolo Do we support standalone (non-orion) builds anymore for M7?

**Comment by jhpedemonte** [comment] 2012-08-30 12:56
Closing, since we won't support non-Orion builds.

**Closed as completed by jhpedemonte** 2012-08-30 12:56 UTC
Labels: Priority Med, Regression, Severity 2, Download & IDE Integration
