### ISSUE TITLE
Modifying theme in Safari not reflected in UI until refresh

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#1013] opened 2011-09-14 14:41 UTC
Create new theme
click global widget or button 
change background color.
Change is not reflect in UI but is reflect in HTML file that is using theme..

**Comment by JonFerraiolo** [comment] 2011-09-14 15:52
@jhpedemonte - likely a caching issue

**Comment by jhpedemonte** [comment] 2011-11-04 04:08
Dupe to #778.  Reopen if that's incorrect.

**Comment by peller** [comment] 2011-11-29 16:55
not sure I see the basis for the dup, but perhaps some clarification would be useful.  By "UI" so we mean the color change does not show up in the theme editor? (that's what I'm seeing -- the properties panel shows the change, but the global widget in the theme editor does not change color, nor does the change seem to "stick" if you select something else and come back)  I don't see the change reflected in the HTML if I create a new file.  In fact, the new file came up broken for me without any theme the first time I loaded it, then with a very plain looking theme, not reflecting the theme I had cloned (claro)

**Comment by peller** [comment] 2011-11-29 17:04
I just tried it again, and now when I try changing the background color with the global widget selected, I get an error that the new theme is read only.  (All works fine in Chrome)  background-image says "url(images/calendarContainerImages.png)" which seems a little odd, but may be what the theme uses.

**Comment by JonFerraiolo** [comment] 2011-11-29 17:09
The "new theme read-only" problem is a separate bug: #1264. You can make theme changes after reopening theme via Open Theme... command (if my memory is right).

**Comment by childsb** [comment] 2011-12-02 21:22
Fixed with checkin 712397781125563492ff8c8e29632ac3c82515b3

**Comment by JonFerraiolo** [comment] 2011-12-16 16:34
@childsb: your comment says this one is fixed, but the issue is still open. I tried to reproduce today and it seems to be fixed. Please close if this one is indeed fixed.

**Closed as completed** 2011-12-16 18:55 UTC
Labels: Theme Editor, Bug, Priority Med
