### ISSUE TITLE
No middle snap line on <label>

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1090] opened 2011-10-21 20:18 UTC
To reproduce:
- Add a **&lt;label>** next to a dijit **Textbox**.
- If i move the label up and down, i can snap to the **top, middle and bottom** of the textbox.
- But if I move the textbox, i can only snap to the **top or bottom** of the label, **no middle**.

**Comment by JonFerraiolo** [comment] 2011-10-21 20:35
I'm having trouble reproducing. I'm able to snap to middle when dragging either the TextBox or <label>. Questions:
- Both widgets are absolutely positioned?
- Running from latest code in GitHub or Preview 3? (I may have committed a fix since Preview 3)
- Move the TextBox away from label (significantly above or below the label). Now drag the TextBox next to label and see if the middle alignment line appears now. (I'm wondering if the existing TextBox's alignment points are taking precedence over the label's middle alignment point.)

**Comment by jhpedemonte** [comment] 2011-10-21 20:45
Actually, I did find this when on P3, but I just reproduced on today's code.  I was actually able to get the text box once to snap to middle of label, but most of the time I never see the middle snap line.

To repro:
- Drop text box, followed by label (i changed label to custom text if that matters).
- Align label to text box middle.  That works.
- When trying to align text box to label middle, I only see top and bottom snap lines.

**Comment by JonFerraiolo** [comment] 2011-10-31 17:22
OK, I think I see what's happening here. The snapping logic loops through the whole document to find candidate snapping points for left, center, right, top, middle, bottom alignment. There is a single winner in x and a single winner in y, where the winner is the snap line with smallest delta from current mouse location. A new snap line is the winner only if its delta is less than the previous winner. Fine and good so far. The problem with this case is that the search is done in document order, and the TextBox is before the LABEL in document order. Therefore, the TextBox's middle snaps to its own middle before it will snap to the LABEL's middle. If the LABEL were added before the TextBox, then you would see the middle snap line for the LABEL.

This one will require some careful thought. Multiple possible ways to go.

**Closed as completed** 2011-12-14 01:03 UTC
Labels: Bug, Priority Med, UI
