### ISSUE TITLE
Server console error messages about jqueryUI and YUI

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#491] opened 2011-06-14 20:37 UTC
@jhpedemonte

Upon creating a new HTML file, the server console shows these messages, even though my Widget palette shows sections for jQueryUI and YUI:

Library file not found! :WebContent/jquery-ui-1
Library file not found! :WebContent/yui

Then if you try to add jQuery and YUI widgets do an HTML page, you just get the HTML snippets without any of the jQuery and YUI library magic that turns them into widgets.

**Comment by childsb** [comment] 2011-06-21 19:43
Both of these plugins ONLY contain metadata at the moment. I'm assuming we removed the code for legal/distribution issues...?  Leaving this open but it's not a server/resource bug.

**Comment by JonFerraiolo** [comment] 2011-06-21 20:49
(I can't remember why I assigned this to you. Reassigned to Javier.) I thought @jhpedemonte and @waynevicknair were going to figure out a way to get the jQuery and YUI libraries included in the builds so that those widgets would work again.

**Comment by jhpedemonte** [comment] 2011-06-21 21:21
I added the library code to my local install and I no longer see the error messages in the server console.  Yes, Wayne and I talked about it and came up with a solution.  Not sure if he's had a chance to work on it yet.  @waynevicknair?

**Comment by waynevicknair** [comment] 2011-06-22 00:02
the builds on Dojo Foundation external machine include these libraries and plugins. i asked @JonFerraiolo if i should copy the libraries into the internal builds you download from lab14 and was told not to.

**Comment by jhpedemonte** [comment] 2011-07-06 19:10
Dupe of internal bug 7787.

**Closed as completed by jhpedemonte** 2011-07-06 19:10 UTC
Labels: Build, Server, Widget Libraries, Priority Med
