### ISSUE TITLE
Exception when changing moveTo property in this case

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2123] opened 2012-04-26 17:13 UTC
- New HTML FIle - iphone
- Add a ScrollableView - set ID to 'root_view'
- Add a Heading - set text to 'root'
- Add a second ScrollableView - set ID to 'alerts_view'
- Add a Heading - set text to 'alerts'
- With Heading selected, in Properties palette, go to Widget-specific section
- Set 'back' to 'aaa'
- Using dropdown menu, set moveTo to 'root_view'

Result=> Exception in Dojo - Cannot read property 'value' of undefined

```
declare._autoCompleteText (_AutoCompleterMixin.js:325)
declare._announceOption (_AutoCompleterMixin.js:507)
declare._selectOption (_AutoCompleterMixin.js:515)
hitch (lang.js:155)
dispatcher.around.advice (aspect.js:189)
target.(anonymous function) (aspect.js:176)
declare.onClick (_ComboBoxMenuMixin.js:51)
declare._onMouseUp (_ListMouseMixin.js:50)
hitch (lang.js:153)
```

**Comment by doronrosenberg** [comment] 2012-04-26 19:20
If you reload the page, does that still happen (changing moveto throws an exception)?  I can't reproduce on Firefox or Chrome

**Comment by JonFerraiolo** [comment] 2012-04-26 19:46
I refreshed and tried again, and I haven't been able to reproduced. At the time I saw this, I had multiple editors open. I wonder if there is a bug where something is pointing to the wrong document.

**Comment by JonFerraiolo** [comment] 2012-04-26 19:47
I refreshed and tried again, and I haven't been able to reproduced. At the time I saw this, I had multiple editors open. I wonder if there is a bug where something is pointing to the wrong document.

**Comment by doronrosenberg** [comment] 2012-05-03 15:03
CLosing as I can't reproduce

**Closed as completed by doronrosenberg** 2012-05-03 15:03 UTC
Labels: Properties View, Widget Libraries, Priority High, Mobile
