### ISSUE TITLE
Download exception

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#2669] opened 2012-07-03 03:32 UTC
@billreed63 @jhpedemonte 

Maybe this is a dupe of #2336, but that issue seems to be about an intermittent bug and I'm seeing an exception that seems to happen with every download operation. I have seen the exception with builds on Win/FF and Win/Chrome and running from Eclipse using Mac/Chrome. I expect the exception occurs in all browsers on all platforms.
- New Eclipse project
- Create a sub-folder to WebContent/, such as WebContent/aaa
- Create a new HTML file in that folder, add a Button, save and close.
- Click on download-entire-workspace icon in Files palette.
- Accept all defaults and click OK.

Result=> Exception at Context.js:2781:

```
var head = this.getDocumentElement().getChildElement('head'),
```

because this.getDocumentElement() returns null. The reason is that the "this" object is actually subclass "davinci.ve.RebaseDownload" which has created a Context-like object but not everything is defined on the "this" object. In particular, `this._srcDocument` is undefined, which causes an exception.

**Comment by childsb** [comment] 2012-07-10 19:05
i couldn't reproduce this error exactly, but the steps did lead to another similar error.

the forEach over the themeFiles array was out of scope and causing a NPE.  please re-open if you still notice the issue still.

**Closed as completed by childsb** 2012-07-10 19:05 UTC
Labels: Files View, Priority High, Regression
