### ISSUE TITLE
Preview takes very long time to fully load

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2753] opened 2012-07-16 03:19 UTC
Preview takes way too long to fully load.

New File, added a Dijit checkbox and text area, then clicked Preview.  Noticed that the checkbox was not styled as it should be for Dojo.  Browser was waiting to load a resource.  Finally, after about 30 seconds, the checkbox styled properly (CSS files must have loaded from network?).

Noticed this error in the console (may or may not be related):

```
GET http://lab9:50010/maqetta/user/javier@pedemonte.us/ws/workspace/project1/resources/blank.gif 404 (Not Found)
```

When testing, clear cache in order to force loading Dojo CSS from network when showing Preview.

After, closed Preview, then closed the file editor.  Reopened file, then opened Preview again.  Widgets not styled correctly, even after refreshing Preview page.  Zazl related?

(lab9:50010; Chrome/Mac)

---

Checked the server logs and saw the following error many times (I'm guessing related to Preview calls):

```
Using jar: /var/lib/maqetta-deploy/base/server/plugins/org.eclipse.equinox.launcher_1.2.0.v20110502.jar
Using directory: /var/lib/maqetta-deploy/base/server/users
Start your browser at: http://localhost:50010/maqetta
Listening on port 0.0.0.0/0.0.0.0:50011 ... 
Registering Zazl JavaScript servlet
Registering Maqetta HTML Filter for Zazl
Jul 15, 2012 9:18:42 PM org.dojotoolkit.optimizer.amd.rhinoast.AMDJSOptimizer _getAnalysisData
INFO: AST parsing [dijit/dijit] using the Rhino AST API
Jul 15, 2012 9:18:45 PM org.dojotoolkit.server.util.rhino.RhinoClassLoader loadJS
SEVERE: Exception while loading class for [json.json2]
java.lang.NullPointerException
        at maqetta.zazl.MaqettaOSGiResourceLoader._getResource(MaqettaOSGiResourceLoader.java:60)
        at org.dojotoolkit.server.util.resource.CachingResourceLoader.getResource(CachingResourceLoader.java:31)
        at org.dojotoolkit.server.util.resource.CachingResourceLoader.readResource(CachingResourceLoader.java:92)
        at org.dojotoolkit.server.util.rhino.RhinoClassLoader.loadClass(RhinoClassLoader.java:57)
        at org.dojotoolkit.server.util.rhino.RhinoClassLoader.loadJS(RhinoClassLoader.java:89)
        at org.dojotoolkit.server.util.rhino.RhinoJSMethods.loadFromClassLoader(RhinoJSMethods.java:152)
        at org.dojotoolkit.server.util.rhino.RhinoJSMethods.loadJS(RhinoJSMethods.java:111
```

**Comment by jhpedemonte** [comment] 2012-07-16 03:19
More Zazl server issues:

```
Jul 15, 2012 9:40:47 PM org.dojotoolkit.optimizer.amd.rhinoast.AMDJSOptimizer _getAnalysisData
INFO: AST parsing [dijit/Menu] using the Rhino AST API
Jul 15, 2012 9:40:47 PM org.dojotoolkit.optimizer.amd.rhinoast.AMDJSOptimizer _getAnalysisData
INFO: AST parsing [dijit/MenuItem] using the Rhino AST API
Jul 15, 2012 9:40:47 PM org.dojotoolkit.optimizer.amd.rhinoast.AMDJSOptimizer _getAnalysisData
INFO: AST parsing [dijit/form/MultiSelect] using the Rhino AST API
Jul 15, 2012 9:40:48 PM org.dojotoolkit.optimizer.amd.rhinoast.AMDJSOptimizer scanForCircularDependencies
INFO: Circular dependency found : dijit/dijit->dijit/_base->dijit/a11y->dojo/dom-attr->dojo/dom-prop->dojo/dom-construct->dojo/dom-attr
Library file not found! :WebContent/dojo-src/dijit/nls/en/common.js
Library file not found! :WebContent/dojo-src/dijit/nls/en-us/common.js
Library file not found! :WebContent/dojo-src/dijit/nls/en/loading.js
Library file not found! :WebContent/dojo-src/dijit/nls/en-us/loading.js
Library file not found! :WebContent/dojo-src/dojo/cldr/nls/en-us/number.js
Library file not found! :WebContent/dojo-src/dojo/cldr/nls/en-us/currency.js
Library file not found! :WebContent/dojo-src/dijit/form/nls/en/validate.js
Library file not found! :WebContent/dojo-src/dijit/form/nls/en-us/validate.js
```

Related or a different bug?

**Comment by peller** [comment] 2012-07-16 03:50
circular loop should have been addressed by @rbackhouse 's commit here 80efdcbac108096818b5e58c7bc913314f67cf64   I was hoping to check out the initial load time with a cold cache after that fix...

**Comment by peller** [comment] 2012-07-16 03:51
@rbackhouse I also saw the blank.gif error... which should probably be logged as a separate issue

**Comment by jhpedemonte** [comment] 2012-07-16 04:07
At the time of testing, lab9:50010 was running from 6892d9c1a7b65a39e79de2e5165983de1fc5f125, which is later than the one you listed (and therefore @rbackhouse's commit should have been included).

**Comment by rbackhouse** [comment] 2012-07-16 10:04
The nullpointer is indicating that the code to resolve the user from the url segments is not working in this particular scenario. 

The reported circular dependency is purely a warning and can be ignored. 

I'm not so sure about "Library file not found" though, I would expect those nls resources tp be found.

**Comment by jhpedemonte** [comment] 2012-07-16 16:41
The _"Library file not found"_ errors most likely have to do with **"dojo-src"**.  Something is pointing to that directory, but I'm going to guess that only exists on one user's workspace.  In the source and the build, the directory will be **"dojo"**.

**Comment by rbackhouse** [comment] 2012-07-16 16:55
If dojo-src is not present then Zazl won't work. dojo-src was added as an ajaxLibrary extension in davinci.dojo_1_8

```
     <ajaxLibrary name="dojo-src" id="dojo-src" version="1.8">
        <libraryPath location="WebContent/dojo-src" name="/lib/dojo"></libraryPath>
        <metadata location="app/metadata/dojo/1.8" />
     </ajaxLibrary>
```

**Comment by jhpedemonte** [comment] 2012-07-16 17:13
I don't understand:  why do we have both "dojo" and "dojo-src" under dojo_1_8/WebContent?

**Comment by peller** [comment] 2012-07-16 17:40
dojo-src is for zazl and zazl only, I think.  Zazl only runs on unoptimized source.  The rest of the product is using the pre-built dojo/ directory.

**Comment by rbackhouse** [comment] 2012-07-16 18:39
The root cause of the performance issue appears to be the fact that the davinci.dojo_1_8 is in jar format. It's over 60MB in size and loading resources out of it via OSGi API calls is going to be slow. When I unjarred it into a directory format the load for sample1.html (clear cache, first preview on server start) was about 5 seconds. 

Assuming /davinci.war/feature.xml is the feature used to assemble the packaging I think removing the unpack="false" from

   <plugin
         id="davinci.dojo_1_8"
         download-size="0"
         install-size="0"
         version="0.0.0"
         unpack="false"/>

should me the davinci_dojo_1_8 bundle should be left as a directory

I'll continure to investigate the nullpointer and missing nls files but they don't seem to be contributing to the performance slow down

**Comment by rbackhouse** [comment] 2012-07-16 19:10
I found the issue with the nullpointer. The Zazl org.json dependency bundle was missing a directory export from its build.properties.

**Comment by rbackhouse** [comment] 2012-07-16 19:21
Library file not found! :WebContent/dojo-src/dijit/nls/en/common.js
Library file not found! :WebContent/dojo-src/dijit/nls/en-us/common.js
Library file not found! :WebContent/dojo-src/dijit/nls/en/loading.js
Library file not found! :WebContent/dojo-src/dijit/nls/en-us/loading.js
Library file not found! :WebContent/dojo-src/dijit/form/nls/en/validate.js
Library file not found! :WebContent/dojo-src/dijit/form/nls/en-us/validate.js
Library file not found! :WebContent/dojo-src/dijit/form/nls/en/ComboBox.js
Library file not found! :WebContent/dojo-src/dijit/form/nls/en-us/ComboBox.js

Are correctly being reported as missing. There does not seem to be any harm with them not being there.

**Comment by peller** [comment] 2012-07-16 22:07
@rbackhouse Ah, ok, it's just complaining about individual modules.  I wonder why it's looking for those?  dojo/i18n! should be looking up 'en' or 'en-us' resources for those since Dojo 1.7.  The new AMD resource bundle format explicitly lists variants, and 'en' and 'en-us' aren't among them.  Does zazl provide replacement i18n loader logic?

**Comment by rbackhouse** [comment] 2012-07-16 23:29
Zazl does provide its own i18n processing and will make calls to the resouceloader to find the different language packs. This would explain the messages.

**Comment by peller** [comment] 2012-07-17 00:28
@jhpedemonte @childsb 

We don't seem to have a feature.xml like this.  Anyone know where the corresponding bits are?   Somewhere in the releng ant scripts?  Does this mean we don't want to jar any of our library plugins?  Isn't there a way to ship our product as jars and have Eclipse unjar them?

**Comment by jhpedemonte** [comment] 2012-07-17 02:41
I think there's a bug about getting rid of the OSGi packaging for the widget libraries and just have them live as files in a dir.  However, that won't get done for v1.0.

**Comment by aerwin** [comment] 2012-07-17 14:55
--> Prio from High to Critical

**Closed as completed** 2012-07-17 20:16 UTC
Labels: Server, Regression, Priority Critical
