### ISSUE TITLE
elements are reordered in RoundRect

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#728] opened 2011-07-14 21:32 UTC
1) Create a new html file
2) Drop mobile RoundRect
3) Drop html label in RoundRect, cancel smart input
4) Drop mobile Button in RoundRect, cancel smart input

You should have a document structure like:
- RoundRect
  - Label
  - Button

6) Select button, from the properties palette select Widget Specific->Label change the label

Notice that the Button now moves in front of the label in the page designer and the outline view, but if you look at the source or preview the element order is still correct

**Comment by jhpedemonte** [comment] 2011-07-15 04:37
I cannot recreate.

First, since this is mobile stuff, there should really be a top level View/ScrollableView/SwapView.  But either way, with or without a View, I didn't see the reordering.

**Comment by JonFerraiolo** [comment] 2011-07-16 18:37
I just saw this with IconContainer:
- New HTML file
- Add a View
- Add an IconContainer inside of View
- Select first IconItem
- In Properties palette, and to to Widget-Specific, then change 'icon' property to SampleBanner.jpg

Result => on screen, first IconItem correctly gets SampleBanner.jpg, but it gets incorrectly moved after second IconItem on the page canvas. As Bill reports above, source code (and model) is correct, but page canvas is wrong.

**Comment by peller** [comment] 2011-07-16 18:47
Confirmed.  I'll try to take a look at this tomorrow night.

**Comment by JonFerraiolo** [comment] 2011-07-16 19:13
I did some digging into the second scenario. See #734

**Comment by JonFerraiolo** [comment] 2011-07-16 20:29
I tried the first scenario and couldn't reproduce in Mac/Chrome, but I can reproduce the second scenario.

**Comment by JonFerraiolo** [comment] 2011-07-18 14:41
Regarding second scenario with IconContainer/IconItem, if we don't get a quick dojox.mobile fix for #734 (dojox.mobile needs to support 2nd parameter on addChild), then maybe with each change to an IconItem we will need to delete/recreate the containing IconContainer.

**Comment by JonFerraiolo** [comment] 2011-07-21 23:08
Closing this as Adam's fix makes this problem go away.

**Closed as completed by JonFerraiolo** 2011-07-21 23:08 UTC
Labels: Visual Editor, Bug, Priority High
