### ISSUE TITLE
Changing state doesn't update CSS cascade

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1707] opened 2012-02-04 19:46 UTC
1. In an HTML file with some states, choose Normal state
2. Select widget (say a button)
3. Go to CSS cascade for a property (say Font -> Size)
4. Go to states palette and choose different state (say abc)
5. Note option to "Only apply to current state (abc)" does _not_ appear.
6. Select another widget and note "Only apply to current state (abc)"  _does_ appear
7. Now select another state in states palette (say xyz), and note CSS cascade still says "Only apply to current state (abc)" rather than "Only apply to current state (xyz)"

**Comment by JonFerraiolo** [comment] 2012-03-15 21:35
This is a dupe of #1839, which was fixed by e3b9c08770e6f594049d1215cc6ea7c2f918a19e. Closing.

**Closed as completed by JonFerraiolo** 2012-03-15 21:35 UTC
Labels: Properties View, Priority Med
