### ISSUE TITLE
Can't delete file - selection disappears when doing right-click

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#628] opened 2011-06-30 20:54 UTC
In the **Files** view, select a file.  Notice it has a selection halo.  Then right-click on the file.  Notice that selection halo has now disappeared.

This makes it impossible to delete a file, since selecting **Delete resource** from context menu results in a dialog stating that no resources are selected.

Related to #538?

**Comment by jhpedemonte** [comment] 2011-07-06 02:42
See #657 for some more info.

**Comment by jhpedemonte** [comment] 2011-07-07 05:31
Not sure if the previous commits were meant to fix this issue, but I am still seeing it.  And based on #660, I think I see what is going on.

Currently, when I click on the file, I see a **blue halo**.  But this only represents that that item in the tree has **focus**, but not selection.  Rather, **selection** in a Dijit tree is signified by a **full width blue box** around the item.

So right now, the **File** view does not allow selection of an item and that is why the user cannot delete anything.  The user can only set focus (but not selection) on an item.

**Comment by peller** [comment] 2011-07-07 14:36
There were indeed intended to fix the bug.  Wonder why the "Fixes #628" did not close this ticket?

When I click on a file, I see a blue halo (focus) **and** selection.  The selection code was stubbed out in #510 to get our DnD working, but my change broke the selection and caused this regression.

**Closed as completed by peller** 2011-07-07 14:36 UTC
Labels: Files View, Bug, Priority High
