### ISSUE TITLE
EventCommand.js basically broken

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#908] opened 2011-09-01 00:01 UTC
Undo doesn't seem to be working when changing event properties in the Properties palette, which goes through EventCommand.js.
- New HTML file
- Add a LABEL
- Set onclick property, such as onclick: console.log('ccc')
- Undo

Result=> onclick property still show console.log('ccc'). I don't think this is simply a redraw problem in Properties palette. If you have 2 widgets and select the other than go back to the LABEL, the onclick property is still there. (Changing selection updates all fields in the Properties palette)

**Comment by JonFerraiolo** [comment] 2012-01-01 19:09
Pushing to M5, Priority-Med. We might want to reassign to @childsb or @JonFerraiolo

**Comment by jhpedemonte** [comment] 2012-03-14 05:44
Reassign to Doron.  Take a look and assess risk for M5.

**Comment by doronrosenberg** [comment] 2012-03-14 15:33
The issue is that we call:

```
  widget.setProperties(this._oldProps);
```

during undo.  That won't remove any new properties such as the onclick.  No risk here really, should be easy to fix

**Comment by doronrosenberg** [comment] 2012-03-14 17:39
@JonFerraiolo the event properties is not being refreshed during undo/redo as well, where does that code live?

**Closed as completed** 2012-03-14 19:40 UTC
Labels: Properties View, Visual Editor, Priority Med
