### ISSUE TITLE
Setting editable attribute on EdgeToEdgeDataList causes exception and screws up rendering

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3511] opened 2012-10-04 19:10 UTC
Using Chrome on Mac going to maqetta.org...
1. New mobile app
2. Drag view onto page
3. Drag EdgeToEdgeDataList onto page
4. In widget-specific properties, check the `editable` attribute
5. In widget-specific properties, uncheck the `editable` attribute
6. Rendering in page is messed up and exception in console:

```
Uncaught Error: Tried to register widget with id==ul_0 but that id is already registered dijit.js:15
_158.add dijit.js:15
_2c8.create dijit.js:15
_2c8.postscript dijit.js:15
(anonymous function) dojo.js:15
_1a.construct parser.js:228
(anonymous function) parser.js:74
_578.map dojo.js:15
_1a._instantiate parser.js:69
_1a.instantiate parser.js:67
_18b.constructor /maqetta/app/davinci/davinci.js?3773ee26d1da0e59eda6a108772a6b8990d2c25c:1866
(anonymous function) dojo.js:2900
_24e1.createWidget /maqetta/app/davinci/davinci.js?3773ee26d1da0e59eda6a108772a6b8990d2c25c:51834
_1177.execute /maqetta/app/davinci/davinci.js?3773ee26d1da0e59eda6a108772a6b8990d2c25c:24223
_1c66.execute /maqetta/app/davinci/davinci.js?3773ee26d1da0e59eda6a108772a6b8990d2c25c:39587
ret.withDoc dojo.js:6549
_2d20.execute /maqetta/app/davinci/davinci.js?3773ee26d1da0e59eda6a108772a6b8990d2c25c:62508
_1c0c._objectPropertiesChange /maqetta/app/davinci/davinci.js?3773ee26d1da0e59eda6a108772a6b8990d2c25c:39236
(anonymous function) /maqetta/app/davinci/davinci.js?3773ee26d1da0e59eda6a108772a6b8990d2c25c:35198
(anonymous function) dojo.js:4960
_55f.(anonymous function)._564 dojo.js:6939
on.emit dojo.js:6121
on.emit dojo.js:6157
_3cf.emit dojo.js:5038
publish dojo.js:5216
_588.publish dojo.js:7109
_13e9._onChange /maqetta/app/davinci/davinci.js?3773ee26d1da0e59eda6a108772a6b8990d2c25c:27867
(anonymous function) /maqetta/app/davinci/davinci.js?3773ee26d1da0e59eda6a108772a6b8990d2c25c:27828
(anonymous function) dojo.js:4960
```

**Comment by JonFerraiolo** [comment] 2012-10-06 01:03
@peller @jhpedemonte 

This is a dojo bug - the widget's JavaScript isn't updating the registry properly. Filed a Dojo ticket: http://bugs.dojotoolkit.org/ticket/16105

Sending issue to @peller to manage the integration of the fix into an updated Dojo that (hopefully) we can include with M8.

**Comment by peller** [comment] 2012-10-06 03:28
is this a regression, or something we just discovered?  If it's a regression, we can push for a fix in the 1.8 branch, otherwise we'd be forking the repo again, which is not desirable.  If this is a problem at design-time only, we may be able to monkey patch the code dynamically or something like that, depending on the nature of the fix.

**Comment by aerwin** [comment] 2012-10-06 03:48
I don't know if it's regression or not... it's just something I happened to try.

**Comment by JonFerraiolo** [comment] 2012-10-06 18:10
I think it's a regression. I took my sample HTML file that I included in the bug report and pointed at the CDN for dojo 1.7 instead of 1.8 and I don't see the registry exception with 1.7.

But for the most part, you would only run into this issue when using Maqetta. It's not all that typical for a user to delete and then recreate an EdgeToEdgeList or EdgeToEdgeDataList using the same ID and changing the editable property along the way. 

IMO - It's a bug in Dojo and should be fixed there. If the Dojo fix isn't ready and inside of a production update to Dojo in time for M8, then we should fork the repo and merge the patch into Maqetta's version of Dojo, and then remove that patch when we update Dojo the next time.

Another option might be to define an onRemove helper on the Maqetta side, and clean up the registry there, but I'd rather fork Dojo than try to patch a fix via the onRemove helper.

**Comment by peller** [comment] 2012-10-15 01:32
Fix will be in Dojo 1.8.2, release date not known

**Comment by peller** [comment] 2012-11-26 21:44
see also #3441 which requires an update to 1.8.2

**Comment by JonFerraiolo** [comment] 2012-12-07 00:25
I just tried clicking and unclicking the editable property using latest code and it seems to be hanging. 

I wonder if this is related to the problem that @jhpedemonte mentioned today about mobile ListItems having a different DOM structure with dojo 1.8.

I'm stuck temporarily on this one because of machine issues.

**Comment by peller** [comment] 2012-12-07 02:27
FWIW, I see the exception, then the widget disappears.  No hang.

**Comment by peller** [comment] 2012-12-12 17:09
-> M9, where we can upgrade to 1.8.2 and undo c27f42d

**Comment by peller** [comment] 2012-12-19 04:51
updated to 1.8.2 f3e818c75c4989d4cada3755c89b156858d1b6d8

**Closed as completed** 2013-01-19 15:48 UTC
Labels: Priority High, Mobile, Severity 2
