### ISSUE TITLE
SmartInput not escaping <b> on dojo Button when previewed

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3122] opened 2012-08-27 18:56 UTC
Create new desktop html
DnD button
When SmartInput displayed enter
`label<b>bold</b>test`
ensure that the plan text is selected
click ok
Notice the text is displayed correctly in the designer, but preview the page and the "bold" is bolded

FF/win 7 running on the test build

**Comment by doronrosenberg** [comment] 2012-08-27 19:50
This works fine in my local build but not on maqetta-test.  @peller perhaps zazzle is doing something wonky?

**Comment by doronrosenberg** [comment] 2012-08-27 19:51
@peller I tried with ?zazl=false but it still loaded zazl for me

**Comment by jhpedemonte** [comment] 2012-08-27 20:02
@doronrosenberg, try disabling Zazl in preferences.

**Comment by peller** [comment] 2012-08-27 20:10
or taking away the zazl=xxxx from the url.  Yeah, looks like a bug that zazl=anything is treated as truthy

**Comment by peller** [comment] 2012-08-27 20:17
@rbackhouse 

and it does seem that the MaqettaHTMLFilter is accidentally unescaping HTML entities:

```
<input type="button" data-dojo-type="dijit.form.Button" intermediateChanges="false" label="plain&amp;lt;b&amp;gt;bold&amp;lt;/b&amp;gt;text" iconClass="dijitNoIcon"></input>
```

becomes

```
<INPUT type="button" data-dojo-type="dijit.form.Button" intermediatechanges="false" label="plain&lt;b&gt;bold&lt;/b&gt;text" iconclass="dijitNoIcon">
```

**Comment by doronrosenberg** [comment] 2012-08-27 20:18
Confirmed that removing zazl from the url fixes the issue.

**Comment by rbackhouse** [comment] 2012-08-27 22:53
The HTML Filter use the Neko HTML parser to parse and modify the HTML. It looks like it is not escaping correctly. Will probably have to override some of its writing methods to ensure it does it correctly.

**Comment by rbackhouse** [comment] 2012-08-29 13:44
Should be fixed now

**Closed as completed** 2012-08-29 20:28 UTC
Labels: Priority High, Smart Input, Regression, Severity 2
