### ISSUE TITLE
Regularly corrupting mobile theme

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2405] opened 2012-05-24 18:46 UTC
I don't know if this is related to #2404 I just opened, but this one is kind of bad...
1. Clone theme (say android)
2. Select Global Styling widget and change background to linear gradient (e.g., 2 stops white to black)
3. Background does not get updated
4. Save and close theme
5. Reopen theme and it's corrupted:

![screenshot](http://i.imgur.com/ThseX.png)

**Comment by jhpedemonte** [comment] 2012-05-24 18:47
cc @JonFerraiolo

**Comment by aerwin** [comment] 2012-05-24 18:47
And, also, seemed kind of specific to linear gradient... e.g., with freshly cloned theme if I change background to "red" the change appears in the rendering and saving/reopening the file works fine.

**Comment by aerwin** [comment] 2012-05-24 18:59
Ok... this seems bigger as I play with it more... e.g., not sure you even have to set a property to corrupt things. I had found a couple of font properties (font-weight and font-style) that were being ignored like background linear gradient, and then seeing corruption.

But, then as I played with it some more, I think the corruption occurs if you just open and close the same cloned theme a couple times (whether you make changes or not).

**Comment by aerwin** [comment] 2012-05-24 18:59
Changing title to "Regularly corrupting mobile theme".

**Comment by JonFerraiolo** [comment] 2012-05-24 19:01
I can reproduce.

**Comment by aerwin** [comment] 2012-05-24 19:09
Gets weirder... if I create a new HTML file using one of the themes I thought was corrupted, the rendering of the HTML page seems fine. Also, in some cases reopening what I thought was a corrupted theme in the theme editor also sometimes starts working.

**Comment by billreed63** [comment] 2012-05-24 19:58
I am not sure what we are looking at here: 

The "corruption" in the picture at the top is due to the themes not loading from the server, if you refresh your browser does the theme get updated?

A lot of properties are vot valid for a specfic widget/subwidget/state. we have an ope issue to address this #226

**Comment by aerwin** [comment] 2012-05-24 20:05
Like I said an hour ago:

> Gets weirder... if I create a new HTML file using one of the themes I thought was corrupted, the rendering of the HTML page seems fine. Also, in some cases reopening what I thought was a corrupted theme in the theme editor also sometimes starts working.

**Comment by aerwin** [comment] 2012-05-24 20:09
So, I guess we can chalk it up to sometimes download being really slow (though I'm not sure I ever saw it all  just pop in eventually after initially appearing "corrupt") But, from a UX perspective I thought things were really broken (especially when coupled with #226).

**Comment by JonFerraiolo** [comment] 2012-05-24 20:22
Looks like it isn't a timing/network issue but instead a theme metadata issue. We hope a fix will arrive shortly.

**Comment by billreed63** [comment] 2012-05-24 20:34
missing metadate for mblView fixed by above commit

**Closed as completed by billreed63** 2012-05-24 20:34 UTC
Labels: Theme Editor, Priority High
