### ISSUE TITLE
Widget style selection wizard/dialog?

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#464] opened 2011-06-09 17:55 UTC
Some widgets have several different styles.  For example, here are two styles for `dojox.mobile.TabBar`:

![TabBar](https://docs.google.com/document/pubimage?id=1lzdeIsZBMyU18t-Z4L8z6fqGkgJPnP9Aa29RZflYV9E&image_id=12-nIPyCn6ImtNhiKlJxtEfRcgB4l5mk)
![Segmented Control](https://docs.google.com/document/pubimage?id=1lzdeIsZBMyU18t-Z4L8z6fqGkgJPnP9Aa29RZflYV9E&image_id=1ffYebJkgLPVEegxlzWYvOppsNGitQc0)

Here are the many styles for `dojox.mobile.Switch`:

![Switches](http://i.imgur.com/BDtF9.png)

Currently, if a user wants to switch between these different styles, they would need to fiddle with the **Properties** palette.

I think we should create a default wizard for use by the widgets, something beyond the inline edit.  Inline edit is good for one single property.

But what if we had an overlay that appeared on top of the **Properties** and **Outline** palettes.  The overlay would allow us to show a selection gallery for which type of widget the user would want.  But it could also be used for many other types of widgets.

For example, we could keep inline edit for the simple property case (usually text input) but use the wizard overlay for more complex UI.  There could even be several pages to this wizard overlay.

The main thing I'm thinking of here is to provide a consistent UI for allowing a less technical user to have access to different properties for a given widget.  The wizard overlay would show the properties in a more accessible fashion -- for example, in the case of the widgets above, showing a gallery of available styles.  But this would also be where we show, for example, the wizard for DataGrid, etc.

A more technical user could later directly use the **Properties** palette if necessary.

@JonFerraiolo @billreed63

**Comment by JonFerraiolo** [comment] 2011-06-10 04:43
Sure, we might do wizards or a more complex SmartInput for particular widgets. The SmartInput mechanism is pretty much set up for arbitrary complexity, not just single-value entry. BorderContainer and DataGrid are two existing examples of more complex user input. 

One thing to keep in mind is what the Maqetta UI might look like 12-18 months from now after some UI changes in order to work well on tablets such as the iPad, where there is less screen real estate, controls have to be bigger (because fingers are fatter than a mouse pointer), and UI conventions are different. Seems to me there is a good chance that the Properties palette and Smart Input might operate differently then. So, I would be conservative in short-term about major UI changes and attempt to get things working in short-term via incremental changes to what we have now.

**Comment by JonFerraiolo** [comment] 2011-10-31 16:41
Push to M5?

**Comment by jhpedemonte** [comment] 2011-10-31 19:27
Yes, I'm fine with pushing to M5.  I think this bug needs to come under the umbrella of overall UI enhancements.

**Comment by jhpedemonte** [comment] 2012-03-14 04:40
-> M6

We'll have more discussions on UI in M6.

**Comment by JonFerraiolo** [comment] 2012-05-12 22:24
-> @doronrosenberg M7 Prio-High

**Comment by doronrosenberg** [comment] 2012-05-14 15:04
@JonFerraiolo why is this high?

**Comment by JonFerraiolo** [comment] 2012-06-11 19:57
Closing as dupe of newer bug #2183

**Closed as completed by JonFerraiolo** 2012-06-11 19:57 UTC
Labels: Visual Editor, Widget Libraries, Feature, Priority High, Smart Input, Mobile
