### ISSUE TITLE
Save as doesn't work

### ISSUE THREAD

**Issue by megaD** [maqetta/maqetta#3761] opened 2013-02-24 19:34 UTC
Save as doesn't save the current document but just creates a new document.

Please fix.

Thanks,

Piotr

**Comment by JonFerraiolo** [comment] 2013-02-25 15:33
@megaD but that's how most software works these days. Try almost any other popular product, such as MSWord. Create a new document, type "aaa", save it under a name (e.g., aaa.docx). Then back in the editor, change the text to "bbb" and do a Save As to bbb.docx. Then reopen aaa.docx - the original document (aaa.docx) still says "aaa".

Or perhaps I am misunderstanding.

**Comment by megaD** [comment] 2013-02-26 07:55
This is exactly what doesn't work for me in Maqetta. I expect it to save my content but under a different name. Inetead it saves an empty page.

**Comment by JonFerraiolo** [comment] 2013-02-26 14:44
@megaD - oh, I didn't understand. Any chance you could send me (inside of a ZIP) the source code of the file that ends up with an empty page after a Save As operation? (email: jonferraiolo (at) gmail.com)

**Comment by megaD** [comment] 2013-02-26 17:59
This is what happens (video): http://screencast.com/t/k4KEdrG6xfd

Sending you the source html file.

**Comment by megaD** [comment] 2013-02-26 18:11
Also just realized when I close Maqetta and open it again the file that was "saved as" is not empty but right after "saving as" it just looks like that.

**Comment by JonFerraiolo** [comment] 2013-02-26 23:39
@peller @jhpedemonte 

@megaD - Got your file, thanks. I uploaded it to my account on maqetta.org and found that I could reproduce the blank page problem with Firefox, but not with Chrome - when I tried the Save As operation on Chrome, the page appeared re-appeared after the Save As operation. 

With the file from @megaD, there are no console messages. Looking at the console, the PUT operation for the new file happens (which is why the file appears correctly when reopened), but the GET that happens soon after to retrieve the new file contents from the server comes up with zero length:

```
PUT http://app.maqetta.org/maqetta/cmd/setWorkbenchState 200 OK 3.91s   
GET http://app.maqetta.org/maqetta/cmd/createResource?path=.%2Fproject1%2Ffile30g.html 200 OK 3.91s 
PUT http://app.maqetta.org/maqetta/cmd/setWorkbenchState 200 OK 5.28s   
PUT http://app.maqetta.org/maqetta/project1/file30g.html 200 OK 5.27s   
GET http://app.maqetta.org/maqetta/user/B/ws/workspace/project1/file30g.html 200 OK 4.92s   
PUT http://app.maqetta.org/maqetta/cmd/setWorkbenchState 200 OK 2.54s   
GET http://app.maqetta.org/maqetta/user/B/ws/workspace/project1/themes/claro/document.css 200 OK 66ms   
GET http://app.maqetta.org/maqetta/user/B/ws/workspace/project1/themes/dijit/themes/claro/document.css 200 OK 18ms  
```

We noticed a similar problem ourselves a few weeks ago and logged this issue: #3703. We made some code changes that might result in this Save As problem going away, but we need to post a build on a server with slow network response to see if those fixes did in fact address the problem. (I expect those fixes didn't address the problem and we have more fixing to do.)

**Comment by JonFerraiolo** [comment] 2013-04-09 21:51
@megaD - We have fixed some things in this area of the code (e.g., #3703 seems to be fixed), and I was going to test the latest build with the HTML file that you sent me, but I can't find that file. Any chance you could send the file to me again? (jonferraiolo (at) gmail.com)

**Comment by JonFerraiolo** [comment] 2013-04-16 14:47
Closing - didn't receive file from @medaD, and files we have in hand are working.

**Closed as completed by JonFerraiolo** 2013-04-16 14:47 UTC
Labels: Priority High, Severity 2
