### ISSUE TITLE
Deleting html file in Files when open in editor doesn't delete

### ISSUE THREAD

**Issue by wnm3** [maqetta/maqetta#1618] opened 2012-01-20 18:46 UTC
If I've opened a file in the editor (double click html file in Files) and then I select that file in Files and select Delete (X icon) it is removed from the list of files in the Files / WebContent (eclipse based project) but the file remains there even though the editor closes the file just deleted.  You can see this by opening another file and attempting to Save As to the name of the file just attempted to be deleted -- you'll get an error dialog that the file exists (might be nice to provide an "Overwrite" button on this dialog).  If you stop and restart the browser, the "deleted" file is displayed again.

If you don't open the file and just delete it, then it is gone and you can then open another file, and then Save As to the deleted file's name.

**Comment by JonFerraiolo** [comment] 2012-01-20 23:42
Is this a dupe of #1538?

**Comment by wnm3** [comment] 2012-01-21 15:27
Not really, it seems to be almost the opposite.  The problem I'm reporting is the file shows deleted in the Files list, but it has not been deleted and restarting Maqetta will show it is there, as will trying to save another file to the same name.  I'd thought the open editor was closed by the delete action (which contradicts the request in 1538), but I may have been wrong about the editor being closed.

Create a file.
Create another file.
Open the first file in an editor.
While open, delete that file from the files list (it should disappear from the list as though it was deleted).
Open the 2nd file and try to save it as the name of the first file. It complains the file exists (would be nice to have an overwrite option on this dialog).
Close the browser running Maqetta and reopen Maqetta in a new browser session. The deleted file is still there.

**Comment by childsb** [comment] 2012-03-05 21:51
Thanks for submitting this issue.  I can't point to a specific checkin that fixes it, but we've done rework around resource handling and I've verified that this is resolved in the upcoming M5 release.

**Closed as completed by childsb** 2012-03-05 21:51 UTC
Labels: Files View, Priority Med
