### ISSUE TITLE
Download as ZIP not working for localhost

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#1015] opened 2011-09-16 13:31 UTC
@jhpedemonte, @peller

I'm seeing problems with Mac/Chrome but not Mac/FF.

I was running both from Eclipse and the download ZIP (http://maqetta.org/downloads), and in both cases when I try the download as ZIP icon, instead of creating a ZIP, the URL bar shows what is listed below:

No problem with download as ZIP on the web version hosted at Maqetta.org.

```
http://localhost:50000/maqetta/cmd/download?fileName=aad.zip&root=project1&resources=%5B%22./project1%22%2C%22./project1%22%2C%22./project1%22%2C%22./project1%22%2C%22./project1%22%2C%22./project1%22%2C%22./project1%22%2C%22./project1%22%2C%22./project1%22%5D&libs=%5B{%22id%22%3A%22maqetta%22%2C%22version%22%3A%220.3%22%2C%22root%22%3A%22%22%2C%22includeSrc%22%3Atrue}%2C{%22id%22%3A%22dojo%22%2C%22version%22%3A%221.7%22%2C%22root%22%3A%22lib/dojo%22%2C%22includeSrc%22%3Atrue}%2C{%22id%22%3A%22DojoThemes%22%2C%22version%22%3A%221.7%22%2C%22root%22%3A%22themes%22%2C%22includeSrc%22%3Atrue}%2C{%22id%22%3A%22html%22%2C%22version%22%3A%220.8%22%2C%22root%22%3A%22lib/html%22%2C%22includeSrc%22%3Atrue}%2C{%22id%22%3A%22jquery-ui%22%2C%22version%22%3A%221.8.11%22%2C%22root%22%3A%22lib/jquery-ui%22%2C%22includeSrc%22%3Atrue}%2C{%22id%22%3A%22yui%22%2C%22version%22%3A%222.8.2r1%22%2C%22root%22%3A%22lib/yui%22%2C%22includeSrc%22%3Atrue}%5D
```

**Comment by childsb** [comment] 2011-09-28 14:45
i can't/couldn't reproduce this, but i suspect whatever the odd case is it was fixed with commit 8eecd4bafe9a22e97d75f718d436d52c333a9cb4

please reopen if you notice this again, or if there is more steps to recreate.

**Closed as completed** 2011-09-28 14:44 UTC
Labels: Priority High
