### ISSUE TITLE
GridX exception when to jsonp data stores

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3254] opened 2012-09-05 15:12 UTC
Running the GridX basic test case oJSONP on FF/win

Continuing from the test case above, open the HTML File from the Data from workspace test case.
Double click on the GridX Widget in the design view to display the smart input.
SmartInput is displayed. Choose Data from URL (JSONP) from the drop down list on the first panel.
In the text area enter the following URL: http://maqettaservice.appspot.com/sampleservice
Click the Finish button on the wizard.
The GridX should be updated with the data from the service. Notice that the data is displayed with HTML tags rendered (for example Fruits).
Save and close the file.
Reopen the file
Click on the preview icon in the toolbar, this should open a new browser window and the grid should be displayed with the data from the service.
Continuing with the file above.
Open the Dojo Controls folder in the Widget palette.
Drag a 2nd GridX widget onto the canvas.
SmartInput is displayed. Choose Data from URL (JSONP) from the drop down list on the first panel.
In the text area enter the following URL: http://maqetta.org/sampleService
Click the Finish button on the wizard.
The GridX should be updated with the data from the service.
Save and close the file.
Reopen the file
Click on the preview icon in the toolbar, this should open a new browser window and the grid should be displayed with the data from the service.

Reloading the page I get the red screen of death

h oh! An error has occurred:
_1896 is undefined
file: https://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@
line: 34860

@https://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:34860
@https://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:34856
@https://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:38673
@https://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:31787
@https://app.moketta.org/maqetta/app/metadata/dojo/1.8/dojox/grid/DataGridHelper.js?@revision@:128
@https://app.moketta.org/maqetta/app/metadata/dojo/1.8/dojox/grid/DataGridHelper.js?@revision@:99
@https://app.moketta.org/maqetta/app/dojo/dojo.js?@revision@:6549
@https://app.moketta.org/maqetta/app/metadata/dojo/1.8/dojox/grid/DataGridHelper.js?@revision@:102
@https://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:39050
@https://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:47950
@https://app.moketta.org/maqetta/app/dojo/dojo.js?@revision@:6439
@https://app.moketta.org/maqetta/app/dojo/dojo.js?@revision@:2134
@https://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:48658
@https://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:48656
@https://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:47886
@https://app.moketta.org/maqetta/app/dojo/dojo.js?@revision@:6950

**Comment by aerwin** [comment] 2012-09-05 15:32
@billreed63  Do you have the HTML source causing the red screen of death?

**Comment by billreed63** [comment] 2012-09-05 17:13
It looks like the 2nd data store is after the table that uses it. 

```

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dojox/io/xhrScriptPlugin",
  "dojo/data/ItemFileReadStore",
  "gridx/Grid",
  "gridx/core/model/cache/Async",
  "dojox/data/CsvStore"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "lib/dojo/gridx/resources/claro/Gridx.css";@import "lib/dojo/gridx/resources/claro/Gridx_rtl.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
<script type="text/javascript">
require(["dojox/io/xhrScriptPlugin"],function(xhrScriptPlugin){
    xhrScriptPlugin("http://maqettaservice.appspot.com/sampleservice","callback");
    xhrScriptPlugin("http://maqetta.org/sampleService","callback");
});
</script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
<span data-dojo-type="dojo.data.ItemFileReadStore" id="ItemFileReadStore_1" jsId="ItemFileReadStore_1" url="http://maqettaservice.appspot.com/sampleservice"></span>
<table data-dojo-type="gridx.Grid" style="min-width: 1em; min-height: 1em; width: 100%; height: 300px;" data-dojo-props="cacheClass: 'gridx/core/model/cache/Async',structure:[{width:'auto',name:'ID',field:'id'},{width:'auto',name:'name',field:'name'},{width:'auto',name:'numberOfItems',field:'numberOfItems'}],store:ItemFileReadStore_1"></table>
<table data-dojo-type="gridx.Grid" style="min-width: 1em; min-height: 1em; width: 100%; height: 300px;" data-dojo-props="cacheClass: 'gridx/core/model/cache/Async',structure:[{width:'auto',name:'ID',field:'id'},{width:'auto',name:'name',field:'name'},{width:'auto',name:'numberOfItems',field:'numberOfItems'}],store:ItemFileReadStore_2"></table>
<span data-dojo-type="dojo.data.ItemFileReadStore" id="ItemFileReadStore_2" jsId="ItemFileReadStore_2" url="http://maqetta.org/sampleService"></span></body>
</html>
```

**Comment by aerwin** [comment] 2012-09-05 17:14
@billreed63 

Just used FF/Mac & FF/Win and couldn't reproduce. Could you try again?

Here's the HTML source:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dojox/io/xhrScriptPlugin",
  "dojo/data/ItemFileReadStore",
  "gridx/Grid",
  "gridx/core/model/cache/Async",
  "dojox/data/CsvStore"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "lib/dojo/gridx/resources/claro/Gridx.css";@import "lib/dojo/gridx/resources/claro/Gridx_rtl.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
<script type="text/javascript">
require(["dojox/io/xhrScriptPlugin"],function(xhrScriptPlugin){
    xhrScriptPlugin("http://maqettaservice.appspot.com/sampleservice","callback");
    xhrScriptPlugin("http://maqetta.org/sampleService","callback");
});
</script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
<span data-dojo-type="dojo.data.ItemFileReadStore" id="ItemFileReadStore_1" jsId="ItemFileReadStore_1" url="http://maqettaservice.appspot.com/sampleservice"></span>
<span data-dojo-type="dojo.data.ItemFileReadStore" id="ItemFileReadStore_2" jsId="ItemFileReadStore_2" url="http://maqetta.org/sampleService"></span><table data-dojo-type="gridx.Grid" style="min-width: 1em; min-height: 1em; width: 100%; height: 300px;" data-dojo-props="cacheClass: 'gridx/core/model/cache/Async',structure:[{width:'auto',name:'ID',field:'id'},{width:'auto',name:'name',field:'name'},{width:'auto',name:'numberOfItems',field:'numberOfItems'}],store:ItemFileReadStore_1"></table>
<table data-dojo-type="gridx.Grid" style="min-width: 1em; min-height: 1em; width: 100%; height: 300px;" data-dojo-props="cacheClass: 'gridx/core/model/cache/Async',structure:[{width:'auto',name:'ID',field:'id'},{width:'auto',name:'name',field:'name'},{width:'auto',name:'numberOfItems',field:'numberOfItems'}],store:ItemFileReadStore_2"></table>
</body>
</html>

```

**Comment by aerwin** [comment] 2012-09-05 17:21
@billreed63 Didn't see your before posting mine... any idea how you managed to get the data store to appear after the table?

**Comment by billreed63** [comment] 2012-09-05 17:33
on FF 15 on https://app.moketta.org/maqetta/

DnD a GidX when SI I set the jsonp to http://maqettaservice.appspot.com/sampleservice
DnD 2nd GridX when SI set jsonp to http://maqetta.org/sampleService

Save the page and then refresh the browser (reload)

**Comment by aerwin** [comment] 2012-09-05 17:44
I upgraded my Win FF to 15 and followed your my recent steps exactly, and still no luck.

```

<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'async':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}]"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dojox/io/xhrScriptPlugin",
  "dojo/data/ItemFileReadStore",
  "gridx/Grid",
  "gridx/core/model/cache/Async",
  "dojox/data/CsvStore"
]);
</script>
<style>@import "themes/claro/document.css";@import "themes/claro/claro.css";@import "lib/dojo/gridx/resources/claro/Gridx.css";@import "lib/dojo/gridx/resources/claro/Gridx_rtl.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
<script type="text/javascript">
require(["dojox/io/xhrScriptPlugin"],function(xhrScriptPlugin){
    xhrScriptPlugin("http://maqettaservice.appspot.com/sampleservice","callback");
    xhrScriptPlugin("http://maqetta.org/sampleService","callback");
});
</script>
</head>
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
<span data-dojo-type="dojo.data.ItemFileReadStore" id="ItemFileReadStore_1" jsId="ItemFileReadStore_1" url="http://maqettaservice.appspot.com/sampleservice"></span>
<span data-dojo-type="dojo.data.ItemFileReadStore" id="ItemFileReadStore_2" jsId="ItemFileReadStore_2" url="http://maqetta.org/sampleService"></span><table data-dojo-type="gridx.Grid" style="min-width: 1em; min-height: 1em; width: 100%; height: 300px;" data-dojo-props="cacheClass: 'gridx/core/model/cache/Async',structure:[{width:'auto',name:'ID',field:'id'},{width:'auto',name:'name',field:'name'},{width:'auto',name:'numberOfItems',field:'numberOfItems'}],store:ItemFileReadStore_1"></table>
<table data-dojo-type="gridx.Grid" style="min-width: 1em; min-height: 1em; width: 100%; height: 300px;" data-dojo-props="cacheClass: 'gridx/core/model/cache/Async',structure:[{width:'auto',name:'ID',field:'id'},{width:'auto',name:'name',field:'name'},{width:'auto',name:'numberOfItems',field:'numberOfItems'}],store:ItemFileReadStore_2"></table>
</body>
</html>
```

I am in a new project I created after the workspace reset this morning... could that make a difference?

**Comment by aerwin** [comment] 2012-09-06 17:58
@billreed63 

Closing... Bill tried with fresh build and workspace and can't reproduce. From ST he said: "works now, must have been https ".

**Comment by aerwin** [comment] 2012-09-10 19:47
--> Reopening

I got the GridX (basic) test case to run today and was able to replicate using Chrome on Mac going to staging server...

The key is the save/reopen between the first GridX and the 2nd GridX...
1. New HTML file
2. GridX with JSONP pointing at ttp://maqettaservice.appspot.com/sampleservice
3. Save, close, reopen*\* NOTE: Key step... if skip, problem doesn't occur.
4. Reopen file
5. Drag 2nd GridX with JSONP pointing at http://moketta.org/sampleService.php
6. Save, close, reopen
7. See red screen of death

We need to figure out why the 2nd data store comes after the 2nd GridX just because the file had been reopened in Step 3.

But, there's really no reason we should see a red screen of death. If I preview the page, it works (except of course the 2nd GridX says "loading...") rather than showing data.

**Comment by aerwin** [comment] 2012-09-10 19:48
Exception from red screen of death:

```
TypeError: Cannot read property 'elementType' of undefined
    at _1878.addChild (http://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:34854:9)
    at _1878.insertBefore (http://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:34850:6)
    at _1bb7.addChild (http://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:38671:18)
    at _1677.execute (http://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:31781:7)
    at _1._reparentTheStore (http://app.moketta.org/maqetta/app/metadata/dojo/1.8/dojox/grid/DataGridHelper.js?@revision@:128:5)
    at _1.create (http://app.moketta.org/maqetta/app/metadata/dojo/1.8/dojox/grid/DataGridHelper.js?@revision@:99:6)
    at Object.ret.withDoc (http://app.moketta.org/maqetta/app/dojo/dojo.js?@revision@:6549:13)
    at _1.create (http://app.moketta.org/maqetta/app/metadata/dojo/1.8/dojox/grid/DataGridHelper.js?@revision@:96:6)
    at _1bb7.attach (http://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:39048:7)
    at _2246.attach (http://app.moketta.org/maqetta/app/davinci/davinci.js?@revision@:47949:7)
```

**Comment by aerwin** [comment] 2012-09-10 21:16
@doronrosenberg @jhpedemonte @JonFerraiolo @billreed63 

Lots of stuff below, but in the end I don't have a real warm fuzzy about resolving this in the _very_ short window left for M7... and I also have some suspicions we're running into some side effects of #2910 which won't be resolved until Dojo 1.8.1... thoughts appreciated...

---

I don't really know the reparent code, but thought I'd at least look to see if something easy could be done to head off the RSOD... 

I ran locally and got the following RSOD stack trace with line numbers in the source:

```
TypeError: Cannot read property 'elementType' of undefined
    at declare.addChild (http://localhost:8081/maqetta/app/davinci/html/HTMLElement.js?@revision@:364:16)
    at declare.insertBefore (http://localhost:8081/maqetta/app/davinci/html/HTMLElement.js?@revision@:358:8)
    at declare.addChild (http://localhost:8081/maqetta/app/davinci/ve/_Widget.js?@revision@:202:23)
    at declare.execute (http://localhost:8081/maqetta/app/davinci/ve/commands/ReparentCommand.js?@revision@:47:13)
    at declare._reparentTheStore (http://localhost:8081/maqetta/app/metadata/dojo/1.8/dojox/grid/DataGridHelper.js?@revision@:187:11)
    at declare.create (http://localhost:8081/maqetta/app/metadata/dojo/1.8/dojox/grid/DataGridHelper.js?@revision@:156:11)
    at Object.ret.withDoc (http://localhost:8081/maqetta/app/dojo/_base/window.js?@revision@:121:20)
    at declare.create (http://localhost:8081/maqetta/app/metadata/dojo/1.8/dojox/grid/DataGridHelper.js?@revision@:153:9)
    at declare.attach (http://localhost:8081/maqetta/app/davinci/ve/_Widget.js?@revision@:783:11)
    at declare.attach (http://localhost:8081/maqetta/app/davinci/ve/Context.
```

The source when loading the page is as such (not 2nd data store comes _after_ 2nd GridX):

```
<body class="claro" data-maq-flow-layout="true" data-maq-ws="collapse" id="myapp" data-maq-appstates="{}">
<span data-dojo-type="dojo.data.ItemFileReadStore" id="ItemFileReadStore_1" jsId="ItemFileReadStore_1" url="http://maqettaservice.appspot.com/sampleservice"></span>
<table data-dojo-type="gridx.Grid" style="min-width: 1em; min-height: 1em; width: 100%; height: 300px;" data-dojo-props="cacheClass: 'gridx/core/model/cache/Async',structure:[{width:'auto',name:'ID',field:'id'},{width:'auto',name:'name',field:'name'},{width:'auto',name:'numberOfItems',field:'numberOfItems'}],store:ItemFileReadStore_1"></table>
<table data-dojo-type="gridx.Grid" style="min-width: 1em; min-height: 1em; width: 100%; height: 300px;" data-dojo-props="cacheClass: 'gridx/core/model/cache/Async',structure:[{width:'auto',name:'ID',field:'id'},{width:'auto',name:'name',field:'name'},{width:'auto',name:'numberOfItems',field:'numberOfItems'}],store:ItemFileReadStore_2"></table>
<span data-dojo-type="dojo.data.ItemFileReadStore" id="ItemFileReadStore_2" jsId="ItemFileReadStore_2" url="http://maqetta.org/sampleService"></span></body>
```

And, it looks to me that the reparent code is kicking in and trying to move the last data store before the GridX (which makes some sense).

I stepped through the code to the point below and thought everything seemed kind of reasonable up to here, but once here I noticed the `_srcElement` for the data store that's being moved is undefined:

![GitHub Logo](http://i.imgur.com/8tco7.png)

This would then naturally lead to the exception in `HTMLElement`. I suppose the srcElement could be empty because it hasn't been fully initialized by the time GridX tries to reparent it?

---

I've also been wondering how much the endless iframe exceptions (a Dojo bug related to JSONP discussed in #2910) influences this overall scenario. And, I noticed the children of the body element contains one of those weird iframes:

![GitHub Logo](http://i.imgur.com/peSbi.png)

That could explain why the data store and grid get out of order to start with (prior to the RSOD).

**Comment by aerwin** [comment] 2012-09-10 21:18
forgot to actually reopen... :)

**Comment by doronrosenberg** [comment] 2012-09-10 21:44
Does this happen when you use the sample json file?

**Comment by aerwin** [comment] 2012-09-10 21:46
No, only if first GridX uses JSONP. I've discovered 2nd GridX can use just default data.

**Comment by aerwin** [comment] 2012-09-10 23:04
Decided to forget the RSOD symptoms for a bit, and dive into why the data store is being placed after the GridX in the first place... and still no clear cause yet.... my theory had been that the presence of the iframe for JSONP was perhaps causing some miscalculation in regard to where the data store should be inserted into the dom, but that does not appear to be the case...
- New HTML page
- Drag GridX onto page, point at JSONP URL (e.g., http://maqettaservice.appspot.com/sampleservice), click Finish
- Save, close, and reopen
- Drag 2nd GridX onto page
- Inspect source and note looks fine (2nd data store comes before 2nd GridX)
- Open GridX smart input again
- Click finish
- I have break points in place including one in `DataGridHelper._reparentTheStore` which creates a ReparentCommand... just before the ReparentCommand is executed, the 2nd data store is the 1st element in the list of  children for the dataGridParent (where dataGridParent is the body)

![GitHub Logo](http://i.imgur.com/5R6wN.png)
- After the command is executed, the 2nd data store has moved to index 2 just before the iframe (which is just before the 2nd GridX): 

![GitHub Logo](http://i.imgur.com/PAXzW.png)
- So, everything still seems right. But, then when I let execution run and check the source, the data store comes _after_ the GridX... so, I still don't know what's moving it

**Comment by aerwin** [comment] 2012-09-10 23:58
Followed this all the way to the end of the execution of the CompoundCommand executed by the GridWizard (which causes the aforementioned ReparentCommand to execute along the way) and the children of the html body still look right all the way to the end:

![GitHub Logo](http://i.imgur.com/1e8Bk.png)

So, still a bit flabbergasted... seems like source that doesn't match the model is getting written out somehow which doesn't really make sense.

**Comment by doronrosenberg** [comment] 2012-09-11 02:32
@jhpedemonte @JonFerraiolo Talking with @aerwin, this is related to #3328.  DataGridHelper::create does a reparent, and that is a bad thing to do.  This breaks things since it will get called while another compound command is being run.  That compound command isn't expecting things to move around that it didn't handle. In this case we are creating the datagrid and associated model, but the model is being moved in the helper create() before the datagrid creation compound has finished.

I think this issue (the patch for #3328 isn't that evil, but needs testing) might warrant a 1 day pushback on the M7 release or at lease a scrumm discussion.  Same fix makes my bug (#3345) go away too.

**Comment by aerwin** [comment] 2012-09-11 03:11
@jhpedemonte @JonFerraiolo @doronrosenberg 

I had a brief discussion with @jhpedemonte via ST and I think he was of the opinion that because of the uncertainty in the fix described by @doronrosenberg  above that we should defer this and the other related issues to M8.

So, pushing to M8.

**Comment by doronrosenberg** [comment] 2012-09-12 15:45
@JonFerraiolo @jhpedemonte m7.01

**Comment by doronrosenberg** [comment] 2012-09-13 19:46
@aerwin I checked in the fix for my bug and removed the reparent in GridX, can you verify this is fixed

**Comment by aerwin** [comment] 2012-09-13 20:25
-> Closing

Thanks, @doronrosenberg ... I had been looking at this some this afternoon as well and the one thing I noticed is that by removing the reparent from create that the data store for the 2nd GridX winds up at the very top of the DOM (above even the 1st data store).

So, I've done a follow on commit (see 8a0b53f0cacfc1d2c86c1b0a0436b9a8b7691fa3 ) to address that. So, now I think we can close this out.

**Closed as completed by aerwin** 2012-09-13 20:25 UTC
Labels: Regression, Priority Critical, Severity 1
