### ISSUE TITLE
Cloning theme hangs Chrome/Mac

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1479] opened 2012-01-05 21:39 UTC
While testing on lab9:50010, I tried to clone "claro".  But the browser (Chrome 16/Mac) kept hanging on me.  @childsb  was able to reproduce as well.

@billreed63 could not, using Chrome/Win (both version 16 and 17).

For now, opening this issue to track this, but I'm not sure if there's anything we can do if it's a bug in Chrome/Mac.

@JonFerraiolo @peller

**Comment by peller** [comment] 2012-01-05 22:20
the whole browser?  Can you use the Chrome menus or close the window?

**Comment by jhpedemonte** [comment] 2012-01-05 22:33
No, hangs that one page/tab.  However, sometimes I can't even close the tab -- I have to force quit the browser and restart.

**Comment by peller** [comment] 2012-01-05 22:37
I've seen that behavior a lot on lab9, in general.  I wrote it off to firewall weirdness.  In the network panel, I saw requests with response codes missing, etc.

**Comment by jhpedemonte** [comment] 2012-01-05 22:56
When I look at my network panel, I see a lot of pending requests which never finish.  Not sure if that's a cause or a side-effect of the issue.

The first 4 such pending requests have an odd path structure:  `http://lab:50020/maqetta/.%2Fproject1%2Fthemes%2Fclaro2%2Fclaro2.theme`

Before that, I see some REST calls which (1) copy claro to claro2, (2) delete `claro2/claro.theme`, (3) create `claro2/claro2.theme`, (4) rename `claro.css` to `claro2.css`.  (Not sure why we do (2) and (3); why not just do a rename?)  But all that seems fine.

I checked the server log, but there's nothing there.

**Comment by billreed63** [comment] 2012-01-05 23:01
I still can't reproduce this on FF lab9. Is this on your local machine? Can you zip the workspace so I could load it on my machine and see...

**Comment by jhpedemonte** [comment] 2012-01-05 23:37
No, Brad and I both reproduced this on lab9.  Again, this looks specific to Chrome/Mac.

**Comment by peller** [comment] 2012-01-06 02:18
So when the conditions are right, over my VPN link, I've seen this problem just loading Maqetta on lab9.  I suggest closing this issue.

**Comment by billreed63** [comment] 2012-01-06 16:14
Wayne says on Mac/Chrome
Try, 
open desktop theme editor 
log off
log back in

**Comment by jhpedemonte** [comment] 2012-01-09 21:32
Retested running the latest build locally and couldn't reproduce.  But still seeing issue on lab9:50020.  Could be a fix from today "fixed" this issue?  I'll retest tomorrow morning, when a new build will be deployed to lab9.

**Comment by peller** [comment] 2012-01-10 00:27
that would also be consistent with it being a network condition.  I've seen it come and go.

**Comment by jhpedemonte** [comment] 2012-01-10 01:32
While it might be network/timing related, ultimately it's still a Chrome bug -- it shouldn't hang the page/browser (unless there's some infinite or long-running loop in JS, which doesn't seem to be the case here).

**Comment by jhpedemonte** [comment] 2012-01-10 20:38
Retested on lab9:50020 today and still seeing this issue.  I had the console open and I did see this error:

> Failed to find States.js script tag.  States and dojox.mobile widgets may not work properly.

This comes from Context.js, as page is being loaded.  So it's making it that far, but then gets stuck somewhere.

---

Oh well, nothing to be done for now.  Pushing to M5.

**Comment by jhpedemonte** [comment] 2012-02-17 18:55
Chrome is now up to version 17.0.34982793975890580728140796389063896.  I tried this again and, while it got further (I saw the cloned theme tab come up), it still hung.

**Comment by billreed63** [comment] 2012-02-20 20:37
fixed I hope...

**Closed as completed by billreed63** 2012-02-20 20:37 UTC
Labels: Theme Editor, Priority High
