### ISSUE TITLE
Close and reopen with two Views causes silhouette to be blank

### ISSUE THREAD

**Issue by cindyskach** [maqetta/maqetta#764] opened 2011-07-21 14:24 UTC
Basically I did the steps from the tutorial up to the second bullet in the "Assembling the alerts view" section and then saved, closed and reopened.
- new HTML file
- choose iPhone silhouette
- drop View onto canvas
- drop Heading onto View and call it "Heading1"
- in the outline palette, select the eye to the left of the View to hide it
- drop another View onto the canvas
- drop a Heading onto View and call it "Heading2"
  - At this point the first View (with Heading1") should have a closed eye next to it and the second view should have an open eye.
- save, close and reopen

The iPhone is blank. If you switch between the two Views in the outline, it does not fix the problem. If you select the eye beside the second view to close it and then reopen it, you can then see the contents of the second View.

Tested in Windows/FF
lab14 build
Version: Preview 2
Date: Jul 21, 2011 7:02:02 AM
Build: 09fca203d8fe228...

**Comment by JonFerraiolo** [comment] 2011-07-21 14:36
@jhpedemonte, @peller

Yeah, this is a known problem. Closing as dupe of #459. I think we need to educate users with the M2 release about View visibility issues and hold off trying to do anything automatic until M3. The problems identified in this bug is one of the big things we will address with M3.

**Closed as completed by JonFerraiolo** 2011-07-21 14:36 UTC
Labels: Mobile
