### ISSUE TITLE
Existing File Removed from Files View

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#1491] opened 2012-01-07 17:46 UTC
Environment: Chrome with downloaded GitHub-only build
1. Create new file (e.g., tony.html) and note file is shown in tree in Files View
2. Click X on the new file to close it and hit OK so that changes are _no_t saved
3. Note new file (e.g. tony.html)  removed from tree in Files View
4. Try to create file with the same name (e.g., tony.html) and get error that file already exists (even though not in Files View)

NOTE: I confirmed file exists from original creation by reloading Maqetta and noticing the file again appears within the Files View.

**Comment by JonFerraiolo** [comment] 2012-01-07 18:53
I wasn't able to recreate this running from lab9:50020. Question to @aerwin  - Did you ever save tony.html, or was this a case of a new file that was never saved? I set this to Priority-High for time being because we don't want to ship with this sort of a bug.

One more thing - were you doing anything with folders?

**Comment by aerwin** [comment] 2012-01-07 19:36
@JonFerraiolo Weird.... I was also not able to recreate with the lab9:50020 server. So, then I started fresh on my local system and can no longer reproduce there either. Must have somehow gotten my project in a weird state when I was seeing the problem, but not sure how I did that. So, I guess I'll close this, but keep my eyes open for it happening again.

**Comment by JonFerraiolo** [comment] 2012-01-07 19:55
@aerwin We have some pending bugs in this area. @jhpedemonte came up with one way to recreate that is in a different bug report. I was planning to study the resource, runtime and Files palette code in next couple of days to see if there are obvious bugs for which there are relatively safe fixes.

**Comment by aerwin** [comment] 2012-01-07 19:58
@JonFerraiolo Ok... still can't reproduce on the lab9:50020 server, but found a set of steps using local install that reproduces it...
1. Delete users directory and restart server
2. New HTML file (file1.html)
3. New CSS file (file1.css)
4. Close file1.css without saving
5. New CSS file (file1.css) fails with "File already exists" dialog

From this point, it appears you can reproduce the orignally reported problem at will.

Build level:
Version: Preview 4
Date: Jan 6, 2012 12:32:26 PM
Build: 5c5b769e17f129b...

**Comment by childsb** [comment] 2012-01-09 16:51
i can't recreate this on local or lab9

**Comment by aerwin** [comment] 2012-01-09 17:06
Hmmm... just recreated on local using build I just downloaded this morning...

Version: Preview 4
Date: Jan 8, 2012 10:02:24 PM
Build: f5b8f94efd1d7b2...

**Comment by JonFerraiolo** [comment] 2012-01-09 21:07
@aerwin - could you try this again with latest code? I just pull'd everything and couldn't reproduce when launching from Eclipse.

**Comment by aerwin** [comment] 2012-01-09 21:15
@JonFerraiolo Yes, appears to still happen with the build I just downloaded a bit ago:

Version: Preview 4
Date: Jan 9, 2012 2:12:26 PM
Build: e57f533dce68662...

**Comment by childsb** [comment] 2012-01-10 15:58
the resource.delete() call was failing on the removeWorkingCopy command only on windows.  

Googling around, i found that there are some known short comings of the file.delete() and some people found forcing java garbage collection fixes it.  It seems to work for us too.

I tested on my windows box, but @aerwin please try again on the next built.

**Comment by aerwin** [comment] 2012-01-11 01:33
Still happens on RC build...

Version: Preview 4
Date: Jan 10, 2012 2:58:23 PM
Build: 3c236b1c2ec48a5...

**Comment by childsb** [comment] 2012-01-11 16:01
moving to m5

**Comment by childsb** [comment] 2012-03-02 18:02
The problem is on Windows--

When we create files on the server, we skip over writing if the content length = 0.

For some reason, just getting a URLConnection on windows then not writing anything would cause the JVM to lock the file in the thread.  This resulted in any file.delete() to fail (and leave the file on the file system).

I changed the code to write 0 bytes and set content length to 0 for empty files.  This resolved the file lock.

**Closed as completed by childsb** 2012-03-02 18:02 UTC
Labels: Files View, Priority High

**Comment by aerwin** [comment] 2012-03-08 23:06
Confirm this is fixed in latest.
