### ISSUE TITLE
VE3 Test: snap line always comes from left side of reference widget

### ISSUE THREAD

**Issue by waynevicknair** [maqetta/maqetta#1505] opened 2012-01-09 18:37 UTC
testing on Mac/Safari

Steps:
1) create a new HTML file of composition type to "Desktop hi-fi sketch"
2) drag a Calendar widget to roughly the center of the canvas
3) drag a Button widget onto canvas 

Result:
notice that as you drag the Button towards the Calendar from the left the snap line comes from the left side of the Calendar.
continue to drag the Button around the Calendar and you will notice that when the Button is on the right side of the Calendar, 
the snap line comes across the Calendar from the left.

**Comment by aerwin** [comment] 2012-07-16 19:48
--> no milestone to M7

**Comment by JonFerraiolo** [comment] 2012-08-26 00:57
Closing. Can't reproduce, and I know I put fixes into the snap logic since this issue was created 8 months ago.

**Closed as completed by JonFerraiolo** 2012-08-26 00:57 UTC
Labels: Bug, Priority Low, Severity 3
