### ISSUE TITLE
Bordercontainer smartinput exception when opened

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2902] opened 2012-08-09 03:25 UTC
```
Error: Tried to register widget with id==dijit_layout_BorderContainer_2 but that id is already registered
```

Odd one

**Comment by jhpedemonte** [comment] 2012-08-09 03:37
The error doesn't seem to cause any issues, but we should definitely investigate.

**Comment by aerwin** [comment] 2012-08-09 03:54
Is this the same as ##2850 ?

**Comment by jhpedemonte** [comment] 2012-08-09 03:57
Dupe of #2850.

**Closed as completed by jhpedemonte** 2012-08-09 03:57 UTC
Labels: Priority Med, Regression, Severity 4
