### ISSUE TITLE
Clip art added to a sketch when a state is selected should default to visibility for that state 

### ISSUE THREAD

**Issue by billreed63** [maqetta/maqetta#3685] opened 2013-01-23 15:46 UTC
I created a Lo-fi sketch and added some Drawing and clip art to background state.
Then I added two states item_one and item_two. 
I selected the item_one state  changed the visibility of all items to hidden. 
I then added more items to the canvas while in state item_two.
I switched state to background and all my widget from state item_two are still visible. 
I expected them to be hidden.

**Comment by JonFerraiolo** [comment] 2013-01-23 20:57
I'm going to close this issue - it's a user education issue - software working as designed.

In previous releases, whenever you added a widget, it always went to the Normal state. When I updated the states logic for M9, I didn't want to change that behavior partly because I didn't want to confuse our existing users with radically new behavior, and also my sense is that it is a better default that new users go into the background.

The reason why I think "new widgets to background" is a better default because of the scenario where a user has most everything on the background, and only a couple of things change when in a new state. If a user builds part of the background, then sets things up such that a couple of widgets only show in particular states, and then want to extend the background, they often will forget to go back to the background state before adding new widgets. Part of my thinking is that it will be easier for novice users to figure out how to move things from background to custom state than from custom state to background.

What I'm thinking is that our tutorials (which I will update before we ship M9) will walk users through all of this and explain that there is a convenience icon on the Scenes palette where you can tell Maqetta to put new widgets into the current state rather than the background, but warn them that they will be changing states fairly often, and therefore THEY NEED TO PAY ATTENTION to that icon and their current state thereafter to make sure that any widgets they create end up in the correct state.

**Closed as completed by JonFerraiolo** 2013-01-23 20:57 UTC
Labels: Visual Editor, Priority High
