### ISSUE TITLE
Set moveTo on ListItem - label text disappears

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3621] opened 2012-12-10 22:17 UTC
@jhpedemonte @billreed63 

Possibly related to #3605 and maybe related to recent addChild changes.
- New Mobile App
- Create 2 View widgets
- In first View, add a RoundRectList Item
- Attempt to set 'moveTo' property for one of the ListItems to point to the other View

Result=> label text disappears on the ListItem at the same point that the arrow icon appears

**Comment by jhpedemonte** [comment] 2012-12-11 13:03
`ListItemHelper.getChildren()` returns an array with the DIV for the moveTo icon.  The code also adds the class `HtmlWidget` to the moveTo icon node.  Oddly, though, the icon DIV does not show up in the Outline view.

Maybe we need to ignore this DIV like we do the label?

**Comment by jhpedemonte** [comment] 2012-12-11 13:07
This worked in M7 because `ListItemHelper.getChildren()` was broken and would always return an empty array.

Also note that I removed `ListItemHelper.getChildrenData()`, which at the time seemed to be unnecessary.  It may (or may not) have helped this situation.

**Comment by jhpedemonte** [comment] 2012-12-11 15:29
Above commit fixes most of this.  The remaining issue is that, after setting `moveTo`, if I click on the affected ListItem, the `moveTo` logic gets invoked, moving to the associated view.

**Comment by jhpedemonte** [comment] 2012-12-11 15:33
`ListItemHelper.create()` tries to override the `moveTo` logic.  However, it doesn't seem that `anchorNode` property is used any more.  Replace with `domNode`?  @JonFerraiolo, I think you know this area best...

**Comment by jhpedemonte** [comment] 2012-12-11 15:53
Also, Jon, if you get [that](https://github.com/maqetta/maqetta/issues/3621#issuecomment-11247948) working, test the case where you set `moveTo` and then try to add a Button into the ListItem.  It didn't seem to be working correctly for me, but it could be caused by the `moveTo` bug.

**Closed as completed** 2012-12-12 05:10 UTC
Labels: Widget Libraries, Priority High, Mobile, Severity 2
