### ISSUE TITLE
Exception dropping Heading onto mobile page

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3240] opened 2012-09-04 19:23 UTC
Using FF on Mac going to moketta...

Not sure any side affects, but making prio high for investigation....
1. Create mobile page
2. Drag view on to page
3. Drag heading onto page and click OK on smart input. See the following exception: 

```

TypeError: this.focusNode is undefined
[Break On This Error]   

if(!_2415&&this.type=="submit"&&!(this.valueNode||this.focusNode).form){

davinc...vision@ (line 50574)
```

**Comment by jhpedemonte** [comment] 2012-09-04 19:24
-> @doronrosenberg

**Comment by aerwin** [comment] 2012-09-04 19:25
Seems to happen with all mobile widgets with smart input.

**Comment by doronrosenberg** [comment] 2012-09-04 19:59
Hmm, we are calling hide twice in this case

**Comment by JonFerraiolo** [comment] 2012-09-04 20:00
I think this is a dupe of #3222. @doronrosenberg and @billreed63 need to coordinate on those two issues

**Comment by doronrosenberg** [comment] 2012-09-04 20:19
The issue is type="submit", we are destroying the button while its doing its thing

**Closed as completed** 2012-09-04 20:33 UTC
Labels: Visual Editor, Priority High, Severity 3
