### ISSUE TITLE
Slowness with Create New HTML File

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#622] opened 2011-06-29 14:45 UTC
@peller, @billreed63, @jhpedemonte, @childsb

I just launched today's build. Typing http://localhost:50000/maqetta happened quickly, but it took 12 seconds on Win/FF to go from clicking on the Create button on the New HTML File dialog to when the new editing canvas was ready to work. We need to investigate why this took so long.

**Comment by JonFerraiolo** [comment] 2011-06-29 14:50
Just did a second New HTML File and this time it took about 20 seconds with Win/FF4, so I'm assigning this to Brad for time being.

Note that the last time I tried this, I was saving into a nested directory. I had created folder1/ and then was doing a SaveAs into folder1/, but there are delays even if not using nested folders. There is a long delay with findResource on *.theme even when simply double-clicking on Sample1.html

**Comment by childsb** [comment] 2011-06-30 00:28
i can't reproduce this on osx/FF or osx/Chrome with latest build (Preview1-450-gda8bd64).  It could be a windows specific issue but i believe it was a big performance problem fixed with commit 91e357f1528b21977f87.

let me know if you still see the bug and i'll track down a windows box.

**Comment by JonFerraiolo** [comment] 2011-06-30 14:44
I'm still seeing a long wait with today's build (6-30) when doing findResource on *.theme files on Win/FF. (Due to auto-update, I'm now running Win/FF5)

**Comment by childsb** [comment] 2011-06-30 14:48
Ok i'll track down a windows box to test.

**Comment by peller** [comment] 2011-06-30 14:54
See #575 and #603 for possible dups

**Comment by jhpedemonte** [comment] 2011-07-01 05:17
So on Chrome/Mac, running daily build from June 30, it seems to me that there is a slow down in opening a file.  Although for me, it's not as bad as Jon was seeing, around the 4-5 second range.

**Comment by childsb** [comment] 2011-07-01 20:39
did a build, and looks like findResource call is down to a few milliseconds, so i think i got it fixed.  i'll test more once the git head is correct-- right now it's missing all the images so really hard to do anything.

**Comment by childsb** [comment] 2011-07-04 16:54
ok,  tested build on windows machine and seeing millisecond times for the findResource call.  closing!

**Closed as completed by childsb** 2011-07-04 16:54 UTC
Labels: Priority High, Performance
