### ISSUE TITLE
Preview in browser sometimes comes up empty

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#72] opened 2011-05-02 20:13 UTC
Intermittent. Adam, Javier and I have seen this occasionally for both Safari
and Chrome. For me, seems like the first time has troubles, but maybe it's OK
if you try the preview-in-browser button a second time.

**Comment by kspain** [comment] 2011-05-02 23:35
I've created several new files to test this - place a widget on the canvas then preview, repeat. It seems like I get to about the 5th time to preview and its blank. I'm on FF4. Closing the browser and reopening doesn't help. It seems like it's broken forever.

**Comment by skarab7** [comment] 2011-05-04 21:22
The same problem in FF4, Chrome, and Safari when running maqetta in the server mode on MacOs. In local mode everything works fine.

How to trigger the bug:
1. The way to trigger error: put a Dojox mobile RoundRect into Dojo BorderContainer (inside TabContainer), and view (preview in the browse) the tab where the containers are.
2. The error does not happen if I view the other tab after adding RoundRect to the tab1. If the error occurred it is permanent and switching tabs in edit mode does not help at all.
3. To have you page working again, you need to remove RoundRec  and -- manually -- @import "./lib/dojo/dojox/mobile/themes/iphone/iphone.css"; from the page sources

Source Code without RoundRect:

<!DOCTYPE html>
<html>
<head>
<title>Untitled</title>

<style type="text/css">
@import "themes/claro/claro.css";
@import "app.css";
@import "./lib/dojo/dojo/resources/dojo.css";
@import "./lib/dojo/dojo/resources/dojo.css";

</style>

<script type="text/javascript" src="./lib/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script>

<script type="text/javascript">
dojo.require('dijit.layout.TabContainer');
dojo.require('dijit.layout.ContentPane');
dojo.require('dijit.layout.BorderContainer');
dojo.require('dijit.form.TextBox');
dojo.require('dijit.form.Button');
dojo.require('dojox.mobile');
dojo.require('dojox.mobile.parser');</script>

<script src="maqetta/States.js"></script>

<script src="maqetta/maqetta.js"></script>

</head>
<body class="claro lotusui" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp">
<span dojoType="dijit.layout.TabContainer" style="width: 100%; height: 100%; min-width: 1em; min-height: 1em;" controllerWidget="dijit.layout.TabController">

<div dojoType="dijit.layout.ContentPane" title="t1" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="true" closable="false" style="width: 728px; height: 460px;">
  <div dojoType="dijit.layout.BorderContainer" design="sidebar" persist="false" gutters="true" style="width: 100%; height: 100%; min-width: 1em; min-height: 1em;">
    <div dojoType="dijit.layout.ContentPane" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" region="top" splitter="true" style="height: 50px;">
      <input type="text" dojoType="dijit.form.TextBox" disabled="false" readOnly="false" intermediateChanges="false" trim="false" uppercase="false" lowercase="false" propercase="false"></input>
      <input type="button" dojoType="dijit.form.Button" disabled="false" intermediateChanges="false" label="Search"></input>
    </div>
    <div dojoType="dijit.layout.ContentPane" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" region="bottom" splitter="true" style="height: 50px;"></div>
    <div dojoType="dijit.layout.ContentPane" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" region="left" splitter="true" style="width: 118px;">
    </div>
    <div dojoType="dijit.layout.ContentPane" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" region="right" splitter="true" style="width: 50px;"></div>
    <div dojoType="dijit.layout.ContentPane" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" region="center" splitter="false">
      <ul dojoType="dojox.mobile.IconContainer" defaultIcon="http://localhost:50000/maqetta/app/metadata/dojo/1.5/resources/images/icon-container-fallback.png">
        <li label="1" dojoType="dojox.mobile.IconItem" transition="below" sync="true"></li>
      </ul>
    </div>
  </div>
</div>

<div dojoType="dijit.layout.ContentPane" title="t2" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" selected="true" closable="false" style="width: 728px; height: 460px;"></div>

<div dojoType="dijit.layout.ContentPane" title="t3" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" doLayout="true" selected="true" closable="false" style="width: 728px; height: 471px;"></div>

<div dojoType="dijit.layout.ContentPane" title="t4" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" doLayout="true" selected="false" closable="false"></div>

<div dojoType="dijit.layout.ContentPane" title="t5" extractContent="false" preventCache="false" preload="false" refreshOnShow="false" doLayout="true" selected="false" closable="false"></div>

</span>
</body>
</html>

**Comment by JonFerraiolo** [comment] 2011-06-15 04:27
@peller

The common denominator causing the blank previews above are the use of dojox.mobile widgets. The browser debugging console shows messages about duplicate use of IDs by multiple dijit widgets.

We included the dojox.mobile widgets in the Preview 1 release mostly as a "vision" feature because we wanted the community to see a glimpse of where we intended to go with visual authoring of mobile UIs. This particular feature is very immature with the Preview 1 release. The Maqetta team was aware of multiple areas where the implementation was incomplete. This bug report highlights an area that of which we were not aware: preview in browser has lots of problems in Preview 1, where there is a bug where duplicate IDs are used for different widgets. If we are lucky, maybe the fix will come "for free" when up upgrade Maqetta from Dojo 1.5 to Dojo 1.7 (with more mature mobile widgets).

**Comment by kspain** [comment] 2011-06-15 05:07
FYI - while all of my current html pages have mobile widgets on them, when I first saw the issue I was using the accordion container and menu - no mobile widgets. I will try to reproduce that way.

**Comment by waynevicknair** [comment] 2011-06-30 15:48
I encountered this error in testing today on Safari 5.0.5. A refresh of the preview page causes content to appear. View source on the blank page comes up completely empty.

this is no longer intermittent; it happens every time for me. i recommend this bug's priority be raised.

**Comment by waynevicknair** [comment] 2011-07-05 16:41
oh well, i cannot reproduce this one on today's build.

**Comment by jhpedemonte** [comment] 2011-09-09 01:30
I have not seen this in a while, just the issue with Preview not loading the latest version (pulling from cache).  The latter issue is handled in #795.

Closing.  If you see this again, feel free to reopen.

**Closed as completed by jhpedemonte** 2011-09-09 01:30 UTC
Labels: Bug, Priority High

**Comment by JonFerraiolo** [comment] 2011-09-09 15:25
OK to close, but I'll add that I have seen occasional problems recently where preview-in-browser shows an incomplete rendering, but a refresh cleaned it up.

**Comment by JonFerraiolo** [comment] 2012-01-04 17:53
I just saw this problem again. Running Windows/Chrome. The very first thing I did after launching server (via localhost) was add a CheckBox and then Preview-in-Browser. Preview came up empty. Hitting refresh causes the CheckBox to appear.
