### ISSUE TITLE
Does zazl apply to reviews?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3238] opened 2012-09-04 18:53 UTC
@jhpdemonte @childsb @aerwin 

@peller: does zazl apply to the HTML files that are published for reviews? If not, we should create a Prio-High issue for M8.

**Comment by peller** [comment] 2012-09-04 18:59
Presently, maqetta.zazl.MaqettaHTMLFilter only applies to `/maqetta/user/*.html`

**Comment by peller** [comment] 2012-09-05 15:10
-> M8/High

**Comment by peller** [comment] 2012-10-16 00:32
@rbackhouse I tried turning on the MaqettaZazl filter for reviews.  Complains about the 'main' reference in dijit/dijit.  Perhaps it's not using the "source" libraries?  Where does that happen?

**Comment by rbackhouse** [comment] 2012-10-16 10:10
The Zazl Resource Loader does that. I'll take a look.

**Comment by rbackhouse** [comment] 2012-11-03 13:00
I tried this out with the maqetta.core.client/WebContent/davinci/review/editor/Context.js and maqetta.zazl/src/maqetta/zazl/HTMLParser.java changes from the 3238ReviewZazl branch (It didn't look like the other file had related changes) and review worked fine with zazl turned on.

**Comment by peller** [comment] 2012-12-06 16:08
with zazl enabled, fails now on the onload handler where it needs to use a topic in the iframe:

'''
userWindow.require("dojo/_base/connect")...
'''

@rbackhouse says that calling the global require this way is a bad thing for zazl

**Comment by rbackhouse** [comment] 2012-12-08 17:24
The  userWindow.require("dojo/_base/connect") is not the cause of the failure. I do see it when Zazl is used for review but it is not stopping the page from loading.

It looks like the url paths for reviews have changed since I tested this last. They now have a prefix like 

http://localhost:8081/maqetta/user/A/ws/workspace/.review/snapshot/2012-12-08T12:22:06Z/project1/

The date segment contain colons and is causing Zazl to not match urls correctly. I will fix Zazl to handle this. 

With Zazl handling the url encoding/decoding review works for me, however I am surprised as the Zazl Resource Loader used by maqetta is actually not handling stripping the .review segments. This results in dojo resources being loaded from the project and I would have expected them to the be the built versions but this is not the case. 

Looking at the review urls I think the Resource Loader should strip 4 segments to the get to the lib path needed to resolve to the src-lib

e.g

/.review/snapshot/2012-12-08T12:22:06Z/project1/lib/dojo/dijit/dijit.js

to 

/lib/dojo/dijit/dijit.js

Can I expect the segment count to be fixed for reviews ?

**Comment by rbackhouse** [comment] 2012-12-08 17:36
On the subject of userWindow.require("dojo/_base/connect") instead of trying to call require synchronously (which is invalid AMD) calling it asynchronously should work.

```
userWindow.require(["dojo/_base/connect"], function(userWindowConnector) {
    userWindowConnector.subscribe("/maqetta/appstates/state/changed", function(args) {

        if (!args || !Runtime.currentEditor || Runtime.currentEditor.declaredClass != "davinci.review.editor.ReviewEditor") { 
            return; 
        }
        var dv = userWindow.davinci;
        if(dv && dv.states && dv.states.setState){
            if (this._commentView) {
                this._commentView.updateStatesScenes();
            }                           
            // Re-publish at the application level
            var newArgs = dojo.clone(args);
            newArgs.editorClass = "davinci.review.editor.ReviewEditor";
            connect.publish("/maqetta/appstates/state/changed", [newArgs]);
        }
    });
});
```

With Zazl the call to subscribe appears to work without error.

**Comment by peller** [comment] 2012-12-08 17:52
Those colons in the url probably are not valid.  I thought I changed them so that they would be encoded?  (In retrospect, it would have been better to encode the dates without colons!)

**Comment by peller** [comment] 2012-12-08 17:55
I will look at stripping those segments, but that will probably have to wait until M9

**Comment by peller** [comment] 2012-12-12 21:37
@rbackhouse  Ah, sorry, I didn't parse your question correctly.  Yes, I think the number of segments in the review url will be fixed at the current number 4.  I removed the colons and dashes. (When testing, you'll have to uncomment b41d35a)

**Comment by rbackhouse** [comment] 2012-12-13 10:17
The dates in the URL are still a problem but I have fixed Zazl to handle them. We would have to upgrade the level of Zazl in maqetta. 

With the updated Zazl and the removal of 4 segments if ".review" is in the URL review works for me

**Comment by peller** [comment] 2013-01-02 03:55
@rbackhouse, Now that we're done with M8, feel free to go ahead with the zazl upgrade to remove the 4 segments for ".review".  I removed the colons from the dates in url paths, but it wouldn't hurt to tolerate them, I guess.

**Comment by rbackhouse** [comment] 2013-01-05 12:06
Zazl has been upgraded and MaqettaOSGiResourceLoader will remove 4 segments if it is a review URL. 

I uncommented out the code in Context.js and review via Zazl worked for me

**Closed as completed** 2013-01-17 04:42 UTC
Labels: Other, Priority High, Severity 3
