### ISSUE TITLE
GridX: second column disappears when opening "Grid Configuration"

### ISSUE THREAD

**Issue by gers32** [maqetta/maqetta#2472] opened 2012-06-01 13:55 UTC
Hi,

I set up a GridX widget with four columns and a few lines. Upon closing the "Grid Configuration" window, my grid looks good. But if I double-click to open "Grid Configuration" again, the second column has disappeared, from all lines!

Cheers,

Chris.

**Comment by aerwin** [comment] 2012-06-01 14:02
> @aerwin

**Comment by aerwin** [comment] 2012-06-01 14:03
Hi, could you paste in the text you used to specify the "four columns and a few lines" so I can try and reproduce?

**Comment by gers32** [comment] 2012-06-01 14:07
Wow! Quick reply!

Here's the text I put in:

Date de début,Date de fin,Code UT,Intitulé UT
03/03/2012,,UT3,Unité de Travail Trois
02/02/2011,,UT2,Unité de Travail Deux
01/01/2010,31/12/2012,UT1,Unité de Travail Un
,,,
,,,
,,,
,,,

And here's the text shown when I double-click on the grid:

Date de début,Code UT,Intitulé UT
03/03/2012,UT3,Unité de Travail Trois
02/02/2011,UT2,Unité de Travail Deux
01/01/2010,UT1,Unité de Travail Un
,,
,,
,,
,,

Thanks for your help,

Chris.
 
The best time to plant a tree is a 100 years ago. The second-best time is now.

Ignorance more frequently begets confidence than does knowledge. (Charles Darwin)

**Comment by aerwin** [comment] 2012-06-01 14:20
Hi, Chris... Great, I was able to reproduce using your data. I'll explore deeper, and keep you posted.

**Comment by aerwin** [comment] 2012-06-01 15:20
The issue is that the first row of data contained an empty cell in the 2nd column. Of course, this should be allowed, so I fixed with commit above.

In the meantime, you should be able to workaround the issue by entering a space where you had empty cells such as below:

```
Date de début,Date de fin,Code UT,Intitulé UT
03/03/2012, ,UT3,Unité de Travail Trois
02/02/2011, ,UT2,Unité de Travail Deux
01/01/2010,31/12/2012,UT1,Unité de Travail Un
```

I'm going to mark the issue as closed. But, please reopen if you see problems.

**Closed as completed by aerwin** 2012-06-01 15:20 UTC
Labels: Widget Libraries, Priority High

**Comment by gers32** [comment] 2012-06-03 20:45
Thanks for the quick answer and workaround.

Cheers,

Chris.
 
The best time to plant a tree is a 100 years ago. The second-best time is now.

Ignorance more frequently begets confidence than does knowledge. (Charles Darwin)
