### ISSUE TITLE
Right-click (context menu) should act on widget under mouse cursor

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2757] opened 2012-07-16 03:34 UTC
In the VE, right-clicking acts on an **already selected** widget, rather than that which is directly underneath the mouse cursor.

For example, New Page, add <table>, make sure nothing is selected, then right-click in a cell.  Context menu comes up but everything is disabled.  Need to first select a widget.

Now add a Button under the table.  Select one of the table cells, then right-click on the Button.  Notice that the context menu is for the table, not the button.

@JonFerraiolo @aerwin 
(Thought there was a bug for this already, but cannot find it.)

**Comment by doronrosenberg** [comment] 2012-07-16 17:49
The issue is that right clicking is not even selecting the widget.  Occurs in m6 as well

**Comment by doronrosenberg** [comment] 2012-07-16 17:50
@jhpedemonte @JonFerraiolo I assume that right clicking in VE should select the widget correct?

**Comment by JonFerraiolo** [comment] 2012-07-16 18:30
Dupe of #1543

**Comment by JonFerraiolo** [comment] 2012-07-16 18:34
> I assume that right clicking in VE should select the widget correct?

I hadn't gotten into this issue at all, but now that you mention it, yes, that's the way to do it. (I see same behavior in Word and PowerPoint.) That approach should make fixing #1543 easy.

**Comment by jhpedemonte** [comment] 2012-07-17 03:00
Actually, I'm going to reopen.  This bug is a bit more general than the other.  But #1543 deals specifically with cut/copy/paste -- and _paste_ will need to be handled specifically.

**Comment by doronrosenberg** [comment] 2012-07-17 18:07
@JonFerraiolo could you review the changes to SelectTool (d6591726a319e0f98c9aa41835f31782b935888a) for this, I believe you know this code the best.

**Closed as completed** 2012-07-17 18:06 UTC
Labels: Bug, Priority High, UX

**Comment by JonFerraiolo** [comment] 2012-07-17 20:01
Looks good!
