### ISSUE TITLE
No migrate.html for non-hosted builds?

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#3195] opened 2012-08-30 21:01 UTC
@jhpedemonte 

I see there is a migrate.html in maqetta.server.orion.hosted but not in maqetta.server.orion.standard. Is this by design?

**Comment by childsb** [comment] 2012-08-30 21:13
Yes by design.  But I suspect you want it in the standard version as well!

There is some workflow around migration.  My assumption is that any large users would write their own migrate workflow, and use the code in the hosted plugin as example.

Maybe "workspace migration" should be a first-class feature in our next releases?

**Comment by jhpedemonte** [comment] 2012-08-31 00:17
If you want to add **migrate.html** to the non-hosted version, we can do that in M8.

**Comment by jhpedemonte** [comment] 2012-11-27 13:54
-> M9

**Comment by jhpedemonte** [comment] 2013-04-12 04:42
Migration no longer supported/needed.  Closing.

**Closed as completed by jhpedemonte** 2013-04-12 04:42 UTC
Labels: Build, Priority High, Severity 2
