### ISSUE TITLE
SOON AFTER M4 RELEASE: announce account removal after 90 days inactivity

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#1471] opened 2012-01-05 17:03 UTC
We need a policy of **removing accounts** that are **inactive for a certain amount of time**.  I propose 90 days. [1]

Before enacting this policy, we need to **announce it**.  Best time would be soon after the M4 release.

[1]  I suggest **90 days** since that is a time period that would span 2 releases (assuming we keep releases every two months).  This way, a user could try a release and then come back again to see what's changed when a new build has been released.  If we start releasing with less frequency, then we'll need to up the number from 90 days. For example, if we start releasing every 3 months, then the policy would change to 120 days inactivity.

**Comment by JonFerraiolo** [comment] 2012-01-27 20:49
Closing. Dupe of #1641

**Closed as completed by JonFerraiolo** 2012-01-27 20:49 UTC
Labels: Priority High
