### ISSUE TITLE
"Error modifying value" when changing button width w/ cloned theme

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#2398] opened 2012-05-24 02:37 UTC
From testplan **Properties 4 > CSS cascade features**.

After cloning the **claro** theme and setting it as the theme on the page, I attempted to change the width of the **Button**.

But I got the same **Error Modifying Value** error dialog, saying I'm trying to update a read-only theme.  However, I clearly set it up to use my cloned theme.

Then I found I had to go into the cascade and select the first radio button, which pointed to my cloned theme files.  By default, it's set to keep using the theme files from the original, read-only theme.

---

This is confusing to the user and a regression, since before the _delta themes_ commit I could easily change the width when using the cloned theme, and I never had to go into the cascade.

Seems to me that the first radio button of the cascade (pointing to the cloned theme files) should be selected by default, allowing to change properties without getting an error dialog and without requiring going into the cascade view.

Not sure if there's anything that can be done for M6, but would be nice, given it's a regression.

@JonFerraiolo

**Comment by JonFerraiolo** [comment] 2012-05-24 13:12
Hope it's OK, but I've pushed to M7 High and assigned to me. 

I don't think this is a hugely used feature by our users (i.e., attempted to modify a cloned theme in page editor) and there is a workaround, and I fear that we might break other things if we attempt to change the logic at this point. From what I've seen, anyway, if users want to change theme styling in the page editor, they tend to go the app.css route. They will still get the global theming prompt even if we did make a change, and that's a scary dialog for the end user.

**Comment by childsb** [comment] 2012-05-24 14:56
dupe of #2369

**Comment by JonFerraiolo** [comment] 2012-08-14 00:18
-> @billreed63 I think this is fixed and working correctly, but could you please evaluate? If you think everything is working, please close.

**Comment by billreed63** [comment] 2012-08-14 14:43
working now

**Closed as completed by billreed63** 2012-08-14 14:43 UTC
Labels: Priority High, Regression, Themes, Severity 2
