### ISSUE TITLE
Changed "global" CSS rule, doesn't show in preview or when file reopened

### ISSUE THREAD

**Issue by jhpedemonte** [maqetta/maqetta#561] opened 2011-06-17 22:04 UTC
To recreate:
- Drop Dojo Button.
- Change it's background color.
- This will result in dialog warning about changing global CSS rule.  Press **OK**.

At this point, the VE will show that the background color change took effect.  However, if you load preview, or close and reopen the file, that change was not saved.

Could this be as a result of the read-only theme changes by @childsb?  If so, the dialog should be changed to something explaining that change can't happen on read-only theme, and that user will need to create a copy of the theme before applying change.

**Comment by jhpedemonte** [comment] 2011-06-21 01:40
@JonFerraiolo: Is this the same as #582?

**Comment by JonFerraiolo** [comment] 2011-06-21 21:22
Closing this. It's partly a dupe of #582 and partly a dupe of #258. Nothing original here.

**Closed as completed by JonFerraiolo** 2011-06-21 21:22 UTC
Labels: Properties View, Bug
