### ISSUE TITLE
(Orion) Login screen doesn't tell me I entered wrong password

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2949] opened 2012-08-15 18:07 UTC
@childsb 
1. Go to Orion login screen
2. Enter user name
3. Type wrong password and nothing happens except for following in console:

```
POST http://maqetta-app-test.austin.ibm.com/login/form 401 (Unauthorized) LoginWindow.js:221
confirmLogin LoginWindow.js:221
document.getElementById.onclick LoginWindow.js:415
```

**Comment by peller** [comment] 2012-08-22 14:04
I actually see an exception in the code.   Using the build on app-test, I get a 403, and the LoginWindow code attempts to parse the responseText as JSON when it's really a full HTML error page

**Comment by jhpedemonte** [comment] 2012-08-22 14:56
Duplicate of 8246 in our bugzilla.  Closing.

**Closed as completed by jhpedemonte** 2012-08-22 14:56 UTC
Labels: Priority High, UI, UX, Severity 2

**Comment by aerwin** [comment] 2012-08-22 15:01
@jhpedemonte This isn't an internal driver issue, so not sure BugZilla is right tracking mechanism. But, guess that's up to you.
