### ISSUE TITLE
GridX combined with States/Scenes seems to not show all rows

### ISSUE THREAD

**Issue by painbank** [maqetta/maqetta#2991] opened 2012-08-17 16:02 UTC
I am trying to follow this sample shown here for getting a GridX page to work.

https://www.ibm.com/developerworks/mydeveloperworks/blogs/MaqettaAuthoring/entry/adding_custom_javascript3?lang=en

This works fine on a single smaple page.

When I move to a scene page, it doesn't seem to want to show the additional rows of data.  The column headers display and change names on the dojo/ready function gets called, but for some reason, I cannot figure out how to get this to show the data.  The data appears to be attached properly, but nada for dipslay.

ideas?

**Comment by JonFerraiolo** [comment] 2012-08-17 16:16
-> @aerwin

**Comment by painbank** [comment] 2012-08-17 16:26
when I add a height:22 to the css for the <div class="gridxHeaderRow"....

this resizes the header and now once I get a refresh on the page, I can see the data rows.  btw, I could not see these bfore this.  Since this DOM div element is generated by the widget library at run time, I cannot see where else to add it.  Perhaps attaching it as it's own css property class.

also, the gridx widget is not shown on the initial state for the page, but on a subsequent state.

**Comment by aerwin** [comment] 2012-08-17 18:34
@painbank 

Hi... could you be more specific about what you mean by "When I move to a scene page, it doesn't seem to want to show the additional rows of data. "? Maybe include a sample of what you're doing?

**Comment by painbank** [comment] 2012-08-17 19:56
composite of the states.  The Home state doesn't have the GridX shown, so when you go to a new state, it should show.  side note, the proper of the GridX works inside the Editor, but doesn't not when deployed to web server.

http://imagepaste.nullnetwork.net/viewimage.php?id=4702

**Comment by aerwin** [comment] 2012-08-18 17:35
-> Making Prio High (and setting other relevant tags) so gets investigated/assessed during M7

@painbank 

Does this sound roughly like your scenario?
1. New HTML page
2. Create new state called "Grid"
3. Drag 2 Dojo buttons onto canvas
4. Drag GridX onto canvas and click Finish on page
5. In Events, choose Normal:State for onclick of first button
6. In Events, choose Grid:State for onclick of second button
7. Choose Normal state in scenes palette
8. In outline panel, close the eyeball next to GridX so that the grid is hidden in the Normal state
9. Choose Grid state in scenes palette
10. In outline panel, open the eyeball next to GridX so that the grid is shown in the normal state

When I do the above and preview I see the following where data is missing from the table when I click on the 2nd button to switch to Grid state:

![screenshot](http://i.imgur.com/KCaOb.png)

**Comment by painbank** [comment] 2012-08-21 14:15
Yes, that is essentially it.  I did try a different demo project, just as you did, but I was unable to repeat it.

**Comment by aerwin** [comment] 2012-08-26 14:58
@painbank 

Hmmm... well, turns out I don't think I reproduced it either. I think the fact I didn't see data in my test case is because of #2899 (which I don't think you could be running into unless you're using nightly builds).

So, since neither of us can reproduce and it seems you have a workaround for your original app, I'm thinking we should just close this issue.

Please let me know if you have further questions, or if you disagree with my assessment.

**Closed as completed** 2012-08-26 15:00 UTC
Labels: States, Priority High, Lib: GridX, Severity 3

**Comment by painbank** [comment] 2012-08-26 15:56
Let me do some investigation, but I think #2899 may be the issue I am running into.  I am using a nightly build.
