### ISSUE TITLE
Login page redirects to workbench, not review and commenting task

### ISSUE THREAD

**Issue by peller** [maqetta/maqetta#1494] opened 2012-01-07 18:18 UTC
@JonFerraiolo, @childsb, @waynevicknair 

When responding to a review & commenting e-mail invitation, the first time I click on the link I may need to authenticate at the login screen.  If so, authentication leads me to the main workbench, not to the review and commenting page.  I must close the window and click on the link again

**Comment by JonFerraiolo** [comment] 2012-01-07 18:47
This should go away with the R/C merger into core. There will be only one redirect URL.

**Comment by JonFerraiolo** [comment] 2012-03-10 00:58
Actually, there will be one redirect URL, but there might be different URL parameters or URL fragment identifiers that provide review information and tell the Maqetta application which review sessions need to be automatically opened and brought to top at the start of the session.

Still, this bug will probably get closed as "no longer applicable" once we get all of the above redirect logic working.

**Comment by jhpedemonte** [comment] 2012-03-14 21:35
@childsb, was this fixed by any of your latest R&C-related changes?

**Comment by childsb** [comment] 2012-03-14 21:37
no

**Comment by jhpedemonte** [comment] 2012-03-15 21:59
-> @childsb

**Comment by childsb** [comment] 2012-03-21 21:17
@waynevicknair re-opening per discussion with Wayne-

"Clicking a review link while already logged in to maqetta wont bring up the Review Editor." 

There seems to be a timing error that causes this sporadically.  Continuing investigation..

**Comment by JonFerraiolo** [comment] 2012-03-22 12:43
This morning using latest build on lab9:50020, I created a review invitation to myself for Sample1.html.rev. Clicking on the link in the review invitation for Mac/Chrome brought up the review editor, but for FF the review editor for Sample1.html.rev does not come up automatically.

**Comment by childsb** [comment] 2012-03-22 15:42
jon, 

can you clear your browser cache/cookies and try again?  this is working for me on fire fox.

the big issue was that the cookie set on the server had a path of /, and files loaded under /maqetta/ couldn't erase the cookie. i suspect you have the old cookie and FF is having problems updating it.

**Comment by jhpedemonte** [comment] 2012-03-22 17:15
Is this a migration issue?

**Comment by JonFerraiolo** [comment] 2012-03-22 17:27
Can't be a migration issue. lab9:50020 gets cleared every day. No legacy content around, except Sample1.html', but R/C logic treats HTML files as black boxes.

**Comment by jhpedemonte** [comment] 2012-03-22 17:39
I was wondering more about old cookies that are laying around.  Brad has made a few cookie changes -- will those changes affect users coming from M4?

**Comment by childsb** [comment] 2012-03-22 18:03
No this shouldn't be a migration issue. These cookies were introduced in m5.

**Comment by peller** [comment] 2012-03-22 19:27
What is the cookie?  Can you make sure it's listed in the [cookie list](https://github.com/maqetta/maqetta/wiki/Cookie-list)?  and can we make it start with "maq"?

**Comment by JonFerraiolo** [comment] 2012-03-22 21:52
FYI @peller 

I believe I found the problem. It's an intermittent timing bug with logic in pagedesigner.html calling `Workbench._createEditor` to open a review editor. Sometimes other async processes aren't yet ready, so sometimes the following call:

```
tabContainer = dijit.byId("editors_tabcontainer"),
```

returns undefined because `showPerspective()` (which creates the TabContainer for the editors) hasn't been called yet.

One way to fix this is to create some sort of global deferred object (e.g., Runtime.editors_tabcontainer_deferred) and have the logic in pagedesigner.html that launches review editors wait until that deferred has been resolved, and have showPerspective resolve that deferred. Such an approach would be _really ugly_ but I can't think of a better way without a whole bunch of refactoring.

**Comment by JonFerraiolo** [comment] 2012-03-22 22:31
@peller noticed this and wants to take this, so reassigning to him. He thinks he can figure out a relatively clean and safe way to use a deferred.

**Comment by JonFerraiolo** [comment] 2012-03-22 22:37
Here is how I got this bug to reproduce itself most of the time:
- No breakpoints. Instead, to debug I added a bunch of console.log statements to figure out what was going on.
- Launched Maqetta from Eclipse with no editors, browser cached cleared, using Mac/FF, and launched using the URL from a review invitation that I copied/pasted into the review bar.
  You should get a console error message about addChild or other such message that comes from tabContainer being undefined. If you can't get it to fail with the above, you might have to find a way to delay the call to showPerspective by putting it in a setTimeout or other such nonsense.

**Closed as completed** 2012-03-23 22:57 UTC
Labels: Server, Review and Commenting, Bug, Priority High
