### ISSUE TITLE
Investigate/profile page editing and Properties paletFrom a user perspective, the page editor and the Properties palette are the centerpiece of daVinci. We should use profiling tools to check to see where performance problems are and fix any things that q

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#252] opened 2011-05-09 16:40 UTC
From a user perspective, the page editor and the Properties palette are the
centerpiece of daVinci. We should use profiling tools to check to see where
performance problems are and fix any things that quality as low-hanging fruit.

bug: 7254

**Comment by JonFerraiolo** [comment] 2012-07-18 03:08
-> @peller If this is a dupe of a difference performance bug, please close

**Closed as completed** 2012-07-18 20:41 UTC
Labels: Properties View, Visual Editor, Priority Med, Performance, Severity 3
