### ISSUE TITLE
No "Remove Value" item in background-image pulldown

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#2003] opened 2012-03-26 17:59 UTC
Following the /test/testplan/PropertiesPalette/basic5.html instructions, Step 3 under "background-image on a DIV" say to select "Remove value":

> 3 Under background-image, select "Remove value" from the dropdown. Verify that DIV now has no background image.

However, there is no such option. Selecting the empty entry results in removing the value.

I'm not sure if this is actually a bug or if the test case just needs to be tweaked,

**Comment by jhpedemonte** [comment] 2012-05-01 19:47
cc @JonFerraiolo 

I'm fine just staying with the empty value as the "remove" option.

**Comment by JonFerraiolo** [comment] 2012-05-01 19:53
It shouldn't be hard to include an explicit Remove option. We used to have one, but when I made all of the background property changes (Background.js and BackgroundDialog.js) I neglected the Remove option.

**Comment by JonFerraiolo** [comment] 2012-05-17 22:54
Closing as dupe of #1785

**Closed as completed by JonFerraiolo** 2012-05-17 22:54 UTC
Labels: Properties View, Priority Low
