### ISSUE TITLE
Big (and weird) problem setting theme set in on mobile page 

### ISSUE THREAD

**Issue by aerwin** [maqetta/maqetta#3167] opened 2012-08-29 22:52 UTC
@billreed63 

Really weird issue on Safari on Mac... 

Working through Theme Sets test case... completed "Applying theme sets to HTML" test case (e.g., clicked OK when changing themes to _dojo_theme_set_).

Display started alternating between these two states for several mins before crashing Safari.

![GitHub Logo](http://i.imgur.com/3UjVS.png)

![GitHub Logo](http://i.imgur.com/xKN3D.png)

Lots of these exceptions in console:

```
davinci.js:50435TypeError: 'undefined' is not an object (evaluating '(this.valueNode||this.focusNode).form')
```

**Comment by aerwin** [comment] 2012-08-29 22:58
After restarting the browser, the page seems to have settled on the 1st image above (the corrupt rendering), and no errors in console.

**Comment by aerwin** [comment] 2012-08-29 23:10
Probably pointless, but moved on to the "Restore dojo default theme to HTML" section after restarting the browser. I was able to switch the theme, but got back into kind of a flickering state after switching to the "(none)" theme set. And, it's kind of difficult to do anything in the browser. Very weird state of affairs in that I can save the file, but it's dirty bit comes back on on each flicker.

Here's the HTML source at this point. There are a couple of stick notes I accidentally added that I'm having trouble getting rid of:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Untitled</title>
<script type="text/javascript" src="lib/dojo/dojo/dojo.js" data-dojo-config="'parseOnLoad':true,'packages':[{'name':'gridx','location':'../gridx'},{'name':'clipart','location':'../../clipart'},{'name':'maqettaSamples','location':'../../../samples'},{'name':'maqetta','location':'../../maqetta'},{'name':'shapes','location':'../../shapes'},{'name':'zazl','location':'../../zazl'},{'name':'widgets','location':'../../custom'}],'themeMap':null,'mblThemeFiles':null,'mblLoadCompatPattern':null"></script>
<script type="text/javascript">
require([
  "dijit/dijit",
  "dojo/parser",
  "maqetta/space",
  "maqetta/AppStates",
  "dojox/mobile",
  "dojox/mobile/deviceTheme",
  "dojox/mobile/compat",
  "dojo/hash"
]);
</script>
<style>@import "themes/claro/claro.css";@import "app.css";
</style>
<script type="text/javascript" src="app.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no"></meta>
</head>
<body data-maq-device="iphone" data-maq-flow-layout="true" data-maq-ws="collapse" data-maq-appstates="{}" class="claro" id="myapp">
 <div data-dojo-type="dojox.mobile.View" id="View_0" style="height: 100%;" selected="selected">
   <h1 label="Heading" data-dojo-type="dojox.mobile.Heading"></h1>
 </div>
 <div dvwidget="html.stickynote" style="border-width: 2px; border-style: solid; border-color: black; border-radius: 5px 5px 0 0; -moz-border-radius: 5px 5px 0 0; position: absolute; height: 100px; width: 100px; background-color: #F9FFC2; z-index: 925; -webkit-border-radius: 5px 5px 0 0; left: 50px; top: 29px;" class="stickyNote">
   <i>
     Enter Note</i>
 </div>
 <div dvwidget="html.stickynote" style="border-width: 2px; border-style: solid; border-color: black; border-radius: 5px 5px 0 0; -moz-border-radius: 5px 5px 0 0; position: absolute; height: 100px; width: 100px; background-color: #F9FFC2; z-index: 925; -webkit-border-radius: 5px 5px 0 0; left: 50px; top: 50px;" class="stickyNote">
   <i>
          Enter Note</i>
 </div>
</body>
</html>



```

**Comment by aerwin** [comment] 2012-08-29 23:15
Last post on this one (I hope)... browser crashed again, and page rendering seems to be what I'd expect after switching theme sets to "none" (e.g., back to normal):

![GitHub Logo](http://i.imgur.com/5aS2A.png)

**Comment by billreed63** [comment] 2012-08-30 20:16
I could never reproduce the error although I did notice that the `,'themeMap':null,'mblThemeFiles':null,'mblLoadCompatPattern':null"`` is wrong and that is the bug that I fixed with the above commit.

**Comment by billreed63** [comment] 2012-08-30 21:03
I was able to reproduce with tony's html.. now to figure out why....

**Comment by billreed63** [comment] 2012-08-30 21:12
So this seems to be a combinations of changing the theme with a html that has view... What is interesting is that if I change the theme and then add a view I get the same flicker of the page being refreshed....

**Closed as completed** 2012-09-04 14:57 UTC
Labels: Theme Editor, Priority Critical, Severity 1
