### ISSUE TITLE
Improved performance for pulling down widget metadata files (*_oam.json)

### ISSUE THREAD

**Issue by JonFerraiolo** [maqetta/maqetta#165] opened 2011-05-03 21:59 UTC
The performance problem is when you mousedown over a widget on the widget
palette for the first time. daVinci does a server request to get the oam.json
file. On a slow network, this can take a few seconds, at which point the icon
appears next to the cursor, and only then can you move the mouse to the canvas
and successfully complete the drop operation.

Also, if you have a file with multiple widgets, refresh the daVinci browser
window, and open that file, there is a delay as we do N server requests, one
for each of the oam.json files (sequentially due to sync XHR).

------- Comment #3 From Javier Pedemonte 2011-01-28 15:08 -------

Well, one fix is to stop using synchronous XHR (as already discussed).  That
way, an async XHR is kicked off when the user does a mousedown on a widget. 
While this metadata request is going on in the background, the user is still
allowed to drag/drop the widget on to the canvas.  If the metadata has been
retrieved, then things go on as expected.  If the connection is slow and the
metadata has not yet been retrieved, then a placeholder is dropped on to the
canvas, in place of the widget.  When the metadata finally arrives, the
placeholder is replaced with the widget data.

------- Comment #4 From Jon Ferraiolo 2011-01-28 15:25 -------

Sure, of course, switch to async when we have the time to make this change, but
async or sync, we still have to wait for the web request(s) to complete and it
is a major performance problem when running daVinci off of a server running
over a slow connection, and nearly every hosting site we have tried so far
falls into the "slow connection" category.

------- Comment #5 From Jon Ferraiolo 2011-03-24 11:28 [reply] -------

Left as P3 for 0.81, because this is a performance issue with page editor, but
unlikely we can implement something safe and effective in time.

------- Comment #6 From Javier Pedemonte 2011-03-24 13:49 [reply] -------

For the time being, can we add the metadata files to the appcache?  We have a
limited number of libraries, and the metadata isn't that big (i don't think),
so this may be a temporary way to increase perf, until we come up with a better
solution.

------- Comment #7 From bradley childs 2011-03-24 13:53 [reply] -------

javier - the appcache bug we fixed yesterday (or 2 days ago?) moved metadata to
appcache.  i believe adam cleaned up the appcache manifest afterwards moving
everything with ./app prefix to appcache.

------- Comment #8 From Javier Pedemonte 2011-03-24 17:41 [reply] -------

(In reply to comment #7)
Talked to Adam, and this is not the case:  metadata files are not stored in the
appcache.

However, I did look at the Net panel while working with mtc03.  Metadata
loading is a very small percentage of the loading wait time.  Most of the
loading time is spent with the required resources listed in the metadata (JS,
CSS, images, etc).  So improving the performance of the metadata files by
themselves really won't get us much.

**Comment by jhpedemonte** [comment] 2011-11-04 02:44
Dupe of #844.

**Closed as completed by jhpedemonte** 2011-11-04 02:44 UTC
Labels: Widgets Palette, Widget Libraries, Priority High, Performance
