### ISSUE TITLE
Manually added style rules doesn't apply in design mode

### ISSUE THREAD

**Issue by doronrosenberg** [maqetta/maqetta#2089] opened 2012-04-16 19:29 UTC
@JonFerraiolo @peller @jhpedemonte 

If I add this using source editor:

```
<style>
  .red {
    color : red;
  }

  .blue {
    color : blue;
  }

</style>
</head>
<body class="claro" dvFlowLayout="true" data-davinci-ws="collapse" id="myapp">
 <div class="blue">
   test</div>
 <div class="red">
 test2</div>
 <div class="blue">
test3</div>
 <div class="red">
   test 4</div>
</body>
```

None of those custom defined styles rules are applied when in design mode, even if I reload the html page.  They only show up correctly when previewed.

I couldn't find any existing bug for this, but my search skills are quite lacking.

**Comment by doronrosenberg** [comment] 2012-04-16 19:33
Also should add: setting the class names using the properties panel also doesn't apply the style rules

**Comment by billreed63** [comment] 2012-08-14 17:41
@JonFerraiolo @jhpedemonte 

-> M8

**Comment by JonFerraiolo** [comment] 2012-08-14 17:54
I think this is mostly a dupe of #156

**Comment by jhpedemonte** [comment] 2012-08-17 01:29
Closing as duplicate of #156.

**Closed as completed by jhpedemonte** 2012-08-17 01:29 UTC
Labels: Bug, Priority Low, Severity 2
