### ISSUE TITLE
custom mobile theme results in no CS in VE

### ISSUE THREAD

**Issue by childsb** [maqetta/maqetta#3049] opened 2012-08-22 23:18 UTC
1) create a new iphone theme
2) select a global widget and set its background color to red
3) create a new html file, chose iphone silhouette
4) after the file comes up, switch the theme to the custom theme created in step 1
5) add a widget to the page (calendar for me) and notice it has no styling/theme.

**Comment by billreed63** [comment] 2012-08-23 15:10
I am unable to reproduce this.

What browser and platform? 

 I am also confused by the steps, calendar is part of the desktop widget set so it is styled my claro not iphone

I was able to create an myiphone theme and change the background of the global heading widgets and apply that theme to a mobile html page. I was able to drop a heading on the page and get the correct styling on the headings. I added a calendar widget at it had the claro styling as expected.

If you still reproduce this, please reopen.

**Comment by billreed63** [comment] 2012-08-23 19:29
closing with above comment

**Closed as completed by billreed63** 2012-08-23 19:29 UTC
Labels: Priority Critical, Severity 2
